"""Deprecated ``python -m nodebpy.assets`` entry point; use ``nodebpy``.

Forwards to the ``nodebpy`` command (:mod:`nodebpy.__main__`) with a
``FutureWarning``, and will be removed in nodebpy 530. Subcommands pass
through unchanged (``python -m nodebpy.assets dump …`` runs ``nodebpy dump
…``), and the old flag-based codegen interface (``-b lib.blend -o DIR``)
runs ``nodebpy dump --api-only lib.blend DIR``. The :mod:`nodebpy.assets`
module itself stays.
"""

from __future__ import annotations

import argparse
import sys
import warnings
from pathlib import Path

# ``blender ... -P .../nodebpy/assets/__main__.py`` runs this file as a plain
# script (no package context): put the package root on sys.path so the
# absolute imports resolve, a no-op under ``python -m nodebpy.assets``.
if not __package__:  # pragma: no cover - only under blender -P
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))


def _api_dump_argv(argv: list[str]) -> list[str]:
    """The flag-based codegen command line as a ``dump --api-only`` one."""
    parser = argparse.ArgumentParser(prog="python -m nodebpy.assets")
    parser.add_argument("--blend-file", "-b", type=Path)
    parser.add_argument("--output", "--output-dir", "-o", dest="output", type=Path)
    parser.add_argument("--nodebpy-pkg")
    parser.add_argument("--no-docstrings", dest="docstrings", action="store_false")
    args = parser.parse_args(argv)
    if args.blend_file is None:
        raise SystemExit(
            "python -m nodebpy.assets: nodebpy's own bundled-essentials classes "
            "are regenerated by 'python -m gen' (make generate)."
        )
    if args.output is None or args.output.suffix == ".py":
        raise SystemExit(
            "python -m nodebpy.assets: 'nodebpy dump --api-only' writes one "
            "module per asset, so -o must be a directory; for a single module "
            "call nodebpy.assets.generate_asset_api."
        )
    forwarded = ["dump", "--api-only", str(args.blend_file), str(args.output)]
    if args.nodebpy_pkg:
        forwarded += ["--nodebpy-pkg", args.nodebpy_pkg]
    if not args.docstrings:
        forwarded.append("--no-docstrings")
    return forwarded


def main() -> None:
    # Blender passes script arguments after a ``--`` separator: strip
    # everything up to and including it.
    argv = sys.argv[1:]
    if "--" in sys.argv:
        argv = sys.argv[sys.argv.index("--") + 1 :]

    # The flag-based codegen interface took no positionals, so a leading
    # positional is always a subcommand.
    if not argv or argv[0].startswith("-"):
        argv = _api_dump_argv(argv)
    warnings.warn(
        "'python -m nodebpy.assets' is deprecated and will be removed in "
        f"nodebpy 530; use 'nodebpy {' '.join(argv[:2])}' instead.",
        FutureWarning,
        stacklevel=2,
    )

    from nodebpy.__main__ import main as nodebpy_main

    nodebpy_main(argv)


if __name__ == "__main__":  # pragma: no cover
    main()
