"""Configuration, staleness stamping and roundtrip checking for the asset
pipeline CLI (``python -m nodebpy.assets``).

Downstream projects keep a dumped source tree and a built ``.blend`` in fixed
places, so the CLI's positional arguments and flags can come from a
``[tool.nodebpy.assets]`` table in the nearest ``pyproject.toml`` (walking up
from the working directory) instead of being retyped — or wrapped in a
project-local script — on every invocation::

    [tool.nodebpy.assets]
    source = "mypkg/nodes"                    # the dumped sources: build's
                                              # <source>, and the dump target
    blend = "mypkg/assets/nodes.blend"
    resources = "mypkg/assets/resources.blend"
    typed-api = true
    add-reroutes = true
    iterations = 100

Keys are spelled like the CLI flags they stand in for (kebab-case; ``source``
and ``blend`` supply the positionals); paths are relative to the pyproject's
directory. Explicit CLI arguments always override the table, and a positional
neither given nor configured errors naming both the argument and the config
key.

``build`` and (full) ``dump`` record a fingerprint of everything the
``.blend`` derives from in a ``<blend>.stamp`` sidecar — nodebpy's own
version, the resolved build/dump options, the source files and the resources
``.blend``'s bytes — so ``ensure`` can skip the rebuild when nothing changed
by comparing hashes alone. ``check`` verifies the roundtrip fixed point:
building the sources and dumping the result back out must reproduce them
byte-for-byte.

This module stays free of module-level ``bpy``: deciding whether a rebuild is
needed only hashes files, and ``check``'s stages run as subprocesses (each
needs a fresh session anyway) — only the spawn decision peeks at
``bpy.app.binary_path``, deferred until a stage actually runs.
"""

from __future__ import annotations

import hashlib
import os
import subprocess
import sys
import tempfile
from argparse import Namespace
from importlib import metadata
from pathlib import Path

#: Catalog definition file that Blender keeps next to an asset library.
CATALOG_FILENAME = "blender_assets.cats.txt"

_INIT_CONTENT = "# Package marker for nodebpy-dumped asset sources.\n"

_GENERATED_INIT_HEADER = (
    "# Auto-generated by nodebpy.assets.dump_library — do not edit manually."
)


def _is_generated_init(path: Path) -> bool:
    """Whether ``path`` is an ``__init__.py`` nodebpy wrote (marker or plain
    package marker) rather than a hand-written one."""
    first_line = path.read_text(encoding="utf-8").split("\n", 1)[0]
    return first_line in (_GENERATED_INIT_HEADER, _INIT_CONTENT.rstrip("\n"))


# ---------------------------------------------------------------------------
# [tool.nodebpy.assets] pyproject configuration
# ---------------------------------------------------------------------------

# Config keys, spelled like the CLI flags they stand in for, mapped to
# (argparse dest, kind). "path" and "value" fill a dest the command line left
# at None (paths resolve against the pyproject's directory); "flag" turns a
# store_true dest on; "off" turns an inverted flag's dest off (`no-compress =
# true` means what passing --no-compress does); "drop" maps `drop-missing =
# true` onto on_missing="drop". The two positional keys carry no fixed dest —
# it depends on the subcommand (dump's <output> is the source directory).
_CONFIG_KEYS: dict[str, tuple[str | None, str]] = {
    "source": (None, "path"),
    "blend": (None, "path"),
    "resources": ("resources", "path"),
    "nodebpy-pkg": ("nodebpy_pkg", "value"),
    "typed-api": ("typed_api", "flag"),
    "snapshot-positions": ("snapshot_positions", "flag"),
    "keep-reroutes": ("keep_reroutes", "flag"),
    "no-materials": ("materials", "off"),
    "allow-existing": ("allow_existing", "flag"),
    "no-compress": ("compress", "off"),
    "drop-missing": ("on_missing", "drop"),
    "add-reroutes": ("add_reroutes", "flag"),
    "spacing": ("spacing", "value"),
    "iterations": ("iterations", "value"),
    "direction": ("direction", "value"),
    "socket-alignment": ("socket_alignment", "value"),
    "keep-reroutes-outside-frames": ("keep_reroutes_outside_frames", "flag"),
    "no-stack-collapsed": ("stack_collapsed", "off"),
    "stack-margin-y-fac": ("stack_margin_y_fac", "value"),
    "optimize-sizes": ("optimize_sizes", "flag"),
}

# Which dest each positional config key fills, per subcommand: the dump
# target directory *is* the source directory of the other subcommands.
_POSITIONAL_DESTS: dict[str, dict[str, str]] = {
    "dump": {"blend": "blend", "source": "output"},
    "build": {"source": "source", "blend": "blend"},
    "ensure": {"source": "source", "blend": "blend"},
    "check": {"source": "source", "blend": "blend"},
}

# Parser defaults for every configurable dest, so `apply_config` can fill
# dests a subcommand's parser doesn't define and all four subcommands resolve
# the same full option set — the stamp fingerprint hashes it, and a stamp
# written by `dump` must match the one `ensure` computes.
_OPTION_DEFAULTS: dict[str, object] = {
    "resources": None,
    "nodebpy_pkg": None,
    "typed_api": False,
    "snapshot_positions": False,
    "keep_reroutes": False,
    "materials": True,
    "allow_existing": False,
    "compress": True,
    "on_missing": "error",
    "add_reroutes": False,
    "spacing": None,
    "iterations": None,
    "direction": None,
    "socket_alignment": None,
    "keep_reroutes_outside_frames": False,
    "stack_collapsed": True,
    "stack_margin_y_fac": None,
    "optimize_sizes": False,
}

# The resolved options the stamp fingerprint covers: everything, beyond the
# source and resources bytes themselves, that changes what build (or the
# dump refreshing the stamp) writes. allow_existing is deliberately absent —
# it gates the session check, not the output.
_STAMP_DESTS = (
    "add_reroutes",
    "compress",
    "direction",
    "iterations",
    "keep_reroutes",
    "keep_reroutes_outside_frames",
    "materials",
    "nodebpy_pkg",
    "on_missing",
    "optimize_sizes",
    "snapshot_positions",
    "socket_alignment",
    "spacing",
    "stack_collapsed",
    "stack_margin_y_fac",
    "typed_api",
)


def load_config(start: str | Path | None = None) -> tuple[dict, Path | None]:
    """The ``[tool.nodebpy.assets]`` table of the nearest ``pyproject.toml``
    at or above ``start`` (default: the working directory), plus the
    directory it was found in — paths in the table are relative to it.

    The walk stops at the first ``pyproject.toml`` whether or not it carries
    the table (the nearest project owns the configuration); no pyproject at
    all yields ``({}, None)``.
    """
    import tomllib

    directory = Path(start if start is not None else Path.cwd()).resolve()
    for candidate in (directory, *directory.parents):
        pyproject = candidate / "pyproject.toml"
        if pyproject.is_file():
            with pyproject.open("rb") as stream:
                data = tomllib.load(stream)
            table = data.get("tool", {}).get("nodebpy", {}).get("assets", {})
            if not isinstance(table, dict):
                raise SystemExit(f"[tool.nodebpy.assets] in {pyproject} is not a table")
            return table, candidate
    return {}, None


def apply_config(args: Namespace, start: str | Path | None = None) -> None:
    """Merge the nearest pyproject's ``[tool.nodebpy.assets]`` table into the
    parsed CLI namespace, in place.

    Explicit CLI arguments win: a config value only fills a dest the command
    line left at its default (and a boolean flag key can only push the dest
    the way passing the flag would). Dests the subcommand's parser doesn't
    define are filled too — config value or default — so every subcommand
    resolves the same full option set for the stamp fingerprint.
    """
    config, config_dir = load_config(start)
    if unknown := sorted(set(config) - set(_CONFIG_KEYS)):
        raise SystemExit(
            f"Unknown [tool.nodebpy.assets] keys in pyproject.toml: {unknown} "
            f"(known: {sorted(_CONFIG_KEYS)})"
        )
    positionals = _POSITIONAL_DESTS[args.command]
    for key, (dest, kind) in _CONFIG_KEYS.items():
        if dest is None:
            dest = positionals[key]
        if not hasattr(args, dest):
            setattr(args, dest, _OPTION_DEFAULTS[dest])
        if key not in config:
            continue
        value = config[key]
        current = getattr(args, dest)
        if kind == "path" and current is None:
            assert config_dir is not None  # a key exists, so a table was found
            setattr(args, dest, config_dir / str(value))
        elif kind == "value" and current is None:
            if dest in ("direction", "socket_alignment") and isinstance(value, str):
                value = value.upper()  # the CLI upper-cases these choices too
            setattr(args, dest, value)
        elif kind == "flag" and value:
            setattr(args, dest, True)
        elif kind == "off" and value:
            setattr(args, dest, False)
        elif kind == "drop" and value and current == "error":
            setattr(args, dest, "drop")
    if args.nodebpy_pkg is None:  # the flag's documented default
        args.nodebpy_pkg = "nodebpy"


def require_positionals(args: Namespace) -> None:
    """Error out, argparse-style, when a positional neither given on the
    command line nor supplied by the config is still missing — naming both
    the argument and the config key that could provide it."""
    for key, dest in _POSITIONAL_DESTS[args.command].items():
        if getattr(args, dest) is None:
            raise SystemExit(
                f"{args.command}: the <{dest}> argument is required — pass it "
                f"on the command line or set {key!r} under "
                "[tool.nodebpy.assets] in pyproject.toml."
            )


# ---------------------------------------------------------------------------
# Fingerprint stamping (build/dump write it, ensure compares it)
# ---------------------------------------------------------------------------


def stamp_options(args: Namespace) -> dict[str, object]:
    """The resolved option values the stamp fingerprint covers, read
    uniformly off any subcommand's namespace (:func:`apply_config` fills the
    dests a parser doesn't define)."""
    options: dict[str, object] = {}
    for dest in _STAMP_DESTS:
        value = getattr(args, dest)
        options[dest] = tuple(value) if isinstance(value, list) else value
    return options


def fingerprint(
    source_dir: str | Path,
    resources: str | Path | None,
    options: dict[str, object],
) -> str:
    """Hash of everything the built ``.blend`` derives from: nodebpy's own
    version, the resolved options, the source files' paths and bytes, and the
    resources ``.blend``'s bytes when one is configured.

    The source files are every ``.py`` under ``source_dir`` plus the catalog
    file — a deliberate overapproximation of what the build imports (root
    modules pull in ``_shared`` helpers, and could import a sibling runtime
    module), so a change can only ever err towards rebuilding. No ``bpy``
    involved: staleness is decided from bytes alone.
    """
    source_dir = Path(source_dir)
    digest = hashlib.sha256()
    digest.update(metadata.version("nodebpy").encode())
    digest.update(repr(sorted(options.items())).encode())
    files = sorted(
        p
        for p in source_dir.rglob("*")
        if p.is_file()
        and (p.suffix == ".py" or p.name == CATALOG_FILENAME)
        and "__pycache__" not in p.relative_to(source_dir).parts
    )
    for path in files:
        digest.update(path.relative_to(source_dir).as_posix().encode())
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    if resources is not None and Path(resources).is_file():
        digest.update(b"resources\0")
        digest.update(Path(resources).read_bytes())
    return digest.hexdigest()


def stamp_path(blend: str | Path) -> Path:
    """The sidecar file recording the fingerprint ``blend`` was built from."""
    blend = Path(blend)
    return blend.with_name(blend.name + ".stamp")


def write_stamp(
    blend: str | Path,
    source_dir: str | Path,
    resources: str | Path | None,
    options: dict[str, object],
) -> None:
    """Record the current fingerprint next to ``blend`` — call after a build
    or a full dump, when the ``.blend`` and the sources match by
    construction."""
    stamp_path(blend).write_text(
        fingerprint(source_dir, resources, options) + "\n", encoding="utf-8"
    )


def is_stale(
    blend: str | Path,
    source_dir: str | Path,
    resources: str | Path | None,
    options: dict[str, object],
) -> bool:
    """Whether the built ``.blend`` is missing or behind the sources — a pure
    hash comparison against the stamp, cheap enough to run on every
    ``ensure``."""
    blend = Path(blend)
    stamp = stamp_path(blend)
    if not blend.is_file() or not stamp.is_file():
        return True
    return stamp.read_text(encoding="utf-8").strip() != fingerprint(
        source_dir, resources, options
    )


# ---------------------------------------------------------------------------
# check: roundtrip fixed-point verification
# ---------------------------------------------------------------------------


def _build_stage_flags(args: Namespace) -> list[str]:
    """Serialise the resolved build options back into CLI flags, so a
    subprocess stage builds exactly as ``build`` would here — explicit flags
    override whatever config the child process would otherwise re-load."""
    flags: list[str] = []
    if args.resources is not None:
        flags += ["--resources", str(args.resources)]
    if args.on_missing == "drop":
        flags.append("--drop-missing")
    if not args.compress:
        flags.append("--no-compress")
    if args.add_reroutes:
        flags.append("--add-reroutes")
    if args.spacing is not None:
        flags += ["--spacing", *(str(value) for value in args.spacing)]
    if args.iterations is not None:
        flags += ["--iterations", str(args.iterations)]
    if args.direction is not None:
        flags += ["--direction", args.direction]
    if args.socket_alignment is not None:
        flags += ["--socket-alignment", args.socket_alignment]
    if args.keep_reroutes_outside_frames:
        flags.append("--keep-reroutes-outside-frames")
    if not args.stack_collapsed:
        flags.append("--no-stack-collapsed")
    if args.stack_margin_y_fac is not None:
        flags += ["--stack-margin-y-fac", str(args.stack_margin_y_fac)]
    if args.optimize_sizes:
        flags.append("--optimize-sizes")
    return flags


def _dump_stage_flags(args: Namespace) -> list[str]:
    """Serialise the resolved dump options back into CLI flags, as
    :func:`_build_stage_flags` does for the build stage."""
    flags = ["--nodebpy-pkg", str(args.nodebpy_pkg)]
    if args.typed_api:
        flags.append("--typed-api")
    if args.snapshot_positions:
        flags.append("--snapshot-positions")
    if args.keep_reroutes:
        flags.append("--keep-reroutes")
    if not args.materials:
        flags.append("--no-materials")
    return flags


def run_stage(argv: list[str]) -> None:
    """Run one pipeline stage (any ``nodebpy.assets`` subcommand) in a fresh
    session — :func:`~nodebpy.assets.build_library` and
    :func:`~nodebpy.assets.dump_library` each require one, so ``check``
    cannot run its stages in this process.

    With the ``bpy`` module a plain interpreter carries a session; inside a
    full Blender (``bpy.app.binary_path`` non-empty) another Blender is
    spawned onto the CLI entry (``-b --factory-startup -P .../__main__.py --
    <argv>``), with an isolated extensions directory so the spawn can't pick
    up stale wheels.
    """
    import bpy  # deferred: only the spawn decision needs the session

    env = os.environ.copy()
    if bpy.app.binary_path:  # pragma: no cover - needs a full Blender
        env["BLENDER_USER_EXTENSIONS"] = tempfile.mkdtemp(prefix="nodebpy-ext-")
        entry = Path(__file__).with_name("__main__.py")
        cmd = [
            bpy.app.binary_path,
            "-b",
            "--factory-startup",
            "-P",
            str(entry),
            "--",
            *argv,
        ]
    else:
        cmd = [sys.executable, "-m", "nodebpy.assets", *argv]
    subprocess.run(cmd, check=True, env=env)


def compare_sources(source_dir: Path, redump_dir: Path) -> tuple[list[str], int]:
    """Compare a dumped source tree against a re-dump of its built library.

    Byte-exact, with two deliberate exemptions: ``_``-prefixed files at the
    source root (downstream runtime modules the dump never writes), and the
    top-level ``__init__.py`` when it is hand-written (the dump leaves it
    untouched in place, so the re-dump's generated marker is no divergence —
    :func:`_is_generated_init` semantics). Everything else must match
    exactly, file sets included: a file present on only one side is a
    failure. Returns the offending files (set differences first, then
    content differences, each sorted) and the number of ``.py`` modules
    compared.
    """

    def tree(root: Path) -> set[Path]:
        return {
            p.relative_to(root)
            for p in root.rglob("*")
            if p.is_file()
            and (p.suffix == ".py" or p.name == CATALOG_FILENAME)
            and "__pycache__" not in p.relative_to(root).parts
        }

    src_files = tree(source_dir)
    new_files = tree(redump_dir)
    src_files -= {
        f
        for f in src_files
        if len(f.parts) == 1 and f.name.startswith("_") and f.name != "__init__.py"
    }
    init = source_dir / "__init__.py"
    if init.is_file() and not _is_generated_init(init):
        src_files.discard(Path("__init__.py"))
        new_files.discard(Path("__init__.py"))

    problems = sorted(str(f) for f in src_files ^ new_files)
    matching = src_files & new_files
    problems += sorted(
        str(f)
        for f in matching
        if (source_dir / f).read_bytes() != (redump_dir / f).read_bytes()
    )
    modules = len({f for f in matching if f.suffix == ".py"})
    return problems, modules


def check_roundtrip(args: Namespace) -> None:
    """The ``check`` subcommand: verify the roundtrip fixed point — building
    the sources and dumping the result back out must reproduce them
    byte-for-byte. Catches hand-edited sources the dumper would normalise
    differently, stale-datablock shadowing from a resources ``.blend``, and
    nodebpy drift.

    The build and dump stages run via :func:`run_stage` into a temporary
    directory; the dump is anchored at the real source directory and
    ``.blend`` location (``--anchor``), so its typed-API ``PackageLibrary``
    paths come out byte-identical to the real sources despite being written
    somewhere else.
    """
    source_dir = Path(args.source)
    with tempfile.TemporaryDirectory(prefix="nodebpy-check-") as tmp:
        blend = Path(tmp) / "library.blend"
        redump = Path(tmp) / "sources"
        run_stage(["build", str(source_dir), str(blend), *_build_stage_flags(args)])
        run_stage(
            [
                "dump",
                str(blend),
                str(redump),
                "--anchor",
                str(source_dir),
                str(args.blend),
                *_dump_stage_flags(args),
            ]
        )
        problems, modules = compare_sources(source_dir, redump)
        if problems:
            print("Sources do not survive the build->dump roundtrip:")
            for name in problems:
                print(f"  {name}")
            print(
                "Rebuild and re-dump to normalise them:\n"
                "  python -m nodebpy.assets build && python -m nodebpy.assets dump"
            )
            raise SystemExit(1)
    print(f"Roundtrip OK: {modules} source modules reproduce exactly")
