# Auto-generated by generate.py — do not edit manually.


import bpy

from ...builder import NodeBuilder, SocketLinker

from ...types import (
    InputFloat,
)


class Normalize(NodeBuilder):
    """
    Map values to 0 to 1 range, based on the minimum and maximum pixel values
    """

    _bl_idname = "CompositorNodeNormalize"
    node: bpy.types.CompositorNodeNormalize

    def __init__(self, value: InputFloat = 1.0):
        super().__init__()
        key_args = {"Value": value}

        self._establish_links(**key_args)

    @property
    def i_value(self) -> SocketLinker:
        """Input socket: Value"""
        return self.inputs.get("Value")

    class Outputs:
        __slots__ = ("_node",)

        def __init__(self, node: "Normalize") -> None:
            self._node = node

        @property
        def value(self) -> SocketLinker:
            """Output socket: Value"""
            return self._node.outputs.get("Value")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return Normalize.Outputs(self)
