# Auto-generated by generate.py — do not edit manually.

from typing import Literal

import bpy

from ...builder import (
    NodeBuilder,
    SocketLinker,
    TypedInputs,
    TypedOutputs,
    ColorSocketLinker,
    RotationSocketLinker,
    VectorSocketLinker,
)

from ...types import (
    InputClosure,
    InputColor,
    InputRotation,
    InputShader,
    InputFloat,
    InputVector,
)


class CombineColor(NodeBuilder):
    """
    Create a color from individual components using multiple models
    """

    _bl_idname = "ShaderNodeCombineColor"
    node: bpy.types.ShaderNodeCombineColor

    def __init__(
        self,
        red: InputFloat = 0.0,
        green: InputFloat = 0.0,
        blue: InputFloat = 0.0,
        *,
        mode: Literal["RGB", "HSV", "HSL"] = "RGB",
    ):
        super().__init__()
        key_args = {"Red": red, "Green": green, "Blue": blue}
        self.mode = mode
        self._establish_links(**key_args)

    class Inputs(TypedInputs):
        @property
        def red(self) -> SocketLinker:
            """Input socket: Red"""
            return self.get("Red")

        @property
        def green(self) -> SocketLinker:
            """Input socket: Green"""
            return self.get("Green")

        @property
        def blue(self) -> SocketLinker:
            """Input socket: Blue"""
            return self.get("Blue")

    @property
    def i(self) -> "Inputs":
        return CombineColor.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def color(self) -> ColorSocketLinker:
            """Output socket: Color"""
            return self.get("Color")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return CombineColor.Outputs(self)

    @property
    def mode(self) -> Literal["RGB", "HSV", "HSL"]:
        return self.node.mode

    @mode.setter
    def mode(self, value: Literal["RGB", "HSV", "HSL"]):
        self.node.mode = value


class EvaluateClosure(NodeBuilder):
    """
    Execute a given closure
    """

    _bl_idname = "NodeEvaluateClosure"
    node: bpy.types.Node

    def __init__(
        self,
        closure: InputClosure = None,
        *,
        active_input_index: int = 0,
        active_output_index: int = 0,
        define_signature: bool = False,
    ):
        super().__init__()
        key_args = {"Closure": closure}
        self.active_input_index = active_input_index
        self.active_output_index = active_output_index
        self.define_signature = define_signature
        self._establish_links(**key_args)

    class Inputs(TypedInputs):
        @property
        def closure(self) -> SocketLinker:
            """Input socket: Closure"""
            return self.get("Closure")

    @property
    def i(self) -> "Inputs":
        return EvaluateClosure.Inputs(self)

    @property
    def active_input_index(self) -> int:
        return self.node.active_input_index

    @active_input_index.setter
    def active_input_index(self, value: int):
        self.node.active_input_index = value

    @property
    def active_output_index(self) -> int:
        return self.node.active_output_index

    @active_output_index.setter
    def active_output_index(self, value: int):
        self.node.active_output_index = value

    @property
    def define_signature(self) -> bool:
        return self.node.define_signature

    @define_signature.setter
    def define_signature(self, value: bool):
        self.node.define_signature = value


class Mix(NodeBuilder):
    """
    Mix values by a factor
    """

    _bl_idname = "ShaderNodeMix"
    node: bpy.types.ShaderNodeMix

    def __init__(
        self,
        factor_float: InputFloat = 0.5,
        factor_vector: InputVector = None,
        a_float: InputFloat = 0.0,
        b_float: InputFloat = 0.0,
        a_vector: InputVector = None,
        b_vector: InputVector = None,
        a_color: InputColor = None,
        b_color: InputColor = None,
        a_rotation: InputRotation = None,
        b_rotation: InputRotation = None,
        *,
        data_type: Literal["FLOAT", "VECTOR", "RGBA"] = "FLOAT",
        factor_mode: Literal["UNIFORM", "NON_UNIFORM"] = "UNIFORM",
        blend_type: Literal[
            "MIX",
            "DARKEN",
            "MULTIPLY",
            "BURN",
            "LIGHTEN",
            "SCREEN",
            "DODGE",
            "ADD",
            "OVERLAY",
            "SOFT_LIGHT",
            "LINEAR_LIGHT",
            "DIFFERENCE",
            "EXCLUSION",
            "SUBTRACT",
            "DIVIDE",
            "HUE",
            "SATURATION",
            "COLOR",
            "VALUE",
        ] = "MIX",
        clamp_factor: bool = False,
        clamp_result: bool = False,
    ):
        super().__init__()
        key_args = {
            "Factor_Float": factor_float,
            "Factor_Vector": factor_vector,
            "A_Float": a_float,
            "B_Float": b_float,
            "A_Vector": a_vector,
            "B_Vector": b_vector,
            "A_Color": a_color,
            "B_Color": b_color,
            "A_Rotation": a_rotation,
            "B_Rotation": b_rotation,
        }
        self.data_type = data_type
        self.factor_mode = factor_mode
        self.blend_type = blend_type
        self.clamp_factor = clamp_factor
        self.clamp_result = clamp_result
        self._establish_links(**key_args)

    @classmethod
    def float(
        cls, factor: InputFloat = 0.5, a: InputFloat = 0.0, b: InputFloat = 0.0
    ) -> "Mix":
        """Create Mix with operation 'Float'."""
        return cls(data_type="FLOAT", factor_float=factor, a_float=a, b_float=b)

    @classmethod
    def vector(
        cls, factor: InputFloat = 0.5, a: InputVector = None, b: InputVector = None
    ) -> "Mix":
        """Create Mix with operation 'Vector'."""
        return cls(data_type="VECTOR", factor_float=factor, a_vector=a, b_vector=b)

    @classmethod
    def color(
        cls,
        factor: InputFloat = 0.5,
        a_color: InputColor = None,
        b_color: InputColor = None,
    ) -> "Mix":
        """Create Mix with operation 'Color'."""
        return cls(
            data_type="RGBA", factor_float=factor, a_color=a_color, b_color=b_color
        )

    class Inputs(TypedInputs):
        @property
        def factor_float(self) -> SocketLinker:
            """Input socket: Factor"""
            return self.get("Factor_Float")

        @property
        def factor_vector(self) -> SocketLinker:
            """Input socket: Factor"""
            return self.get("Factor_Vector")

        @property
        def a_float(self) -> SocketLinker:
            """Input socket: A"""
            return self.get("A_Float")

        @property
        def b_float(self) -> SocketLinker:
            """Input socket: B"""
            return self.get("B_Float")

        @property
        def a_vector(self) -> SocketLinker:
            """Input socket: A"""
            return self.get("A_Vector")

        @property
        def b_vector(self) -> SocketLinker:
            """Input socket: B"""
            return self.get("B_Vector")

        @property
        def a_color(self) -> SocketLinker:
            """Input socket: A"""
            return self.get("A_Color")

        @property
        def b_color(self) -> SocketLinker:
            """Input socket: B"""
            return self.get("B_Color")

        @property
        def a_rotation(self) -> SocketLinker:
            """Input socket: A"""
            return self.get("A_Rotation")

        @property
        def b_rotation(self) -> SocketLinker:
            """Input socket: B"""
            return self.get("B_Rotation")

    @property
    def i(self) -> "Inputs":
        return Mix.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def result_float(self) -> SocketLinker:
            """Output socket: Result"""
            return self.get("Result_Float")  # type: ignore[return-value]

        @property
        def result_vector(self) -> VectorSocketLinker:
            """Output socket: Result"""
            return self.get("Result_Vector")  # type: ignore[return-value]

        @property
        def result_color(self) -> ColorSocketLinker:
            """Output socket: Result"""
            return self.get("Result_Color")  # type: ignore[return-value]

        @property
        def result_rotation(self) -> RotationSocketLinker:
            """Output socket: Result"""
            return self.get("Result_Rotation")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return Mix.Outputs(self)

    @property
    def data_type(self) -> Literal["FLOAT", "VECTOR", "RGBA"]:
        return self.node.data_type

    @data_type.setter
    def data_type(self, value: Literal["FLOAT", "VECTOR", "RGBA"]):
        self.node.data_type = value

    @property
    def factor_mode(self) -> Literal["UNIFORM", "NON_UNIFORM"]:
        return self.node.factor_mode

    @factor_mode.setter
    def factor_mode(self, value: Literal["UNIFORM", "NON_UNIFORM"]):
        self.node.factor_mode = value

    @property
    def blend_type(
        self,
    ) -> Literal[
        "MIX",
        "DARKEN",
        "MULTIPLY",
        "BURN",
        "LIGHTEN",
        "SCREEN",
        "DODGE",
        "ADD",
        "OVERLAY",
        "SOFT_LIGHT",
        "LINEAR_LIGHT",
        "DIFFERENCE",
        "EXCLUSION",
        "SUBTRACT",
        "DIVIDE",
        "HUE",
        "SATURATION",
        "COLOR",
        "VALUE",
    ]:
        return self.node.blend_type

    @blend_type.setter
    def blend_type(
        self,
        value: Literal[
            "MIX",
            "DARKEN",
            "MULTIPLY",
            "BURN",
            "LIGHTEN",
            "SCREEN",
            "DODGE",
            "ADD",
            "OVERLAY",
            "SOFT_LIGHT",
            "LINEAR_LIGHT",
            "DIFFERENCE",
            "EXCLUSION",
            "SUBTRACT",
            "DIVIDE",
            "HUE",
            "SATURATION",
            "COLOR",
            "VALUE",
        ],
    ):
        self.node.blend_type = value

    @property
    def clamp_factor(self) -> bool:
        return self.node.clamp_factor

    @clamp_factor.setter
    def clamp_factor(self, value: bool):
        self.node.clamp_factor = value

    @property
    def clamp_result(self) -> bool:
        return self.node.clamp_result

    @clamp_result.setter
    def clamp_result(self, value: bool):
        self.node.clamp_result = value


class RGBToBw(NodeBuilder):
    """
    Convert a color's luminance to a grayscale value
    """

    _bl_idname = "ShaderNodeRGBToBW"
    node: bpy.types.ShaderNodeRGBToBW

    def __init__(self, color: InputColor = None):
        super().__init__()
        key_args = {"Color": color}

        self._establish_links(**key_args)

    class Inputs(TypedInputs):
        @property
        def color(self) -> SocketLinker:
            """Input socket: Color"""
            return self.get("Color")

    @property
    def i(self) -> "Inputs":
        return RGBToBw.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def val(self) -> SocketLinker:
            """Output socket: Val"""
            return self.get("Val")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return RGBToBw.Outputs(self)


class SeparateColor(NodeBuilder):
    """
    Split a color into its individual components using multiple models
    """

    _bl_idname = "ShaderNodeSeparateColor"
    node: bpy.types.ShaderNodeSeparateColor

    def __init__(
        self,
        color: InputColor = None,
        *,
        mode: Literal["RGB", "HSV", "HSL"] = "RGB",
    ):
        super().__init__()
        key_args = {"Color": color}
        self.mode = mode
        self._establish_links(**key_args)

    class Inputs(TypedInputs):
        @property
        def color(self) -> SocketLinker:
            """Input socket: Color"""
            return self.get("Color")

    @property
    def i(self) -> "Inputs":
        return SeparateColor.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def red(self) -> SocketLinker:
            """Output socket: Red"""
            return self.get("Red")  # type: ignore[return-value]

        @property
        def green(self) -> SocketLinker:
            """Output socket: Green"""
            return self.get("Green")  # type: ignore[return-value]

        @property
        def blue(self) -> SocketLinker:
            """Output socket: Blue"""
            return self.get("Blue")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return SeparateColor.Outputs(self)

    @property
    def mode(self) -> Literal["RGB", "HSV", "HSL"]:
        return self.node.mode

    @mode.setter
    def mode(self, value: Literal["RGB", "HSV", "HSL"]):
        self.node.mode = value


class ShaderToRGB(NodeBuilder):
    """
        Convert rendering effect (such as light and shadow) to color. Typically used for non-photorealistic rendering, to apply additional effects on the output of BSDFs.
    Note: only supported in EEVEE
    """

    _bl_idname = "ShaderNodeShaderToRGB"
    node: bpy.types.ShaderNodeShaderToRGB

    def __init__(self, shader: InputShader = None):
        super().__init__()
        key_args = {"Shader": shader}

        self._establish_links(**key_args)

    class Inputs(TypedInputs):
        @property
        def shader(self) -> SocketLinker:
            """Input socket: Shader"""
            return self.get("Shader")

    @property
    def i(self) -> "Inputs":
        return ShaderToRGB.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def color(self) -> ColorSocketLinker:
            """Output socket: Color"""
            return self.get("Color")  # type: ignore[return-value]

        @property
        def alpha(self) -> SocketLinker:
            """Output socket: Alpha"""
            return self.get("Alpha")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return ShaderToRGB.Outputs(self)


class Wavelength(NodeBuilder):
    """
    Convert a wavelength value to an RGB value
    """

    _bl_idname = "ShaderNodeWavelength"
    node: bpy.types.ShaderNodeWavelength

    def __init__(self, wavelength: InputFloat = 500.0):
        super().__init__()
        key_args = {"Wavelength": wavelength}

        self._establish_links(**key_args)

    class Inputs(TypedInputs):
        @property
        def wavelength(self) -> SocketLinker:
            """Input socket: Wavelength"""
            return self.get("Wavelength")

    @property
    def i(self) -> "Inputs":
        return Wavelength.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def color(self) -> ColorSocketLinker:
            """Output socket: Color"""
            return self.get("Color")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return Wavelength.Outputs(self)
