# Auto-generated by generate.py — do not edit manually.

from typing import Literal

import bpy

from ...builder import BaseNode as NodeBuilder, Socket, FloatSocket, VectorSocket

from ...types import (
    InputColor,
    InputFloat,
    InputVector,
)


class Bump(NodeBuilder):
    """
    Generate a perturbed normal from a height texture for bump mapping. Typically used for faking highly detailed surfaces
    """

    _bl_idname = "ShaderNodeBump"
    node: bpy.types.ShaderNodeBump

    def __init__(
        self,
        strength: InputFloat = 1.0,
        distance: InputFloat = 0.001,
        filter_width: InputFloat = 0.1,
        height: InputFloat = 1.0,
        normal: InputVector = None,
        *,
        invert: bool = False,
    ):
        super().__init__()
        key_args = {
            "Strength": strength,
            "Distance": distance,
            "Filter Width": filter_width,
            "Height": height,
            "Normal": normal,
        }
        self.invert = invert
        self._establish_links(**key_args)

    @property
    def i_strength(self) -> Socket:
        """Input socket: Strength"""
        return self.inputs.get("Strength")

    @property
    def i_distance(self) -> Socket:
        """Input socket: Distance"""
        return self.inputs.get("Distance")

    @property
    def i_filter_width(self) -> Socket:
        """Input socket: Filter Width"""
        return self.inputs.get("Filter Width")

    @property
    def i_height(self) -> Socket:
        """Input socket: Height"""
        return self.inputs.get("Height")

    @property
    def i_normal(self) -> Socket:
        """Input socket: Normal"""
        return self.inputs.get("Normal")

    @property
    def o_normal(self) -> VectorSocket:
        """Output socket: Normal"""
        return self.outputs.get("Normal")

    @property
    def invert(self) -> bool:
        return self.node.invert

    @invert.setter
    def invert(self, value: bool):
        self.node.invert = value


class Displacement(NodeBuilder):
    """
    Displace the surface along the surface normal
    """

    _bl_idname = "ShaderNodeDisplacement"
    node: bpy.types.ShaderNodeDisplacement

    def __init__(
        self,
        height: InputFloat = 0.0,
        midlevel: InputFloat = 0.5,
        scale: InputFloat = 0.01,
        normal: InputVector = None,
        *,
        space: Literal["OBJECT", "WORLD"] = "OBJECT",
    ):
        super().__init__()
        key_args = {
            "Height": height,
            "Midlevel": midlevel,
            "Scale": scale,
            "Normal": normal,
        }
        self.space = space
        self._establish_links(**key_args)

    @property
    def i_height(self) -> Socket:
        """Input socket: Height"""
        return self.inputs.get("Height")

    @property
    def i_midlevel(self) -> Socket:
        """Input socket: Midlevel"""
        return self.inputs.get("Midlevel")

    @property
    def i_scale(self) -> Socket:
        """Input socket: Scale"""
        return self.inputs.get("Scale")

    @property
    def i_normal(self) -> Socket:
        """Input socket: Normal"""
        return self.inputs.get("Normal")

    @property
    def o_displacement(self) -> VectorSocket:
        """Output socket: Displacement"""
        return self.outputs.get("Displacement")

    @property
    def space(self) -> Literal["OBJECT", "WORLD"]:
        return self.node.space

    @space.setter
    def space(self, value: Literal["OBJECT", "WORLD"]):
        self.node.space = value


class Mapping(NodeBuilder):
    """
    Transform the input vector by applying translation, rotation, and scale
    """

    _bl_idname = "ShaderNodeMapping"
    node: bpy.types.ShaderNodeMapping

    def __init__(
        self,
        vector: InputVector = None,
        location: InputVector = None,
        rotation: InputVector = None,
        scale: InputVector = None,
        *,
        vector_type: Literal["POINT", "TEXTURE", "VECTOR", "NORMAL"] = "POINT",
    ):
        super().__init__()
        key_args = {
            "Vector": vector,
            "Location": location,
            "Rotation": rotation,
            "Scale": scale,
        }
        self.vector_type = vector_type
        self._establish_links(**key_args)

    @property
    def i_vector(self) -> Socket:
        """Input socket: Vector"""
        return self.inputs.get("Vector")

    @property
    def i_location(self) -> Socket:
        """Input socket: Location"""
        return self.inputs.get("Location")

    @property
    def i_rotation(self) -> Socket:
        """Input socket: Rotation"""
        return self.inputs.get("Rotation")

    @property
    def i_scale(self) -> Socket:
        """Input socket: Scale"""
        return self.inputs.get("Scale")

    @property
    def o_vector(self) -> VectorSocket:
        """Output socket: Vector"""
        return self.outputs.get("Vector")

    @property
    def vector_type(self) -> Literal["POINT", "TEXTURE", "VECTOR", "NORMAL"]:
        return self.node.vector_type

    @vector_type.setter
    def vector_type(self, value: Literal["POINT", "TEXTURE", "VECTOR", "NORMAL"]):
        self.node.vector_type = value


class Normal(NodeBuilder):
    """
    Generate a normal vector and a dot product
    """

    _bl_idname = "ShaderNodeNormal"
    node: bpy.types.ShaderNodeNormal

    def __init__(self, normal: InputVector = None):
        super().__init__()
        key_args = {"Normal": normal}

        self._establish_links(**key_args)

    @property
    def i_normal(self) -> Socket:
        """Input socket: Normal"""
        return self.inputs.get("Normal")

    @property
    def o_normal(self) -> VectorSocket:
        """Output socket: Normal"""
        return self.outputs.get("Normal")

    @property
    def o_dot(self) -> FloatSocket:
        """Output socket: Dot"""
        return self.outputs.get("Dot")


class NormalMap(NodeBuilder):
    """
    Generate a perturbed normal from an RGB normal map image. Typically used for faking highly detailed surfaces
    """

    _bl_idname = "ShaderNodeNormalMap"
    node: bpy.types.ShaderNodeNormalMap

    def __init__(
        self,
        strength: InputFloat = 1.0,
        color: InputColor = None,
        *,
        space: Literal[
            "TANGENT", "OBJECT", "WORLD", "BLENDER_OBJECT", "BLENDER_WORLD"
        ] = "TANGENT",
        uv_map: str = "",
    ):
        super().__init__()
        key_args = {"Strength": strength, "Color": color}
        self.space = space
        self.uv_map = uv_map
        self._establish_links(**key_args)

    @property
    def i_strength(self) -> Socket:
        """Input socket: Strength"""
        return self.inputs.get("Strength")

    @property
    def i_color(self) -> Socket:
        """Input socket: Color"""
        return self.inputs.get("Color")

    @property
    def o_normal(self) -> VectorSocket:
        """Output socket: Normal"""
        return self.outputs.get("Normal")

    @property
    def space(
        self,
    ) -> Literal["TANGENT", "OBJECT", "WORLD", "BLENDER_OBJECT", "BLENDER_WORLD"]:
        return self.node.space

    @space.setter
    def space(
        self,
        value: Literal["TANGENT", "OBJECT", "WORLD", "BLENDER_OBJECT", "BLENDER_WORLD"],
    ):
        self.node.space = value

    @property
    def uv_map(self) -> str:
        return self.node.uv_map

    @uv_map.setter
    def uv_map(self, value: str):
        self.node.uv_map = value


class VectorDisplacement(NodeBuilder):
    """
    Displace the surface along an arbitrary direction
    """

    _bl_idname = "ShaderNodeVectorDisplacement"
    node: bpy.types.ShaderNodeVectorDisplacement

    def __init__(
        self,
        vector: InputColor = None,
        midlevel: InputFloat = 0.0,
        scale: InputFloat = 0.01,
        *,
        space: Literal["TANGENT", "OBJECT", "WORLD"] = "TANGENT",
    ):
        super().__init__()
        key_args = {"Vector": vector, "Midlevel": midlevel, "Scale": scale}
        self.space = space
        self._establish_links(**key_args)

    @property
    def i_vector(self) -> Socket:
        """Input socket: Vector"""
        return self.inputs.get("Vector")

    @property
    def i_midlevel(self) -> Socket:
        """Input socket: Midlevel"""
        return self.inputs.get("Midlevel")

    @property
    def i_scale(self) -> Socket:
        """Input socket: Scale"""
        return self.inputs.get("Scale")

    @property
    def o_displacement(self) -> VectorSocket:
        """Output socket: Displacement"""
        return self.outputs.get("Displacement")

    @property
    def space(self) -> Literal["TANGENT", "OBJECT", "WORLD"]:
        return self.node.space

    @space.setter
    def space(self, value: Literal["TANGENT", "OBJECT", "WORLD"]):
        self.node.space = value


class VectorTransform(NodeBuilder):
    """
    Convert a vector, point, or normal between world, camera, and object coordinate space
    """

    _bl_idname = "ShaderNodeVectorTransform"
    node: bpy.types.ShaderNodeVectorTransform

    def __init__(
        self,
        vector: InputVector = None,
        *,
        vector_type: Literal["POINT", "VECTOR", "NORMAL"] = "VECTOR",
        convert_from: Literal["WORLD", "OBJECT", "CAMERA"] = "WORLD",
        convert_to: Literal["WORLD", "OBJECT", "CAMERA"] = "OBJECT",
    ):
        super().__init__()
        key_args = {"Vector": vector}
        self.vector_type = vector_type
        self.convert_from = convert_from
        self.convert_to = convert_to
        self._establish_links(**key_args)

    @property
    def i_vector(self) -> Socket:
        """Input socket: Vector"""
        return self.inputs.get("Vector")

    @property
    def o_vector(self) -> VectorSocket:
        """Output socket: Vector"""
        return self.outputs.get("Vector")

    @property
    def vector_type(self) -> Literal["POINT", "VECTOR", "NORMAL"]:
        return self.node.vector_type

    @vector_type.setter
    def vector_type(self, value: Literal["POINT", "VECTOR", "NORMAL"]):
        self.node.vector_type = value

    @property
    def convert_from(self) -> Literal["WORLD", "OBJECT", "CAMERA"]:
        return self.node.convert_from

    @convert_from.setter
    def convert_from(self, value: Literal["WORLD", "OBJECT", "CAMERA"]):
        self.node.convert_from = value

    @property
    def convert_to(self) -> Literal["WORLD", "OBJECT", "CAMERA"]:
        return self.node.convert_to

    @convert_to.setter
    def convert_to(self, value: Literal["WORLD", "OBJECT", "CAMERA"]):
        self.node.convert_to = value
