# Auto-generated by generate.py — do not edit manually.

from typing import Literal

import bpy

from ...builder import (
    NodeBuilder,
    SocketLinker,
    GeometrySocketLinker,
    IntegerSocketLinker,
)

from ...types import (
    InputBoolean,
    InputColor,
    InputGeometry,
    InputInteger,
    InputMatrix,
    InputMenu,
    InputRotation,
    InputString,
    InputFloat,
    InputVector,
)


class BlurAttribute(NodeBuilder):
    """
    Mix attribute values of neighboring elements
    """

    _bl_idname = "GeometryNodeBlurAttribute"
    node: bpy.types.GeometryNodeBlurAttribute

    def __init__(
        self,
        value: InputFloat = 0.0,
        iterations: InputInteger = 1,
        weight: InputFloat = 1.0,
        *,
        data_type: Literal["FLOAT", "INT", "FLOAT_VECTOR", "FLOAT_COLOR"] = "FLOAT",
    ):
        super().__init__()
        key_args = {"Value": value, "Iterations": iterations, "Weight": weight}
        self.data_type = data_type
        self._establish_links(**key_args)

    @classmethod
    def float(
        cls,
        value: InputFloat = 0.0,
        iterations: InputInteger = 1,
        weight: InputFloat = 1.0,
    ) -> "BlurAttribute":
        """Create Blur Attribute with operation 'Float'."""
        return cls(data_type="FLOAT", value=value, iterations=iterations, weight=weight)

    @classmethod
    def integer(
        cls,
        value: InputInteger = 0,
        iterations: InputInteger = 1,
        weight: InputFloat = 1.0,
    ) -> "BlurAttribute":
        """Create Blur Attribute with operation 'Integer'."""
        return cls(data_type="INT", value=value, iterations=iterations, weight=weight)

    @classmethod
    def vector(
        cls,
        value: InputVector = None,
        iterations: InputInteger = 1,
        weight: InputFloat = 1.0,
    ) -> "BlurAttribute":
        """Create Blur Attribute with operation 'Vector'."""
        return cls(
            data_type="FLOAT_VECTOR", value=value, iterations=iterations, weight=weight
        )

    @classmethod
    def color(
        cls,
        value: InputColor = None,
        iterations: InputInteger = 1,
        weight: InputFloat = 1.0,
    ) -> "BlurAttribute":
        """Create Blur Attribute with operation 'Color'."""
        return cls(
            data_type="FLOAT_COLOR", value=value, iterations=iterations, weight=weight
        )

    @property
    def i_value(self) -> SocketLinker:
        """Input socket: Value"""
        return self.inputs.get("Value")

    @property
    def i_iterations(self) -> SocketLinker:
        """Input socket: Iterations"""
        return self.inputs.get("Iterations")

    @property
    def i_weight(self) -> SocketLinker:
        """Input socket: Weight"""
        return self.inputs.get("Weight")

    class Outputs:
        __slots__ = ("_node",)

        def __init__(self, node: "BlurAttribute") -> None:
            self._node = node

        @property
        def value(self) -> SocketLinker:
            """Output socket: Value"""
            return self._node.outputs.get("Value")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return BlurAttribute.Outputs(self)

    @property
    def data_type(self) -> Literal["FLOAT", "INT", "FLOAT_VECTOR", "FLOAT_COLOR"]:
        return self.node.data_type

    @data_type.setter
    def data_type(self, value: Literal["FLOAT", "INT", "FLOAT_VECTOR", "FLOAT_COLOR"]):
        self.node.data_type = value


class DomainSize(NodeBuilder):
    """
    Retrieve the number of elements in a geometry for each attribute domain
    """

    _bl_idname = "GeometryNodeAttributeDomainSize"
    node: bpy.types.GeometryNodeAttributeDomainSize

    def __init__(
        self,
        geometry: InputGeometry = None,
        *,
        component: Literal[
            "MESH", "POINTCLOUD", "CURVE", "INSTANCES", "GREASEPENCIL"
        ] = "MESH",
    ):
        super().__init__()
        key_args = {"Geometry": geometry}
        self.component = component
        self._establish_links(**key_args)

    @property
    def i_geometry(self) -> SocketLinker:
        """Input socket: Geometry"""
        return self.inputs.get("Geometry")

    class Outputs:
        __slots__ = ("_node",)

        def __init__(self, node: "DomainSize") -> None:
            self._node = node

        @property
        def point_count(self) -> IntegerSocketLinker:
            """Output socket: Point Count"""
            return self._node.outputs.get("Point Count")  # type: ignore[return-value]

        @property
        def edge_count(self) -> IntegerSocketLinker:
            """Output socket: Edge Count"""
            return self._node.outputs.get("Edge Count")  # type: ignore[return-value]

        @property
        def face_count(self) -> IntegerSocketLinker:
            """Output socket: Face Count"""
            return self._node.outputs.get("Face Count")  # type: ignore[return-value]

        @property
        def face_corner_count(self) -> IntegerSocketLinker:
            """Output socket: Face Corner Count"""
            return self._node.outputs.get("Face Corner Count")  # type: ignore[return-value]

        @property
        def spline_count(self) -> IntegerSocketLinker:
            """Output socket: Spline Count"""
            return self._node.outputs.get("Spline Count")  # type: ignore[return-value]

        @property
        def instance_count(self) -> IntegerSocketLinker:
            """Output socket: Instance Count"""
            return self._node.outputs.get("Instance Count")  # type: ignore[return-value]

        @property
        def layer_count(self) -> IntegerSocketLinker:
            """Output socket: Layer Count"""
            return self._node.outputs.get("Layer Count")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return DomainSize.Outputs(self)

    @property
    def component(
        self,
    ) -> Literal["MESH", "POINTCLOUD", "CURVE", "INSTANCES", "GREASEPENCIL"]:
        return self.node.component

    @component.setter
    def component(
        self, value: Literal["MESH", "POINTCLOUD", "CURVE", "INSTANCES", "GREASEPENCIL"]
    ):
        self.node.component = value


class RemoveNamedAttribute(NodeBuilder):
    """
    Delete an attribute with a specified name from a geometry. Typically used to optimize performance
    """

    _bl_idname = "GeometryNodeRemoveAttribute"
    node: bpy.types.GeometryNodeRemoveAttribute

    def __init__(
        self,
        geometry: InputGeometry = None,
        pattern_mode: InputMenu | Literal["Exact", "Wildcard"] = "Exact",
        name: InputString = "",
    ):
        super().__init__()
        key_args = {"Geometry": geometry, "Pattern Mode": pattern_mode, "Name": name}

        self._establish_links(**key_args)

    @property
    def i_geometry(self) -> SocketLinker:
        """Input socket: Geometry"""
        return self.inputs.get("Geometry")

    @property
    def i_pattern_mode(self) -> SocketLinker:
        """Input socket: Pattern Mode"""
        return self.inputs.get("Pattern Mode")

    @property
    def i_name(self) -> SocketLinker:
        """Input socket: Name"""
        return self.inputs.get("Name")

    class Outputs:
        __slots__ = ("_node",)

        def __init__(self, node: "RemoveNamedAttribute") -> None:
            self._node = node

        @property
        def geometry(self) -> GeometrySocketLinker:
            """Output socket: Geometry"""
            return self._node.outputs.get("Geometry")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return RemoveNamedAttribute.Outputs(self)


class StoreNamedAttribute(NodeBuilder):
    """
    Store the result of a field on a geometry as an attribute with the specified name
    """

    _bl_idname = "GeometryNodeStoreNamedAttribute"
    node: bpy.types.GeometryNodeStoreNamedAttribute

    def __init__(
        self,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputFloat = 0.0,
        *,
        data_type: Literal[
            "FLOAT",
            "INT",
            "BOOLEAN",
            "FLOAT_VECTOR",
            "FLOAT_COLOR",
            "QUATERNION",
            "FLOAT4X4",
            "INT8",
            "FLOAT2",
            "BYTE_COLOR",
        ] = "FLOAT",
        domain: Literal[
            "POINT", "EDGE", "FACE", "CORNER", "CURVE", "INSTANCE", "LAYER"
        ] = "POINT",
    ):
        super().__init__()
        key_args = {
            "Geometry": geometry,
            "Selection": selection,
            "Name": name,
            "Value": value,
        }
        self.data_type = data_type
        self.domain = domain
        self._establish_links(**key_args)

    @classmethod
    def float(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputFloat = 0.0,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Float'."""
        return cls(
            data_type="FLOAT",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def integer(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputInteger = 0,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Integer'."""
        return cls(
            data_type="INT",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def boolean(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputBoolean = False,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Boolean'."""
        return cls(
            data_type="BOOLEAN",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def vector(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputVector = None,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Vector'."""
        return cls(
            data_type="FLOAT_VECTOR",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def color(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputColor = None,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Color'."""
        return cls(
            data_type="FLOAT_COLOR",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def quaternion(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputRotation = None,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Quaternion'."""
        return cls(
            data_type="QUATERNION",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def matrix(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputMatrix = None,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation '4x4 Matrix'."""
        return cls(
            data_type="FLOAT4X4",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def int8(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputInteger = 0,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation '8-Bit Integer'."""
        return cls(
            data_type="INT8",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def vector2(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputVector = None,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation '2D Vector'."""
        return cls(
            data_type="FLOAT2",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def byte_color(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputColor = None,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Byte Color'."""
        return cls(
            data_type="BYTE_COLOR",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def point(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputFloat = 0.0,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Point'."""
        return cls(
            domain="POINT",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def edge(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputFloat = 0.0,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Edge'."""
        return cls(
            domain="EDGE",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def face(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputFloat = 0.0,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Face'."""
        return cls(
            domain="FACE",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def face_corner(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputFloat = 0.0,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Face Corner'."""
        return cls(
            domain="CORNER",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def spline(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputFloat = 0.0,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Spline'."""
        return cls(
            domain="CURVE",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def instance(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputFloat = 0.0,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Instance'."""
        return cls(
            domain="INSTANCE",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def layer(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputFloat = 0.0,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Layer'."""
        return cls(
            domain="LAYER",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @property
    def i_geometry(self) -> SocketLinker:
        """Input socket: Geometry"""
        return self.inputs.get("Geometry")

    @property
    def i_selection(self) -> SocketLinker:
        """Input socket: Selection"""
        return self.inputs.get("Selection")

    @property
    def i_name(self) -> SocketLinker:
        """Input socket: Name"""
        return self.inputs.get("Name")

    @property
    def i_value(self) -> SocketLinker:
        """Input socket: Value"""
        return self.inputs.get("Value")

    class Outputs:
        __slots__ = ("_node",)

        def __init__(self, node: "StoreNamedAttribute") -> None:
            self._node = node

        @property
        def geometry(self) -> GeometrySocketLinker:
            """Output socket: Geometry"""
            return self._node.outputs.get("Geometry")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return StoreNamedAttribute.Outputs(self)

    @property
    def data_type(
        self,
    ) -> Literal[
        "FLOAT",
        "INT",
        "BOOLEAN",
        "FLOAT_VECTOR",
        "FLOAT_COLOR",
        "QUATERNION",
        "FLOAT4X4",
        "INT8",
        "FLOAT2",
        "BYTE_COLOR",
    ]:
        return self.node.data_type

    @data_type.setter
    def data_type(
        self,
        value: Literal[
            "FLOAT",
            "INT",
            "BOOLEAN",
            "FLOAT_VECTOR",
            "FLOAT_COLOR",
            "QUATERNION",
            "FLOAT4X4",
            "INT8",
            "FLOAT2",
            "BYTE_COLOR",
        ],
    ):
        self.node.data_type = value

    @property
    def domain(
        self,
    ) -> Literal["POINT", "EDGE", "FACE", "CORNER", "CURVE", "INSTANCE", "LAYER"]:
        return self.node.domain

    @domain.setter
    def domain(
        self,
        value: Literal["POINT", "EDGE", "FACE", "CORNER", "CURVE", "INSTANCE", "LAYER"],
    ):
        self.node.domain = value
