# Auto-generated by generate.py — do not edit manually.

from typing import TYPE_CHECKING, Literal

import bpy

from ...builder import (
    BaseNode as NodeBuilder,
    SocketAccessor,
    BooleanSocket,
    FloatSocket,
    GeometrySocket,
    IntegerSocket,
    MenuSocket,
    StringSocket,
)

from ...types import (
    InputBoolean,
    InputColor,
    InputGeometry,
    InputInteger,
    InputMatrix,
    InputMenu,
    InputRotation,
    InputString,
    InputFloat,
    InputVector,
)


class BlurAttribute(NodeBuilder):
    """
    Mix attribute values of neighboring elements

    Parameters
    ----------
    value : InputFloat
        Value
    iterations : InputInteger
        Iterations
    weight : InputFloat
        Weight

    Inputs
    ------
    i.value : FloatSocket
        Value
    i.iterations : IntegerSocket
        Iterations
    i.weight : FloatSocket
        Weight

    Outputs
    -------
    o.value : FloatSocket
        Value
    """

    _bl_idname = "GeometryNodeBlurAttribute"
    node: bpy.types.GeometryNodeBlurAttribute

    class _Inputs(SocketAccessor):
        value: FloatSocket
        """Value"""
        iterations: IntegerSocket
        """Iterations"""
        weight: FloatSocket
        """Weight"""

    class _Outputs(SocketAccessor):
        value: FloatSocket
        """Value"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        value: InputFloat = 0.0,
        iterations: InputInteger = 1,
        weight: InputFloat = 1.0,
        *,
        data_type: Literal["FLOAT", "INT", "FLOAT_VECTOR", "FLOAT_COLOR"] = "FLOAT",
    ):
        super().__init__()
        key_args = {"Value": value, "Iterations": iterations, "Weight": weight}
        self.data_type = data_type
        self._establish_links(**key_args)

    @classmethod
    def float(
        cls,
        value: InputFloat = 0.0,
        iterations: InputInteger = 1,
        weight: InputFloat = 1.0,
    ) -> "BlurAttribute":
        """Create Blur Attribute with operation 'Float'. Floating-point value"""
        return cls(data_type="FLOAT", value=value, iterations=iterations, weight=weight)

    @classmethod
    def integer(
        cls,
        value: InputInteger = 0,
        iterations: InputInteger = 1,
        weight: InputFloat = 1.0,
    ) -> "BlurAttribute":
        """Create Blur Attribute with operation 'Integer'. 32-bit integer"""
        return cls(data_type="INT", value=value, iterations=iterations, weight=weight)

    @classmethod
    def vector(
        cls,
        value: InputVector = None,
        iterations: InputInteger = 1,
        weight: InputFloat = 1.0,
    ) -> "BlurAttribute":
        """Create Blur Attribute with operation 'Vector'. 3D vector with floating-point values"""
        return cls(
            data_type="FLOAT_VECTOR", value=value, iterations=iterations, weight=weight
        )

    @classmethod
    def color(
        cls,
        value: InputColor = None,
        iterations: InputInteger = 1,
        weight: InputFloat = 1.0,
    ) -> "BlurAttribute":
        """Create Blur Attribute with operation 'Color'. RGBA color with 32-bit floating-point values"""
        return cls(
            data_type="FLOAT_COLOR", value=value, iterations=iterations, weight=weight
        )

    @property
    def data_type(self) -> Literal["FLOAT", "INT", "FLOAT_VECTOR", "FLOAT_COLOR"]:
        return self.node.data_type

    @data_type.setter
    def data_type(self, value: Literal["FLOAT", "INT", "FLOAT_VECTOR", "FLOAT_COLOR"]):
        self.node.data_type = value


class DomainSize(NodeBuilder):
    """
    Retrieve the number of elements in a geometry for each attribute domain

    Parameters
    ----------
    geometry : InputGeometry
        Geometry

    Inputs
    ------
    i.geometry : GeometrySocket
        Geometry

    Outputs
    -------
    o.point_count : IntegerSocket
        Point Count
    o.edge_count : IntegerSocket
        Edge Count
    o.face_count : IntegerSocket
        Face Count
    o.face_corner_count : IntegerSocket
        Face Corner Count
    o.spline_count : IntegerSocket
        Spline Count
    o.instance_count : IntegerSocket
        Instance Count
    o.layer_count : IntegerSocket
        Layer Count
    """

    _bl_idname = "GeometryNodeAttributeDomainSize"
    node: bpy.types.GeometryNodeAttributeDomainSize

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""

    class _Outputs(SocketAccessor):
        point_count: IntegerSocket
        """Point Count"""
        edge_count: IntegerSocket
        """Edge Count"""
        face_count: IntegerSocket
        """Face Count"""
        face_corner_count: IntegerSocket
        """Face Corner Count"""
        spline_count: IntegerSocket
        """Spline Count"""
        instance_count: IntegerSocket
        """Instance Count"""
        layer_count: IntegerSocket
        """Layer Count"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        *,
        component: Literal[
            "MESH", "POINTCLOUD", "CURVE", "INSTANCES", "GREASEPENCIL"
        ] = "MESH",
    ):
        super().__init__()
        key_args = {"Geometry": geometry}
        self.component = component
        self._establish_links(**key_args)

    @property
    def component(
        self,
    ) -> Literal["MESH", "POINTCLOUD", "CURVE", "INSTANCES", "GREASEPENCIL"]:
        return self.node.component

    @component.setter
    def component(
        self, value: Literal["MESH", "POINTCLOUD", "CURVE", "INSTANCES", "GREASEPENCIL"]
    ):
        self.node.component = value


class RemoveNamedAttribute(NodeBuilder):
    """
    Delete an attribute with a specified name from a geometry. Typically used to optimize performance

    Parameters
    ----------
    geometry : InputGeometry
        Geometry
    pattern_mode : InputMenu | Literal['Exact', 'Wildcard']
        Pattern Mode
    name : InputString
        Name

    Inputs
    ------
    i.geometry : GeometrySocket
        Geometry
    i.pattern_mode : MenuSocket
        Pattern Mode
    i.name : StringSocket
        Name

    Outputs
    -------
    o.geometry : GeometrySocket
        Geometry
    """

    _bl_idname = "GeometryNodeRemoveAttribute"
    node: bpy.types.GeometryNodeRemoveAttribute

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        pattern_mode: MenuSocket
        """Pattern Mode"""
        name: StringSocket
        """Name"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        pattern_mode: InputMenu | Literal["Exact", "Wildcard"] = "Exact",
        name: InputString = "",
    ):
        super().__init__()
        key_args = {"Geometry": geometry, "Pattern Mode": pattern_mode, "Name": name}

        self._establish_links(**key_args)


class StoreNamedAttribute(NodeBuilder):
    """
    Store the result of a field on a geometry as an attribute with the specified name

    Parameters
    ----------
    geometry : InputGeometry
        Geometry
    selection : InputBoolean
        Selection
    name : InputString
        Name
    value : InputFloat
        Value

    Inputs
    ------
    i.geometry : GeometrySocket
        Geometry
    i.selection : BooleanSocket
        Selection
    i.name : StringSocket
        Name
    i.value : FloatSocket
        Value

    Outputs
    -------
    o.geometry : GeometrySocket
        Geometry
    """

    _bl_idname = "GeometryNodeStoreNamedAttribute"
    node: bpy.types.GeometryNodeStoreNamedAttribute

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        selection: BooleanSocket
        """Selection"""
        name: StringSocket
        """Name"""
        value: FloatSocket
        """Value"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputFloat = 0.0,
        *,
        data_type: Literal[
            "FLOAT",
            "INT",
            "BOOLEAN",
            "FLOAT_VECTOR",
            "FLOAT_COLOR",
            "QUATERNION",
            "FLOAT4X4",
            "INT8",
            "FLOAT2",
            "BYTE_COLOR",
        ] = "FLOAT",
        domain: Literal[
            "POINT", "EDGE", "FACE", "CORNER", "CURVE", "INSTANCE", "LAYER"
        ] = "POINT",
    ):
        super().__init__()
        key_args = {
            "Geometry": geometry,
            "Selection": selection,
            "Name": name,
            "Value": value,
        }
        self.data_type = data_type
        self.domain = domain
        self._establish_links(**key_args)

    @classmethod
    def float(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputFloat = 0.0,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Float'. Floating-point value"""
        return cls(
            data_type="FLOAT",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def integer(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputInteger = 0,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Integer'. 32-bit integer"""
        return cls(
            data_type="INT",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def boolean(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputBoolean = False,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Boolean'. True or false"""
        return cls(
            data_type="BOOLEAN",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def vector(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputVector = None,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Vector'. 3D vector with floating-point values"""
        return cls(
            data_type="FLOAT_VECTOR",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def color(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputColor = None,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Color'. RGBA color with 32-bit floating-point values"""
        return cls(
            data_type="FLOAT_COLOR",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def quaternion(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputRotation = None,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Quaternion'. Floating point quaternion rotation"""
        return cls(
            data_type="QUATERNION",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def input_4x4_matrix(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputMatrix = None,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation '4x4 Matrix'. Floating point matrix"""
        return cls(
            data_type="FLOAT4X4",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def input_8_bit_integer(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputInteger = 0,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation '8-Bit Integer'. Smaller integer with a range from -128 to 127"""
        return cls(
            data_type="INT8",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def input_2d_vector(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputVector = None,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation '2D Vector'. 2D vector with floating-point values"""
        return cls(
            data_type="FLOAT2",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def byte_color(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputColor = None,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Byte Color'. RGBA color with 8-bit positive integer values"""
        return cls(
            data_type="BYTE_COLOR",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def point(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputFloat = 0.0,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Point'. Attribute on point"""
        return cls(
            domain="POINT",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def edge(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputFloat = 0.0,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Edge'. Attribute on mesh edge"""
        return cls(
            domain="EDGE",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def face(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputFloat = 0.0,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Face'. Attribute on mesh faces"""
        return cls(
            domain="FACE",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def face_corner(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputFloat = 0.0,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Face Corner'. Attribute on mesh face corner"""
        return cls(
            domain="CORNER",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def spline(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputFloat = 0.0,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Spline'. Attribute on spline"""
        return cls(
            domain="CURVE",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def instance(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputFloat = 0.0,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Instance'. Attribute on instance"""
        return cls(
            domain="INSTANCE",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @classmethod
    def layer(
        cls,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        name: InputString = "",
        value: InputFloat = 0.0,
    ) -> "StoreNamedAttribute":
        """Create Store Named Attribute with operation 'Layer'. Attribute on Grease Pencil layer"""
        return cls(
            domain="LAYER",
            geometry=geometry,
            selection=selection,
            name=name,
            value=value,
        )

    @property
    def data_type(
        self,
    ) -> Literal[
        "FLOAT",
        "INT",
        "BOOLEAN",
        "FLOAT_VECTOR",
        "FLOAT_COLOR",
        "QUATERNION",
        "FLOAT4X4",
        "INT8",
        "FLOAT2",
        "BYTE_COLOR",
    ]:
        return self.node.data_type

    @data_type.setter
    def data_type(
        self,
        value: Literal[
            "FLOAT",
            "INT",
            "BOOLEAN",
            "FLOAT_VECTOR",
            "FLOAT_COLOR",
            "QUATERNION",
            "FLOAT4X4",
            "INT8",
            "FLOAT2",
            "BYTE_COLOR",
        ],
    ):
        self.node.data_type = value

    @property
    def domain(
        self,
    ) -> Literal["POINT", "EDGE", "FACE", "CORNER", "CURVE", "INSTANCE", "LAYER"]:
        return self.node.domain

    @domain.setter
    def domain(
        self,
        value: Literal["POINT", "EDGE", "FACE", "CORNER", "CURVE", "INSTANCE", "LAYER"],
    ):
        self.node.domain = value
