# Auto-generated by generate.py — do not edit manually.


import bpy

from ...builder import BaseNode as NodeBuilder, SocketAccessor, Socket, ColorSocket

from ...types import (
    InputColor,
    InputFloat,
)


class Gamma(NodeBuilder):
    """
    Apply a gamma correction

    Parameters
    ----------
    color : InputColor
        Color
    gamma : InputFloat
        Gamma

    Outputs
    -------
    color : ColorSocket
        Color
    """

    _bl_idname = "ShaderNodeGamma"
    node: bpy.types.ShaderNodeGamma

    class Inputs(SocketAccessor):
        color: Socket
        gamma: Socket

    class Outputs(SocketAccessor):
        color: ColorSocket

    @property
    def i(self) -> "Gamma.Inputs":
        return Gamma.Inputs(self.node.inputs, "input")

    @property
    def o(self) -> "Gamma.Outputs":
        return Gamma.Outputs(self.node.outputs, "output")

    def __init__(
        self,
        color: InputColor = None,
        gamma: InputFloat = 1.0,
    ):
        super().__init__()
        key_args = {"Color": color, "Gamma": gamma}

        self._establish_links(**key_args)


class RGBCurves(NodeBuilder):
    """
    Apply color corrections for each color channel

    Parameters
    ----------
    fac : InputFloat
        Factor
    color : InputColor
        Color

    Outputs
    -------
    color : ColorSocket
        Color
    """

    _bl_idname = "ShaderNodeRGBCurve"
    node: bpy.types.ShaderNodeRGBCurve

    class Inputs(SocketAccessor):
        fac: Socket
        color: Socket

    class Outputs(SocketAccessor):
        color: ColorSocket

    @property
    def i(self) -> "RGBCurves.Inputs":
        return RGBCurves.Inputs(self.node.inputs, "input")

    @property
    def o(self) -> "RGBCurves.Outputs":
        return RGBCurves.Outputs(self.node.outputs, "output")

    def __init__(
        self,
        fac: InputFloat = 1.0,
        color: InputColor = None,
    ):
        super().__init__()
        key_args = {"Fac": fac, "Color": color}

        self._establish_links(**key_args)
