# Auto-generated by generate.py — do not edit manually.

from typing import Literal

import bpy

from ...builder import BaseNode as NodeBuilder, Socket, VectorSocket

from ...types import (
    InputBoolean,
    InputGeometry,
    InputInteger,
    InputMatrix,
    InputMenu,
    InputString,
    InputFloat,
    InputVector,
)


class AdvectGrid(NodeBuilder):
    """
    Move grid values through a velocity field using numerical integration. Supports multiple integration schemes for different accuracy and performance trade-offs
    """

    _bl_idname = "GeometryNodeGridAdvect"
    node: bpy.types.GeometryNodeGridAdvect

    def __init__(
        self,
        grid: InputFloat = 0.0,
        velocity: InputVector = None,
        time_step: InputFloat = 1.0,
        integration_scheme: InputMenu
        | Literal[
            "Semi-Lagrangian",
            "Midpoint",
            "Runge-Kutta 3",
            "Runge-Kutta 4",
            "MacCormack",
            "BFECC",
        ] = "Runge-Kutta 3",
        limiter: InputMenu | Literal["None", "Clamp", "Revert"] = "Clamp",
        *,
        data_type: Literal["FLOAT", "INT", "VECTOR"] = "FLOAT",
    ):
        super().__init__()
        key_args = {
            "Grid": grid,
            "Velocity": velocity,
            "Time Step": time_step,
            "Integration Scheme": integration_scheme,
            "Limiter": limiter,
        }
        self.data_type = data_type
        self._establish_links(**key_args)

    @classmethod
    def float(
        cls,
        grid: InputFloat = 0.0,
        velocity: InputVector = None,
        time_step: InputFloat = 1.0,
        integration_scheme: InputMenu
        | Literal[
            "Semi-Lagrangian",
            "Midpoint",
            "Runge-Kutta 3",
            "Runge-Kutta 4",
            "MacCormack",
            "BFECC",
        ] = "Runge-Kutta 3",
        limiter: InputMenu | Literal["None", "Clamp", "Revert"] = "Clamp",
    ) -> "AdvectGrid":
        """Create Advect Grid with operation 'Float'."""
        return cls(
            data_type="FLOAT",
            grid=grid,
            velocity=velocity,
            time_step=time_step,
            integration_scheme=integration_scheme,
            limiter=limiter,
        )

    @classmethod
    def integer(
        cls,
        grid: InputInteger = 0,
        velocity: InputVector = None,
        time_step: InputFloat = 1.0,
        integration_scheme: InputMenu
        | Literal[
            "Semi-Lagrangian",
            "Midpoint",
            "Runge-Kutta 3",
            "Runge-Kutta 4",
            "MacCormack",
            "BFECC",
        ] = "Runge-Kutta 3",
        limiter: InputMenu | Literal["None", "Clamp", "Revert"] = "Clamp",
    ) -> "AdvectGrid":
        """Create Advect Grid with operation 'Integer'."""
        return cls(
            data_type="INT",
            grid=grid,
            velocity=velocity,
            time_step=time_step,
            integration_scheme=integration_scheme,
            limiter=limiter,
        )

    @classmethod
    def vector(
        cls,
        grid: InputVector = None,
        velocity: InputVector = None,
        time_step: InputFloat = 1.0,
        integration_scheme: InputMenu
        | Literal[
            "Semi-Lagrangian",
            "Midpoint",
            "Runge-Kutta 3",
            "Runge-Kutta 4",
            "MacCormack",
            "BFECC",
        ] = "Runge-Kutta 3",
        limiter: InputMenu | Literal["None", "Clamp", "Revert"] = "Clamp",
    ) -> "AdvectGrid":
        """Create Advect Grid with operation 'Vector'."""
        return cls(
            data_type="VECTOR",
            grid=grid,
            velocity=velocity,
            time_step=time_step,
            integration_scheme=integration_scheme,
            limiter=limiter,
        )

    @property
    def i_grid(self) -> Socket:
        """Input socket: Grid"""
        return self.inputs.get("Grid")

    @property
    def i_velocity(self) -> Socket:
        """Input socket: Velocity"""
        return self.inputs.get("Velocity")

    @property
    def i_time_step(self) -> Socket:
        """Input socket: Time Step"""
        return self.inputs.get("Time Step")

    @property
    def i_integration_scheme(self) -> Socket:
        """Input socket: Integration Scheme"""
        return self.inputs.get("Integration Scheme")

    @property
    def i_limiter(self) -> Socket:
        """Input socket: Limiter"""
        return self.inputs.get("Limiter")

    @property
    def o_grid(self) -> Socket:
        """Output socket: Grid"""
        return self.outputs.get("Grid")

    @property
    def data_type(self) -> Literal["FLOAT", "INT", "VECTOR"]:
        return self.node.data_type

    @data_type.setter
    def data_type(self, value: Literal["FLOAT", "INT", "VECTOR"]):
        self.node.data_type = value


class DistributePointsInGrid(NodeBuilder):
    """
    Generate points inside a volume grid
    """

    _bl_idname = "GeometryNodeDistributePointsInGrid"
    node: bpy.types.GeometryNodeDistributePointsInGrid

    def __init__(
        self,
        grid: InputFloat = 0.0,
        density: InputFloat = 1.0,
        seed: InputInteger = 0,
        spacing: InputVector = None,
        threshold: InputFloat = 0.1,
        *,
        mode: Literal["DENSITY_RANDOM", "DENSITY_GRID"] = "DENSITY_RANDOM",
    ):
        super().__init__()
        key_args = {
            "Grid": grid,
            "Density": density,
            "Seed": seed,
            "Spacing": spacing,
            "Threshold": threshold,
        }
        self.mode = mode
        self._establish_links(**key_args)

    @property
    def i_grid(self) -> Socket:
        """Input socket: Grid"""
        return self.inputs.get("Grid")

    @property
    def i_density(self) -> Socket:
        """Input socket: Density"""
        return self.inputs.get("Density")

    @property
    def i_seed(self) -> Socket:
        """Input socket: Seed"""
        return self.inputs.get("Seed")

    @property
    def i_spacing(self) -> Socket:
        """Input socket: Spacing"""
        return self.inputs.get("Spacing")

    @property
    def i_threshold(self) -> Socket:
        """Input socket: Threshold"""
        return self.inputs.get("Threshold")

    @property
    def o_points(self) -> Socket:
        """Output socket: Points"""
        return self.outputs.get("Points")

    @property
    def mode(self) -> Literal["DENSITY_RANDOM", "DENSITY_GRID"]:
        return self.node.mode

    @mode.setter
    def mode(self, value: Literal["DENSITY_RANDOM", "DENSITY_GRID"]):
        self.node.mode = value


class DistributePointsInVolume(NodeBuilder):
    """
    Generate points inside a volume
    """

    _bl_idname = "GeometryNodeDistributePointsInVolume"
    node: bpy.types.GeometryNodeDistributePointsInVolume

    def __init__(
        self,
        volume: InputGeometry = None,
        mode: InputMenu | Literal["Random", "Grid"] = "Random",
        density: InputFloat = 1.0,
        seed: InputInteger = 0,
        spacing: InputVector = None,
        threshold: InputFloat = 0.1,
    ):
        super().__init__()
        key_args = {
            "Volume": volume,
            "Mode": mode,
            "Density": density,
            "Seed": seed,
            "Spacing": spacing,
            "Threshold": threshold,
        }

        self._establish_links(**key_args)

    @property
    def i_volume(self) -> Socket:
        """Input socket: Volume"""
        return self.inputs.get("Volume")

    @property
    def i_mode(self) -> Socket:
        """Input socket: Mode"""
        return self.inputs.get("Mode")

    @property
    def i_density(self) -> Socket:
        """Input socket: Density"""
        return self.inputs.get("Density")

    @property
    def i_seed(self) -> Socket:
        """Input socket: Seed"""
        return self.inputs.get("Seed")

    @property
    def i_spacing(self) -> Socket:
        """Input socket: Spacing"""
        return self.inputs.get("Spacing")

    @property
    def i_threshold(self) -> Socket:
        """Input socket: Threshold"""
        return self.inputs.get("Threshold")

    @property
    def o_points(self) -> Socket:
        """Output socket: Points"""
        return self.outputs.get("Points")


class GetNamedGrid(NodeBuilder):
    """
    Get volume grid from a volume geometry with the specified name
    """

    _bl_idname = "GeometryNodeGetNamedGrid"
    node: bpy.types.GeometryNodeGetNamedGrid

    def __init__(
        self,
        volume: InputGeometry = None,
        name: InputString = "",
        remove: InputBoolean = True,
        *,
        data_type: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"] = "FLOAT",
    ):
        super().__init__()
        key_args = {"Volume": volume, "Name": name, "Remove": remove}
        self.data_type = data_type
        self._establish_links(**key_args)

    @classmethod
    def float(
        cls,
        volume: InputGeometry = None,
        name: InputString = "",
        remove: InputBoolean = True,
    ) -> "GetNamedGrid":
        """Create Get Named Grid with operation 'Float'."""
        return cls(data_type="FLOAT", volume=volume, name=name, remove=remove)

    @classmethod
    def integer(
        cls,
        volume: InputGeometry = None,
        name: InputString = "",
        remove: InputBoolean = True,
    ) -> "GetNamedGrid":
        """Create Get Named Grid with operation 'Integer'."""
        return cls(data_type="INT", volume=volume, name=name, remove=remove)

    @classmethod
    def boolean(
        cls,
        volume: InputGeometry = None,
        name: InputString = "",
        remove: InputBoolean = True,
    ) -> "GetNamedGrid":
        """Create Get Named Grid with operation 'Boolean'."""
        return cls(data_type="BOOLEAN", volume=volume, name=name, remove=remove)

    @classmethod
    def vector(
        cls,
        volume: InputGeometry = None,
        name: InputString = "",
        remove: InputBoolean = True,
    ) -> "GetNamedGrid":
        """Create Get Named Grid with operation 'Vector'."""
        return cls(data_type="VECTOR", volume=volume, name=name, remove=remove)

    @property
    def i_volume(self) -> Socket:
        """Input socket: Volume"""
        return self.inputs.get("Volume")

    @property
    def i_name(self) -> Socket:
        """Input socket: Name"""
        return self.inputs.get("Name")

    @property
    def i_remove(self) -> Socket:
        """Input socket: Remove"""
        return self.inputs.get("Remove")

    @property
    def o_volume(self) -> Socket:
        """Output socket: Volume"""
        return self.outputs.get("Volume")

    @property
    def o_grid(self) -> Socket:
        """Output socket: Grid"""
        return self.outputs.get("Grid")

    @property
    def data_type(self) -> Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]:
        return self.node.data_type

    @data_type.setter
    def data_type(self, value: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]):
        self.node.data_type = value


class GridCurl(NodeBuilder):
    """
    Calculate the magnitude and direction of circulation of a directional vector grid
    """

    _bl_idname = "GeometryNodeGridCurl"
    node: bpy.types.GeometryNodeGridCurl

    def __init__(self, grid: InputVector = None):
        super().__init__()
        key_args = {"Grid": grid}

        self._establish_links(**key_args)

    @property
    def i_grid(self) -> Socket:
        """Input socket: Grid"""
        return self.inputs.get("Grid")

    @property
    def o_curl(self) -> VectorSocket:
        """Output socket: Curl"""
        return self.outputs.get("Curl")


class GridDivergence(NodeBuilder):
    """
    Calculate the flow into and out of each point of a directional vector grid
    """

    _bl_idname = "GeometryNodeGridDivergence"
    node: bpy.types.GeometryNodeGridDivergence

    def __init__(self, grid: InputVector = None):
        super().__init__()
        key_args = {"Grid": grid}

        self._establish_links(**key_args)

    @property
    def i_grid(self) -> Socket:
        """Input socket: Grid"""
        return self.inputs.get("Grid")

    @property
    def o_divergence(self) -> Socket:
        """Output socket: Divergence"""
        return self.outputs.get("Divergence")


class GridGradient(NodeBuilder):
    """
    Calculate the direction and magnitude of the change in values of a scalar grid
    """

    _bl_idname = "GeometryNodeGridGradient"
    node: bpy.types.GeometryNodeGridGradient

    def __init__(self, grid: InputFloat = 0.0):
        super().__init__()
        key_args = {"Grid": grid}

        self._establish_links(**key_args)

    @property
    def i_grid(self) -> Socket:
        """Input socket: Grid"""
        return self.inputs.get("Grid")

    @property
    def o_gradient(self) -> VectorSocket:
        """Output socket: Gradient"""
        return self.outputs.get("Gradient")


class GridInfo(NodeBuilder):
    """
    Retrieve information about a volume grid
    """

    _bl_idname = "GeometryNodeGridInfo"
    node: bpy.types.GeometryNodeGridInfo

    def __init__(
        self,
        grid: InputFloat = 0.0,
        *,
        data_type: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"] = "FLOAT",
    ):
        super().__init__()
        key_args = {"Grid": grid}
        self.data_type = data_type
        self._establish_links(**key_args)

    @classmethod
    def float(cls, grid: InputFloat = 0.0) -> "GridInfo":
        """Create Grid Info with operation 'Float'."""
        return cls(data_type="FLOAT", grid=grid)

    @classmethod
    def integer(cls, grid: InputInteger = 0) -> "GridInfo":
        """Create Grid Info with operation 'Integer'."""
        return cls(data_type="INT", grid=grid)

    @classmethod
    def boolean(cls, grid: InputBoolean = False) -> "GridInfo":
        """Create Grid Info with operation 'Boolean'."""
        return cls(data_type="BOOLEAN", grid=grid)

    @classmethod
    def vector(cls, grid: InputVector = None) -> "GridInfo":
        """Create Grid Info with operation 'Vector'."""
        return cls(data_type="VECTOR", grid=grid)

    @property
    def i_grid(self) -> Socket:
        """Input socket: Grid"""
        return self.inputs.get("Grid")

    @property
    def o_transform(self) -> Socket:
        """Output socket: Transform"""
        return self.outputs.get("Transform")

    @property
    def o_background_value(self) -> Socket:
        """Output socket: Background Value"""
        return self.outputs.get("Background Value")

    @property
    def data_type(self) -> Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]:
        return self.node.data_type

    @data_type.setter
    def data_type(self, value: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]):
        self.node.data_type = value


class GridLaplacian(NodeBuilder):
    """
    Compute the divergence of the gradient of the input grid
    """

    _bl_idname = "GeometryNodeGridLaplacian"
    node: bpy.types.GeometryNodeGridLaplacian

    def __init__(self, grid: InputFloat = 0.0):
        super().__init__()
        key_args = {"Grid": grid}

        self._establish_links(**key_args)

    @property
    def i_grid(self) -> Socket:
        """Input socket: Grid"""
        return self.inputs.get("Grid")

    @property
    def o_laplacian(self) -> Socket:
        """Output socket: Laplacian"""
        return self.outputs.get("Laplacian")


class GridToMesh(NodeBuilder):
    """
    Generate a mesh on the "surface" of a volume grid
    """

    _bl_idname = "GeometryNodeGridToMesh"
    node: bpy.types.GeometryNodeGridToMesh

    def __init__(
        self,
        grid: InputFloat = 0.0,
        threshold: InputFloat = 0.1,
        adaptivity: InputFloat = 0.0,
    ):
        super().__init__()
        key_args = {"Grid": grid, "Threshold": threshold, "Adaptivity": adaptivity}

        self._establish_links(**key_args)

    @property
    def i_grid(self) -> Socket:
        """Input socket: Grid"""
        return self.inputs.get("Grid")

    @property
    def i_threshold(self) -> Socket:
        """Input socket: Threshold"""
        return self.inputs.get("Threshold")

    @property
    def i_adaptivity(self) -> Socket:
        """Input socket: Adaptivity"""
        return self.inputs.get("Adaptivity")

    @property
    def o_mesh(self) -> Socket:
        """Output socket: Mesh"""
        return self.outputs.get("Mesh")


class MeshToDensityGrid(NodeBuilder):
    """
    Create a filled volume grid from a mesh
    """

    _bl_idname = "GeometryNodeMeshToDensityGrid"
    node: bpy.types.GeometryNodeMeshToDensityGrid

    def __init__(
        self,
        mesh: InputGeometry = None,
        density: InputFloat = 1.0,
        voxel_size: InputFloat = 0.3,
        gradient_width: InputFloat = 0.2,
    ):
        super().__init__()
        key_args = {
            "Mesh": mesh,
            "Density": density,
            "Voxel Size": voxel_size,
            "Gradient Width": gradient_width,
        }

        self._establish_links(**key_args)

    @property
    def i_mesh(self) -> Socket:
        """Input socket: Mesh"""
        return self.inputs.get("Mesh")

    @property
    def i_density(self) -> Socket:
        """Input socket: Density"""
        return self.inputs.get("Density")

    @property
    def i_voxel_size(self) -> Socket:
        """Input socket: Voxel Size"""
        return self.inputs.get("Voxel Size")

    @property
    def i_gradient_width(self) -> Socket:
        """Input socket: Gradient Width"""
        return self.inputs.get("Gradient Width")

    @property
    def o_density_grid(self) -> Socket:
        """Output socket: Density Grid"""
        return self.outputs.get("Density Grid")


class MeshToSDFGrid(NodeBuilder):
    """
    Create a signed distance volume grid from a mesh
    """

    _bl_idname = "GeometryNodeMeshToSDFGrid"
    node: bpy.types.GeometryNodeMeshToSDFGrid

    def __init__(
        self,
        mesh: InputGeometry = None,
        voxel_size: InputFloat = 0.3,
        band_width: InputInteger = 3,
    ):
        super().__init__()
        key_args = {"Mesh": mesh, "Voxel Size": voxel_size, "Band Width": band_width}

        self._establish_links(**key_args)

    @property
    def i_mesh(self) -> Socket:
        """Input socket: Mesh"""
        return self.inputs.get("Mesh")

    @property
    def i_voxel_size(self) -> Socket:
        """Input socket: Voxel Size"""
        return self.inputs.get("Voxel Size")

    @property
    def i_band_width(self) -> Socket:
        """Input socket: Band Width"""
        return self.inputs.get("Band Width")

    @property
    def o_sdf_grid(self) -> Socket:
        """Output socket: SDF Grid"""
        return self.outputs.get("SDF Grid")


class MeshToVolume(NodeBuilder):
    """
    Create a fog volume with the shape of the input mesh's surface
    """

    _bl_idname = "GeometryNodeMeshToVolume"
    node: bpy.types.GeometryNodeMeshToVolume

    def __init__(
        self,
        mesh: InputGeometry = None,
        density: InputFloat = 1.0,
        resolution_mode: InputMenu | Literal["Amount", "Size"] = "Amount",
        voxel_size: InputFloat = 0.3,
        voxel_amount: InputFloat = 64.0,
        interior_band_width: InputFloat = 0.2,
    ):
        super().__init__()
        key_args = {
            "Mesh": mesh,
            "Density": density,
            "Resolution Mode": resolution_mode,
            "Voxel Size": voxel_size,
            "Voxel Amount": voxel_amount,
            "Interior Band Width": interior_band_width,
        }

        self._establish_links(**key_args)

    @property
    def i_mesh(self) -> Socket:
        """Input socket: Mesh"""
        return self.inputs.get("Mesh")

    @property
    def i_density(self) -> Socket:
        """Input socket: Density"""
        return self.inputs.get("Density")

    @property
    def i_resolution_mode(self) -> Socket:
        """Input socket: Resolution Mode"""
        return self.inputs.get("Resolution Mode")

    @property
    def i_voxel_size(self) -> Socket:
        """Input socket: Voxel Size"""
        return self.inputs.get("Voxel Size")

    @property
    def i_voxel_amount(self) -> Socket:
        """Input socket: Voxel Amount"""
        return self.inputs.get("Voxel Amount")

    @property
    def i_interior_band_width(self) -> Socket:
        """Input socket: Interior Band Width"""
        return self.inputs.get("Interior Band Width")

    @property
    def o_volume(self) -> Socket:
        """Output socket: Volume"""
        return self.outputs.get("Volume")


class PointsToSDFGrid(NodeBuilder):
    """
    Create a signed distance volume grid from points
    """

    _bl_idname = "GeometryNodePointsToSDFGrid"
    node: bpy.types.GeometryNodePointsToSDFGrid

    def __init__(
        self,
        points: InputGeometry = None,
        radius: InputFloat = 0.5,
        voxel_size: InputFloat = 0.3,
    ):
        super().__init__()
        key_args = {"Points": points, "Radius": radius, "Voxel Size": voxel_size}

        self._establish_links(**key_args)

    @property
    def i_points(self) -> Socket:
        """Input socket: Points"""
        return self.inputs.get("Points")

    @property
    def i_radius(self) -> Socket:
        """Input socket: Radius"""
        return self.inputs.get("Radius")

    @property
    def i_voxel_size(self) -> Socket:
        """Input socket: Voxel Size"""
        return self.inputs.get("Voxel Size")

    @property
    def o_sdf_grid(self) -> Socket:
        """Output socket: SDF Grid"""
        return self.outputs.get("SDF Grid")


class PointsToVolume(NodeBuilder):
    """
    Generate a fog volume sphere around every point
    """

    _bl_idname = "GeometryNodePointsToVolume"
    node: bpy.types.GeometryNodePointsToVolume

    def __init__(
        self,
        points: InputGeometry = None,
        density: InputFloat = 1.0,
        resolution_mode: InputMenu | Literal["Amount", "Size"] = "Amount",
        voxel_size: InputFloat = 0.3,
        voxel_amount: InputFloat = 64.0,
        radius: InputFloat = 0.5,
    ):
        super().__init__()
        key_args = {
            "Points": points,
            "Density": density,
            "Resolution Mode": resolution_mode,
            "Voxel Size": voxel_size,
            "Voxel Amount": voxel_amount,
            "Radius": radius,
        }

        self._establish_links(**key_args)

    @property
    def i_points(self) -> Socket:
        """Input socket: Points"""
        return self.inputs.get("Points")

    @property
    def i_density(self) -> Socket:
        """Input socket: Density"""
        return self.inputs.get("Density")

    @property
    def i_resolution_mode(self) -> Socket:
        """Input socket: Resolution Mode"""
        return self.inputs.get("Resolution Mode")

    @property
    def i_voxel_size(self) -> Socket:
        """Input socket: Voxel Size"""
        return self.inputs.get("Voxel Size")

    @property
    def i_voxel_amount(self) -> Socket:
        """Input socket: Voxel Amount"""
        return self.inputs.get("Voxel Amount")

    @property
    def i_radius(self) -> Socket:
        """Input socket: Radius"""
        return self.inputs.get("Radius")

    @property
    def o_volume(self) -> Socket:
        """Output socket: Volume"""
        return self.outputs.get("Volume")


class PruneGrid(NodeBuilder):
    """
    Make the storage of a volume grid more efficient by collapsing data into tiles or inner nodes
    """

    _bl_idname = "GeometryNodeGridPrune"
    node: bpy.types.GeometryNodeGridPrune

    def __init__(
        self,
        grid: InputFloat = 0.0,
        mode: InputMenu | Literal["Inactive", "Threshold", "SDF"] = "Threshold",
        threshold: InputFloat = 0.01,
        *,
        data_type: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"] = "FLOAT",
    ):
        super().__init__()
        key_args = {"Grid": grid, "Mode": mode, "Threshold": threshold}
        self.data_type = data_type
        self._establish_links(**key_args)

    @classmethod
    def float(
        cls,
        grid: InputFloat = 0.0,
        mode: InputMenu | Literal["Inactive", "Threshold", "SDF"] = "Threshold",
        threshold: InputFloat = 0.01,
    ) -> "PruneGrid":
        """Create Prune Grid with operation 'Float'."""
        return cls(data_type="FLOAT", grid=grid, mode=mode, threshold=threshold)

    @classmethod
    def integer(
        cls,
        grid: InputInteger = 0,
        mode: InputMenu | Literal["Inactive", "Threshold", "SDF"] = "Threshold",
        threshold: InputInteger = 0,
    ) -> "PruneGrid":
        """Create Prune Grid with operation 'Integer'."""
        return cls(data_type="INT", grid=grid, mode=mode, threshold=threshold)

    @classmethod
    def boolean(
        cls,
        grid: InputBoolean = False,
        mode: InputMenu | Literal["Inactive", "Threshold", "SDF"] = "Threshold",
    ) -> "PruneGrid":
        """Create Prune Grid with operation 'Boolean'."""
        return cls(data_type="BOOLEAN", grid=grid, mode=mode)

    @classmethod
    def vector(
        cls,
        grid: InputVector = None,
        mode: InputMenu | Literal["Inactive", "Threshold", "SDF"] = "Threshold",
        threshold: InputVector = None,
    ) -> "PruneGrid":
        """Create Prune Grid with operation 'Vector'."""
        return cls(data_type="VECTOR", grid=grid, mode=mode, threshold=threshold)

    @property
    def i_grid(self) -> Socket:
        """Input socket: Grid"""
        return self.inputs.get("Grid")

    @property
    def i_mode(self) -> Socket:
        """Input socket: Mode"""
        return self.inputs.get("Mode")

    @property
    def i_threshold(self) -> Socket:
        """Input socket: Threshold"""
        return self.inputs.get("Threshold")

    @property
    def o_grid(self) -> Socket:
        """Output socket: Grid"""
        return self.outputs.get("Grid")

    @property
    def data_type(self) -> Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]:
        return self.node.data_type

    @data_type.setter
    def data_type(self, value: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]):
        self.node.data_type = value


class SDFGridFillet(NodeBuilder):
    """
    Round off concave internal corners in a signed distance field. Only affects areas with negative principal curvature, creating smoother transitions between surfaces
    """

    _bl_idname = "GeometryNodeSDFGridFillet"
    node: bpy.types.GeometryNodeSDFGridFillet

    def __init__(
        self,
        grid: InputFloat = 0.0,
        iterations: InputInteger = 1,
    ):
        super().__init__()
        key_args = {"Grid": grid, "Iterations": iterations}

        self._establish_links(**key_args)

    @property
    def i_grid(self) -> Socket:
        """Input socket: Grid"""
        return self.inputs.get("Grid")

    @property
    def i_iterations(self) -> Socket:
        """Input socket: Iterations"""
        return self.inputs.get("Iterations")

    @property
    def o_grid(self) -> Socket:
        """Output socket: Grid"""
        return self.outputs.get("Grid")


class SDFGridLaplacian(NodeBuilder):
    """
    Apply Laplacian flow smoothing to a signed distance field. Computationally efficient alternative to mean curvature flow, ideal when combined with SDF normalization
    """

    _bl_idname = "GeometryNodeSDFGridLaplacian"
    node: bpy.types.GeometryNodeSDFGridLaplacian

    def __init__(
        self,
        grid: InputFloat = 0.0,
        iterations: InputInteger = 1,
    ):
        super().__init__()
        key_args = {"Grid": grid, "Iterations": iterations}

        self._establish_links(**key_args)

    @property
    def i_grid(self) -> Socket:
        """Input socket: Grid"""
        return self.inputs.get("Grid")

    @property
    def i_iterations(self) -> Socket:
        """Input socket: Iterations"""
        return self.inputs.get("Iterations")

    @property
    def o_grid(self) -> Socket:
        """Output socket: Grid"""
        return self.outputs.get("Grid")


class SDFGridMean(NodeBuilder):
    """
    Apply mean (box) filter smoothing to a signed distance field. Fast separable averaging filter for general smoothing of the distance field
    """

    _bl_idname = "GeometryNodeSDFGridMean"
    node: bpy.types.GeometryNodeSDFGridMean

    def __init__(
        self,
        grid: InputFloat = 0.0,
        width: InputInteger = 1,
        iterations: InputInteger = 1,
    ):
        super().__init__()
        key_args = {"Grid": grid, "Width": width, "Iterations": iterations}

        self._establish_links(**key_args)

    @property
    def i_grid(self) -> Socket:
        """Input socket: Grid"""
        return self.inputs.get("Grid")

    @property
    def i_width(self) -> Socket:
        """Input socket: Width"""
        return self.inputs.get("Width")

    @property
    def i_iterations(self) -> Socket:
        """Input socket: Iterations"""
        return self.inputs.get("Iterations")

    @property
    def o_grid(self) -> Socket:
        """Output socket: Grid"""
        return self.outputs.get("Grid")


class SDFGridMeanCurvature(NodeBuilder):
    """
    Apply mean curvature flow smoothing to a signed distance field. Evolves the surface based on its mean curvature, naturally smoothing high-curvature regions more than flat areas
    """

    _bl_idname = "GeometryNodeSDFGridMeanCurvature"
    node: bpy.types.GeometryNodeSDFGridMeanCurvature

    def __init__(
        self,
        grid: InputFloat = 0.0,
        iterations: InputInteger = 1,
    ):
        super().__init__()
        key_args = {"Grid": grid, "Iterations": iterations}

        self._establish_links(**key_args)

    @property
    def i_grid(self) -> Socket:
        """Input socket: Grid"""
        return self.inputs.get("Grid")

    @property
    def i_iterations(self) -> Socket:
        """Input socket: Iterations"""
        return self.inputs.get("Iterations")

    @property
    def o_grid(self) -> Socket:
        """Output socket: Grid"""
        return self.outputs.get("Grid")


class SDFGridMedian(NodeBuilder):
    """
    Apply median filter to a signed distance field. Reduces noise while preserving sharp features and edges in the distance field
    """

    _bl_idname = "GeometryNodeSDFGridMedian"
    node: bpy.types.GeometryNodeSDFGridMedian

    def __init__(
        self,
        grid: InputFloat = 0.0,
        width: InputInteger = 1,
        iterations: InputInteger = 1,
    ):
        super().__init__()
        key_args = {"Grid": grid, "Width": width, "Iterations": iterations}

        self._establish_links(**key_args)

    @property
    def i_grid(self) -> Socket:
        """Input socket: Grid"""
        return self.inputs.get("Grid")

    @property
    def i_width(self) -> Socket:
        """Input socket: Width"""
        return self.inputs.get("Width")

    @property
    def i_iterations(self) -> Socket:
        """Input socket: Iterations"""
        return self.inputs.get("Iterations")

    @property
    def o_grid(self) -> Socket:
        """Output socket: Grid"""
        return self.outputs.get("Grid")


class SDFGridOffset(NodeBuilder):
    """
    Offset a signed distance field surface by a world-space distance. Dilates (positive) or erodes (negative) while maintaining the signed distance property
    """

    _bl_idname = "GeometryNodeSDFGridOffset"
    node: bpy.types.GeometryNodeSDFGridOffset

    def __init__(
        self,
        grid: InputFloat = 0.0,
        distance: InputFloat = 0.1,
    ):
        super().__init__()
        key_args = {"Grid": grid, "Distance": distance}

        self._establish_links(**key_args)

    @property
    def i_grid(self) -> Socket:
        """Input socket: Grid"""
        return self.inputs.get("Grid")

    @property
    def i_distance(self) -> Socket:
        """Input socket: Distance"""
        return self.inputs.get("Distance")

    @property
    def o_grid(self) -> Socket:
        """Output socket: Grid"""
        return self.outputs.get("Grid")


class SampleGrid(NodeBuilder):
    """
    Retrieve values from the specified volume grid
    """

    _bl_idname = "GeometryNodeSampleGrid"
    node: bpy.types.GeometryNodeSampleGrid

    def __init__(
        self,
        grid: InputFloat = 0.0,
        position: InputVector = None,
        interpolation: InputMenu
        | Literal["Nearest Neighbor", "Trilinear", "Triquadratic"] = "Trilinear",
        *,
        data_type: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"] = "FLOAT",
    ):
        super().__init__()
        key_args = {"Grid": grid, "Position": position, "Interpolation": interpolation}
        self.data_type = data_type
        self._establish_links(**key_args)

    @classmethod
    def float(
        cls,
        grid: InputFloat = 0.0,
        position: InputVector = None,
        interpolation: InputMenu
        | Literal["Nearest Neighbor", "Trilinear", "Triquadratic"] = "Trilinear",
    ) -> "SampleGrid":
        """Create Sample Grid with operation 'Float'."""
        return cls(
            data_type="FLOAT", grid=grid, position=position, interpolation=interpolation
        )

    @classmethod
    def integer(
        cls,
        grid: InputInteger = 0,
        position: InputVector = None,
        interpolation: InputMenu
        | Literal["Nearest Neighbor", "Trilinear", "Triquadratic"] = "Trilinear",
    ) -> "SampleGrid":
        """Create Sample Grid with operation 'Integer'."""
        return cls(
            data_type="INT", grid=grid, position=position, interpolation=interpolation
        )

    @classmethod
    def boolean(
        cls,
        grid: InputBoolean = False,
        position: InputVector = None,
        interpolation: InputMenu
        | Literal["Nearest Neighbor", "Trilinear", "Triquadratic"] = "Trilinear",
    ) -> "SampleGrid":
        """Create Sample Grid with operation 'Boolean'."""
        return cls(
            data_type="BOOLEAN",
            grid=grid,
            position=position,
            interpolation=interpolation,
        )

    @classmethod
    def vector(
        cls,
        grid: InputVector = None,
        position: InputVector = None,
        interpolation: InputMenu
        | Literal["Nearest Neighbor", "Trilinear", "Triquadratic"] = "Trilinear",
    ) -> "SampleGrid":
        """Create Sample Grid with operation 'Vector'."""
        return cls(
            data_type="VECTOR",
            grid=grid,
            position=position,
            interpolation=interpolation,
        )

    @property
    def i_grid(self) -> Socket:
        """Input socket: Grid"""
        return self.inputs.get("Grid")

    @property
    def i_position(self) -> Socket:
        """Input socket: Position"""
        return self.inputs.get("Position")

    @property
    def i_interpolation(self) -> Socket:
        """Input socket: Interpolation"""
        return self.inputs.get("Interpolation")

    @property
    def o_value(self) -> Socket:
        """Output socket: Value"""
        return self.outputs.get("Value")

    @property
    def data_type(self) -> Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]:
        return self.node.data_type

    @data_type.setter
    def data_type(self, value: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]):
        self.node.data_type = value


class SampleGridIndex(NodeBuilder):
    """
    Retrieve volume grid values at specific voxels
    """

    _bl_idname = "GeometryNodeSampleGridIndex"
    node: bpy.types.GeometryNodeSampleGridIndex

    def __init__(
        self,
        grid: InputFloat = 0.0,
        x: InputInteger = 0,
        y: InputInteger = 0,
        z: InputInteger = 0,
        *,
        data_type: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"] = "FLOAT",
    ):
        super().__init__()
        key_args = {"Grid": grid, "X": x, "Y": y, "Z": z}
        self.data_type = data_type
        self._establish_links(**key_args)

    @classmethod
    def float(
        cls,
        grid: InputFloat = 0.0,
        x: InputInteger = 0,
        y: InputInteger = 0,
        z: InputInteger = 0,
    ) -> "SampleGridIndex":
        """Create Sample Grid Index with operation 'Float'."""
        return cls(data_type="FLOAT", grid=grid, x=x, y=y, z=z)

    @classmethod
    def integer(
        cls,
        grid: InputInteger = 0,
        x: InputInteger = 0,
        y: InputInteger = 0,
        z: InputInteger = 0,
    ) -> "SampleGridIndex":
        """Create Sample Grid Index with operation 'Integer'."""
        return cls(data_type="INT", grid=grid, x=x, y=y, z=z)

    @classmethod
    def boolean(
        cls,
        grid: InputBoolean = False,
        x: InputInteger = 0,
        y: InputInteger = 0,
        z: InputInteger = 0,
    ) -> "SampleGridIndex":
        """Create Sample Grid Index with operation 'Boolean'."""
        return cls(data_type="BOOLEAN", grid=grid, x=x, y=y, z=z)

    @classmethod
    def vector(
        cls,
        grid: InputVector = None,
        x: InputInteger = 0,
        y: InputInteger = 0,
        z: InputInteger = 0,
    ) -> "SampleGridIndex":
        """Create Sample Grid Index with operation 'Vector'."""
        return cls(data_type="VECTOR", grid=grid, x=x, y=y, z=z)

    @property
    def i_grid(self) -> Socket:
        """Input socket: Grid"""
        return self.inputs.get("Grid")

    @property
    def i_x(self) -> Socket:
        """Input socket: X"""
        return self.inputs.get("X")

    @property
    def i_y(self) -> Socket:
        """Input socket: Y"""
        return self.inputs.get("Y")

    @property
    def i_z(self) -> Socket:
        """Input socket: Z"""
        return self.inputs.get("Z")

    @property
    def o_value(self) -> Socket:
        """Output socket: Value"""
        return self.outputs.get("Value")

    @property
    def data_type(self) -> Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]:
        return self.node.data_type

    @data_type.setter
    def data_type(self, value: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]):
        self.node.data_type = value


class SetGridBackground(NodeBuilder):
    """
    Set the background value used for inactive voxels and tiles
    """

    _bl_idname = "GeometryNodeSetGridBackground"
    node: bpy.types.GeometryNodeSetGridBackground

    def __init__(
        self,
        grid: InputFloat = 0.0,
        background: InputFloat = 0.0,
        *,
        data_type: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"] = "FLOAT",
    ):
        super().__init__()
        key_args = {"Grid": grid, "Background": background}
        self.data_type = data_type
        self._establish_links(**key_args)

    @classmethod
    def float(
        cls, grid: InputFloat = 0.0, background: InputFloat = 0.0
    ) -> "SetGridBackground":
        """Create Set Grid Background with operation 'Float'."""
        return cls(data_type="FLOAT", grid=grid, background=background)

    @classmethod
    def integer(
        cls, grid: InputInteger = 0, background: InputInteger = 0
    ) -> "SetGridBackground":
        """Create Set Grid Background with operation 'Integer'."""
        return cls(data_type="INT", grid=grid, background=background)

    @classmethod
    def boolean(
        cls, grid: InputBoolean = False, background: InputBoolean = False
    ) -> "SetGridBackground":
        """Create Set Grid Background with operation 'Boolean'."""
        return cls(data_type="BOOLEAN", grid=grid, background=background)

    @classmethod
    def vector(
        cls, grid: InputVector = None, background: InputVector = None
    ) -> "SetGridBackground":
        """Create Set Grid Background with operation 'Vector'."""
        return cls(data_type="VECTOR", grid=grid, background=background)

    @property
    def i_grid(self) -> Socket:
        """Input socket: Grid"""
        return self.inputs.get("Grid")

    @property
    def i_background(self) -> Socket:
        """Input socket: Background"""
        return self.inputs.get("Background")

    @property
    def o_grid(self) -> Socket:
        """Output socket: Grid"""
        return self.outputs.get("Grid")

    @property
    def data_type(self) -> Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]:
        return self.node.data_type

    @data_type.setter
    def data_type(self, value: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]):
        self.node.data_type = value


class SetGridTransform(NodeBuilder):
    """
    Set the transform for the grid from index space into object space.
    """

    _bl_idname = "GeometryNodeSetGridTransform"
    node: bpy.types.GeometryNodeSetGridTransform

    def __init__(
        self,
        grid: InputFloat = 0.0,
        transform: InputMatrix = None,
        *,
        data_type: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"] = "FLOAT",
    ):
        super().__init__()
        key_args = {"Grid": grid, "Transform": transform}
        self.data_type = data_type
        self._establish_links(**key_args)

    @classmethod
    def float(
        cls, grid: InputFloat = 0.0, transform: InputMatrix = None
    ) -> "SetGridTransform":
        """Create Set Grid Transform with operation 'Float'."""
        return cls(data_type="FLOAT", grid=grid, transform=transform)

    @classmethod
    def integer(
        cls, grid: InputInteger = 0, transform: InputMatrix = None
    ) -> "SetGridTransform":
        """Create Set Grid Transform with operation 'Integer'."""
        return cls(data_type="INT", grid=grid, transform=transform)

    @classmethod
    def boolean(
        cls, grid: InputBoolean = False, transform: InputMatrix = None
    ) -> "SetGridTransform":
        """Create Set Grid Transform with operation 'Boolean'."""
        return cls(data_type="BOOLEAN", grid=grid, transform=transform)

    @classmethod
    def vector(
        cls, grid: InputVector = None, transform: InputMatrix = None
    ) -> "SetGridTransform":
        """Create Set Grid Transform with operation 'Vector'."""
        return cls(data_type="VECTOR", grid=grid, transform=transform)

    @property
    def i_grid(self) -> Socket:
        """Input socket: Grid"""
        return self.inputs.get("Grid")

    @property
    def i_transform(self) -> Socket:
        """Input socket: Transform"""
        return self.inputs.get("Transform")

    @property
    def o_is_valid(self) -> Socket:
        """Output socket: Is Valid"""
        return self.outputs.get("Is Valid")

    @property
    def o_grid(self) -> Socket:
        """Output socket: Grid"""
        return self.outputs.get("Grid")

    @property
    def data_type(self) -> Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]:
        return self.node.data_type

    @data_type.setter
    def data_type(self, value: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]):
        self.node.data_type = value


class StoreNamedGrid(NodeBuilder):
    """
    Store grid data in a volume geometry with the specified name
    """

    _bl_idname = "GeometryNodeStoreNamedGrid"
    node: bpy.types.GeometryNodeStoreNamedGrid

    def __init__(
        self,
        volume: InputGeometry = None,
        name: InputString = "",
        grid: InputFloat = 0.0,
        *,
        data_type: Literal["BOOLEAN", "FLOAT", "INT", "VECTOR_FLOAT"] = "FLOAT",
    ):
        super().__init__()
        key_args = {"Volume": volume, "Name": name, "Grid": grid}
        self.data_type = data_type
        self._establish_links(**key_args)

    @classmethod
    def boolean(
        cls,
        volume: InputGeometry = None,
        name: InputString = "",
        grid: InputBoolean = False,
    ) -> "StoreNamedGrid":
        """Create Store Named Grid with operation 'Boolean'."""
        return cls(data_type="BOOLEAN", volume=volume, name=name, grid=grid)

    @classmethod
    def float(
        cls,
        volume: InputGeometry = None,
        name: InputString = "",
        grid: InputFloat = 0.0,
    ) -> "StoreNamedGrid":
        """Create Store Named Grid with operation 'Float'."""
        return cls(data_type="FLOAT", volume=volume, name=name, grid=grid)

    @classmethod
    def integer(
        cls,
        volume: InputGeometry = None,
        name: InputString = "",
        grid: InputInteger = 0,
    ) -> "StoreNamedGrid":
        """Create Store Named Grid with operation 'Integer'."""
        return cls(data_type="INT", volume=volume, name=name, grid=grid)

    @classmethod
    def vector(
        cls,
        volume: InputGeometry = None,
        name: InputString = "",
        grid: InputVector = None,
    ) -> "StoreNamedGrid":
        """Create Store Named Grid with operation 'Vector'."""
        return cls(data_type="VECTOR_FLOAT", volume=volume, name=name, grid=grid)

    @property
    def i_volume(self) -> Socket:
        """Input socket: Volume"""
        return self.inputs.get("Volume")

    @property
    def i_name(self) -> Socket:
        """Input socket: Name"""
        return self.inputs.get("Name")

    @property
    def i_grid(self) -> Socket:
        """Input socket: Grid"""
        return self.inputs.get("Grid")

    @property
    def o_volume(self) -> Socket:
        """Output socket: Volume"""
        return self.outputs.get("Volume")

    @property
    def data_type(self) -> Literal["BOOLEAN", "FLOAT", "INT", "VECTOR_FLOAT"]:
        return self.node.data_type

    @data_type.setter
    def data_type(self, value: Literal["BOOLEAN", "FLOAT", "INT", "VECTOR_FLOAT"]):
        self.node.data_type = value


class VolumeCube(NodeBuilder):
    """
    Generate a dense volume with a field that controls the density at each grid voxel based on its position
    """

    _bl_idname = "GeometryNodeVolumeCube"
    node: bpy.types.GeometryNodeVolumeCube

    def __init__(
        self,
        density: InputFloat = 1.0,
        background: InputFloat = 0.0,
        min: InputVector = None,
        max: InputVector = None,
        resolution_x: InputInteger = 32,
        resolution_y: InputInteger = 32,
        resolution_z: InputInteger = 32,
    ):
        super().__init__()
        key_args = {
            "Density": density,
            "Background": background,
            "Min": min,
            "Max": max,
            "Resolution X": resolution_x,
            "Resolution Y": resolution_y,
            "Resolution Z": resolution_z,
        }

        self._establish_links(**key_args)

    @property
    def i_density(self) -> Socket:
        """Input socket: Density"""
        return self.inputs.get("Density")

    @property
    def i_background(self) -> Socket:
        """Input socket: Background"""
        return self.inputs.get("Background")

    @property
    def i_min(self) -> Socket:
        """Input socket: Min"""
        return self.inputs.get("Min")

    @property
    def i_max(self) -> Socket:
        """Input socket: Max"""
        return self.inputs.get("Max")

    @property
    def i_resolution_x(self) -> Socket:
        """Input socket: Resolution X"""
        return self.inputs.get("Resolution X")

    @property
    def i_resolution_y(self) -> Socket:
        """Input socket: Resolution Y"""
        return self.inputs.get("Resolution Y")

    @property
    def i_resolution_z(self) -> Socket:
        """Input socket: Resolution Z"""
        return self.inputs.get("Resolution Z")

    @property
    def o_volume(self) -> Socket:
        """Output socket: Volume"""
        return self.outputs.get("Volume")


class VolumeToMesh(NodeBuilder):
    """
    Generate a mesh on the "surface" of a volume
    """

    _bl_idname = "GeometryNodeVolumeToMesh"
    node: bpy.types.GeometryNodeVolumeToMesh

    def __init__(
        self,
        volume: InputGeometry = None,
        resolution_mode: InputMenu | Literal["Grid", "Amount", "Size"] = "Grid",
        voxel_size: InputFloat = 0.3,
        voxel_amount: InputFloat = 64.0,
        threshold: InputFloat = 0.1,
        adaptivity: InputFloat = 0.0,
    ):
        super().__init__()
        key_args = {
            "Volume": volume,
            "Resolution Mode": resolution_mode,
            "Voxel Size": voxel_size,
            "Voxel Amount": voxel_amount,
            "Threshold": threshold,
            "Adaptivity": adaptivity,
        }

        self._establish_links(**key_args)

    @property
    def i_volume(self) -> Socket:
        """Input socket: Volume"""
        return self.inputs.get("Volume")

    @property
    def i_resolution_mode(self) -> Socket:
        """Input socket: Resolution Mode"""
        return self.inputs.get("Resolution Mode")

    @property
    def i_voxel_size(self) -> Socket:
        """Input socket: Voxel Size"""
        return self.inputs.get("Voxel Size")

    @property
    def i_voxel_amount(self) -> Socket:
        """Input socket: Voxel Amount"""
        return self.inputs.get("Voxel Amount")

    @property
    def i_threshold(self) -> Socket:
        """Input socket: Threshold"""
        return self.inputs.get("Threshold")

    @property
    def i_adaptivity(self) -> Socket:
        """Input socket: Adaptivity"""
        return self.inputs.get("Adaptivity")

    @property
    def o_mesh(self) -> Socket:
        """Output socket: Mesh"""
        return self.outputs.get("Mesh")


class VoxelizeGrid(NodeBuilder):
    """
    Remove sparseness from a volume grid by making the active tiles into voxels
    """

    _bl_idname = "GeometryNodeGridVoxelize"
    node: bpy.types.GeometryNodeGridVoxelize

    def __init__(
        self,
        grid: InputFloat = 0.0,
        *,
        data_type: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"] = "FLOAT",
    ):
        super().__init__()
        key_args = {"Grid": grid}
        self.data_type = data_type
        self._establish_links(**key_args)

    @classmethod
    def float(cls, grid: InputFloat = 0.0) -> "VoxelizeGrid":
        """Create Voxelize Grid with operation 'Float'."""
        return cls(data_type="FLOAT", grid=grid)

    @classmethod
    def integer(cls, grid: InputInteger = 0) -> "VoxelizeGrid":
        """Create Voxelize Grid with operation 'Integer'."""
        return cls(data_type="INT", grid=grid)

    @classmethod
    def boolean(cls, grid: InputBoolean = False) -> "VoxelizeGrid":
        """Create Voxelize Grid with operation 'Boolean'."""
        return cls(data_type="BOOLEAN", grid=grid)

    @classmethod
    def vector(cls, grid: InputVector = None) -> "VoxelizeGrid":
        """Create Voxelize Grid with operation 'Vector'."""
        return cls(data_type="VECTOR", grid=grid)

    @property
    def i_grid(self) -> Socket:
        """Input socket: Grid"""
        return self.inputs.get("Grid")

    @property
    def o_grid(self) -> Socket:
        """Output socket: Grid"""
        return self.outputs.get("Grid")

    @property
    def data_type(self) -> Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]:
        return self.node.data_type

    @data_type.setter
    def data_type(self, value: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]):
        self.node.data_type = value
