# Auto-generated by generate.py — do not edit manually.

from typing import Literal

import bpy

from ...builder import (
    NodeBuilder,
    SocketLinker,
    TypedInputs,
    TypedOutputs,
    BooleanSocketLinker,
    GeometrySocketLinker,
    MatrixSocketLinker,
    VectorSocketLinker,
)

from ...types import (
    InputBoolean,
    InputGeometry,
    InputInteger,
    InputMatrix,
    InputMenu,
    InputString,
    InputFloat,
    InputVector,
)


class AdvectGrid(NodeBuilder):
    """
    Move grid values through a velocity field using numerical integration. Supports multiple integration schemes for different accuracy and performance trade-offs
    """

    _bl_idname = "GeometryNodeGridAdvect"
    node: bpy.types.GeometryNodeGridAdvect

    def __init__(
        self,
        grid: InputFloat = 0.0,
        velocity: InputVector = None,
        time_step: InputFloat = 1.0,
        integration_scheme: InputMenu
        | Literal[
            "Semi-Lagrangian",
            "Midpoint",
            "Runge-Kutta 3",
            "Runge-Kutta 4",
            "MacCormack",
            "BFECC",
        ] = "Runge-Kutta 3",
        limiter: InputMenu | Literal["None", "Clamp", "Revert"] = "Clamp",
        *,
        data_type: Literal["FLOAT", "INT", "VECTOR"] = "FLOAT",
    ):
        super().__init__()
        key_args = {
            "Grid": grid,
            "Velocity": velocity,
            "Time Step": time_step,
            "Integration Scheme": integration_scheme,
            "Limiter": limiter,
        }
        self.data_type = data_type
        self._establish_links(**key_args)

    @classmethod
    def float(
        cls,
        grid: InputFloat = 0.0,
        velocity: InputVector = None,
        time_step: InputFloat = 1.0,
        integration_scheme: InputMenu
        | Literal[
            "Semi-Lagrangian",
            "Midpoint",
            "Runge-Kutta 3",
            "Runge-Kutta 4",
            "MacCormack",
            "BFECC",
        ] = "Runge-Kutta 3",
        limiter: InputMenu | Literal["None", "Clamp", "Revert"] = "Clamp",
    ) -> "AdvectGrid":
        """Create Advect Grid with operation 'Float'."""
        return cls(
            data_type="FLOAT",
            grid=grid,
            velocity=velocity,
            time_step=time_step,
            integration_scheme=integration_scheme,
            limiter=limiter,
        )

    @classmethod
    def integer(
        cls,
        grid: InputInteger = 0,
        velocity: InputVector = None,
        time_step: InputFloat = 1.0,
        integration_scheme: InputMenu
        | Literal[
            "Semi-Lagrangian",
            "Midpoint",
            "Runge-Kutta 3",
            "Runge-Kutta 4",
            "MacCormack",
            "BFECC",
        ] = "Runge-Kutta 3",
        limiter: InputMenu | Literal["None", "Clamp", "Revert"] = "Clamp",
    ) -> "AdvectGrid":
        """Create Advect Grid with operation 'Integer'."""
        return cls(
            data_type="INT",
            grid=grid,
            velocity=velocity,
            time_step=time_step,
            integration_scheme=integration_scheme,
            limiter=limiter,
        )

    @classmethod
    def vector(
        cls,
        grid: InputVector = None,
        velocity: InputVector = None,
        time_step: InputFloat = 1.0,
        integration_scheme: InputMenu
        | Literal[
            "Semi-Lagrangian",
            "Midpoint",
            "Runge-Kutta 3",
            "Runge-Kutta 4",
            "MacCormack",
            "BFECC",
        ] = "Runge-Kutta 3",
        limiter: InputMenu | Literal["None", "Clamp", "Revert"] = "Clamp",
    ) -> "AdvectGrid":
        """Create Advect Grid with operation 'Vector'."""
        return cls(
            data_type="VECTOR",
            grid=grid,
            velocity=velocity,
            time_step=time_step,
            integration_scheme=integration_scheme,
            limiter=limiter,
        )

    class Inputs(TypedInputs):
        @property
        def grid(self) -> SocketLinker:
            """Input socket: Grid"""
            return self.get("Grid")

        @property
        def velocity(self) -> SocketLinker:
            """Input socket: Velocity"""
            return self.get("Velocity")

        @property
        def time_step(self) -> SocketLinker:
            """Input socket: Time Step"""
            return self.get("Time Step")

        @property
        def integration_scheme(self) -> SocketLinker:
            """Input socket: Integration Scheme"""
            return self.get("Integration Scheme")

        @property
        def limiter(self) -> SocketLinker:
            """Input socket: Limiter"""
            return self.get("Limiter")

    @property
    def i(self) -> "Inputs":
        return AdvectGrid.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def grid(self) -> SocketLinker:
            """Output socket: Grid"""
            return self.get("Grid")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return AdvectGrid.Outputs(self)

    @property
    def data_type(self) -> Literal["FLOAT", "INT", "VECTOR"]:
        return self.node.data_type

    @data_type.setter
    def data_type(self, value: Literal["FLOAT", "INT", "VECTOR"]):
        self.node.data_type = value


class DistributePointsInGrid(NodeBuilder):
    """
    Generate points inside a volume grid
    """

    _bl_idname = "GeometryNodeDistributePointsInGrid"
    node: bpy.types.GeometryNodeDistributePointsInGrid

    def __init__(
        self,
        grid: InputFloat = 0.0,
        density: InputFloat = 1.0,
        seed: InputInteger = 0,
        spacing: InputVector = None,
        threshold: InputFloat = 0.1,
        *,
        mode: Literal["DENSITY_RANDOM", "DENSITY_GRID"] = "DENSITY_RANDOM",
    ):
        super().__init__()
        key_args = {
            "Grid": grid,
            "Density": density,
            "Seed": seed,
            "Spacing": spacing,
            "Threshold": threshold,
        }
        self.mode = mode
        self._establish_links(**key_args)

    class Inputs(TypedInputs):
        @property
        def grid(self) -> SocketLinker:
            """Input socket: Grid"""
            return self.get("Grid")

        @property
        def density(self) -> SocketLinker:
            """Input socket: Density"""
            return self.get("Density")

        @property
        def seed(self) -> SocketLinker:
            """Input socket: Seed"""
            return self.get("Seed")

        @property
        def spacing(self) -> SocketLinker:
            """Input socket: Spacing"""
            return self.get("Spacing")

        @property
        def threshold(self) -> SocketLinker:
            """Input socket: Threshold"""
            return self.get("Threshold")

    @property
    def i(self) -> "Inputs":
        return DistributePointsInGrid.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def points(self) -> GeometrySocketLinker:
            """Output socket: Points"""
            return self.get("Points")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return DistributePointsInGrid.Outputs(self)

    @property
    def mode(self) -> Literal["DENSITY_RANDOM", "DENSITY_GRID"]:
        return self.node.mode

    @mode.setter
    def mode(self, value: Literal["DENSITY_RANDOM", "DENSITY_GRID"]):
        self.node.mode = value


class DistributePointsInVolume(NodeBuilder):
    """
    Generate points inside a volume
    """

    _bl_idname = "GeometryNodeDistributePointsInVolume"
    node: bpy.types.GeometryNodeDistributePointsInVolume

    def __init__(
        self,
        volume: InputGeometry = None,
        mode: InputMenu | Literal["Random", "Grid"] = "Random",
        density: InputFloat = 1.0,
        seed: InputInteger = 0,
        spacing: InputVector = None,
        threshold: InputFloat = 0.1,
    ):
        super().__init__()
        key_args = {
            "Volume": volume,
            "Mode": mode,
            "Density": density,
            "Seed": seed,
            "Spacing": spacing,
            "Threshold": threshold,
        }

        self._establish_links(**key_args)

    class Inputs(TypedInputs):
        @property
        def volume(self) -> SocketLinker:
            """Input socket: Volume"""
            return self.get("Volume")

        @property
        def mode(self) -> SocketLinker:
            """Input socket: Mode"""
            return self.get("Mode")

        @property
        def density(self) -> SocketLinker:
            """Input socket: Density"""
            return self.get("Density")

        @property
        def seed(self) -> SocketLinker:
            """Input socket: Seed"""
            return self.get("Seed")

        @property
        def spacing(self) -> SocketLinker:
            """Input socket: Spacing"""
            return self.get("Spacing")

        @property
        def threshold(self) -> SocketLinker:
            """Input socket: Threshold"""
            return self.get("Threshold")

    @property
    def i(self) -> "Inputs":
        return DistributePointsInVolume.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def points(self) -> GeometrySocketLinker:
            """Output socket: Points"""
            return self.get("Points")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return DistributePointsInVolume.Outputs(self)


class GetNamedGrid(NodeBuilder):
    """
    Get volume grid from a volume geometry with the specified name
    """

    _bl_idname = "GeometryNodeGetNamedGrid"
    node: bpy.types.GeometryNodeGetNamedGrid

    def __init__(
        self,
        volume: InputGeometry = None,
        name: InputString = "",
        remove: InputBoolean = True,
        *,
        data_type: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"] = "FLOAT",
    ):
        super().__init__()
        key_args = {"Volume": volume, "Name": name, "Remove": remove}
        self.data_type = data_type
        self._establish_links(**key_args)

    @classmethod
    def float(
        cls,
        volume: InputGeometry = None,
        name: InputString = "",
        remove: InputBoolean = True,
    ) -> "GetNamedGrid":
        """Create Get Named Grid with operation 'Float'."""
        return cls(data_type="FLOAT", volume=volume, name=name, remove=remove)

    @classmethod
    def integer(
        cls,
        volume: InputGeometry = None,
        name: InputString = "",
        remove: InputBoolean = True,
    ) -> "GetNamedGrid":
        """Create Get Named Grid with operation 'Integer'."""
        return cls(data_type="INT", volume=volume, name=name, remove=remove)

    @classmethod
    def boolean(
        cls,
        volume: InputGeometry = None,
        name: InputString = "",
        remove: InputBoolean = True,
    ) -> "GetNamedGrid":
        """Create Get Named Grid with operation 'Boolean'."""
        return cls(data_type="BOOLEAN", volume=volume, name=name, remove=remove)

    @classmethod
    def vector(
        cls,
        volume: InputGeometry = None,
        name: InputString = "",
        remove: InputBoolean = True,
    ) -> "GetNamedGrid":
        """Create Get Named Grid with operation 'Vector'."""
        return cls(data_type="VECTOR", volume=volume, name=name, remove=remove)

    class Inputs(TypedInputs):
        @property
        def volume(self) -> SocketLinker:
            """Input socket: Volume"""
            return self.get("Volume")

        @property
        def name(self) -> SocketLinker:
            """Input socket: Name"""
            return self.get("Name")

        @property
        def remove(self) -> SocketLinker:
            """Input socket: Remove"""
            return self.get("Remove")

    @property
    def i(self) -> "Inputs":
        return GetNamedGrid.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def volume(self) -> GeometrySocketLinker:
            """Output socket: Volume"""
            return self.get("Volume")  # type: ignore[return-value]

        @property
        def grid(self) -> SocketLinker:
            """Output socket: Grid"""
            return self.get("Grid")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return GetNamedGrid.Outputs(self)

    @property
    def data_type(self) -> Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]:
        return self.node.data_type

    @data_type.setter
    def data_type(self, value: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]):
        self.node.data_type = value


class GridCurl(NodeBuilder):
    """
    Calculate the magnitude and direction of circulation of a directional vector grid
    """

    _bl_idname = "GeometryNodeGridCurl"
    node: bpy.types.GeometryNodeGridCurl

    def __init__(self, grid: InputVector = None):
        super().__init__()
        key_args = {"Grid": grid}

        self._establish_links(**key_args)

    class Inputs(TypedInputs):
        @property
        def grid(self) -> SocketLinker:
            """Input socket: Grid"""
            return self.get("Grid")

    @property
    def i(self) -> "Inputs":
        return GridCurl.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def curl(self) -> VectorSocketLinker:
            """Output socket: Curl"""
            return self.get("Curl")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return GridCurl.Outputs(self)


class GridDivergence(NodeBuilder):
    """
    Calculate the flow into and out of each point of a directional vector grid
    """

    _bl_idname = "GeometryNodeGridDivergence"
    node: bpy.types.GeometryNodeGridDivergence

    def __init__(self, grid: InputVector = None):
        super().__init__()
        key_args = {"Grid": grid}

        self._establish_links(**key_args)

    class Inputs(TypedInputs):
        @property
        def grid(self) -> SocketLinker:
            """Input socket: Grid"""
            return self.get("Grid")

    @property
    def i(self) -> "Inputs":
        return GridDivergence.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def divergence(self) -> SocketLinker:
            """Output socket: Divergence"""
            return self.get("Divergence")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return GridDivergence.Outputs(self)


class GridGradient(NodeBuilder):
    """
    Calculate the direction and magnitude of the change in values of a scalar grid
    """

    _bl_idname = "GeometryNodeGridGradient"
    node: bpy.types.GeometryNodeGridGradient

    def __init__(self, grid: InputFloat = 0.0):
        super().__init__()
        key_args = {"Grid": grid}

        self._establish_links(**key_args)

    class Inputs(TypedInputs):
        @property
        def grid(self) -> SocketLinker:
            """Input socket: Grid"""
            return self.get("Grid")

    @property
    def i(self) -> "Inputs":
        return GridGradient.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def gradient(self) -> VectorSocketLinker:
            """Output socket: Gradient"""
            return self.get("Gradient")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return GridGradient.Outputs(self)


class GridInfo(NodeBuilder):
    """
    Retrieve information about a volume grid
    """

    _bl_idname = "GeometryNodeGridInfo"
    node: bpy.types.GeometryNodeGridInfo

    def __init__(
        self,
        grid: InputFloat = 0.0,
        *,
        data_type: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"] = "FLOAT",
    ):
        super().__init__()
        key_args = {"Grid": grid}
        self.data_type = data_type
        self._establish_links(**key_args)

    @classmethod
    def float(cls, grid: InputFloat = 0.0) -> "GridInfo":
        """Create Grid Info with operation 'Float'."""
        return cls(data_type="FLOAT", grid=grid)

    @classmethod
    def integer(cls, grid: InputInteger = 0) -> "GridInfo":
        """Create Grid Info with operation 'Integer'."""
        return cls(data_type="INT", grid=grid)

    @classmethod
    def boolean(cls, grid: InputBoolean = False) -> "GridInfo":
        """Create Grid Info with operation 'Boolean'."""
        return cls(data_type="BOOLEAN", grid=grid)

    @classmethod
    def vector(cls, grid: InputVector = None) -> "GridInfo":
        """Create Grid Info with operation 'Vector'."""
        return cls(data_type="VECTOR", grid=grid)

    class Inputs(TypedInputs):
        @property
        def grid(self) -> SocketLinker:
            """Input socket: Grid"""
            return self.get("Grid")

    @property
    def i(self) -> "Inputs":
        return GridInfo.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def transform(self) -> MatrixSocketLinker:
            """Output socket: Transform"""
            return self.get("Transform")  # type: ignore[return-value]

        @property
        def background_value(self) -> SocketLinker:
            """Output socket: Background Value"""
            return self.get("Background Value")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return GridInfo.Outputs(self)

    @property
    def data_type(self) -> Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]:
        return self.node.data_type

    @data_type.setter
    def data_type(self, value: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]):
        self.node.data_type = value


class GridLaplacian(NodeBuilder):
    """
    Compute the divergence of the gradient of the input grid
    """

    _bl_idname = "GeometryNodeGridLaplacian"
    node: bpy.types.GeometryNodeGridLaplacian

    def __init__(self, grid: InputFloat = 0.0):
        super().__init__()
        key_args = {"Grid": grid}

        self._establish_links(**key_args)

    class Inputs(TypedInputs):
        @property
        def grid(self) -> SocketLinker:
            """Input socket: Grid"""
            return self.get("Grid")

    @property
    def i(self) -> "Inputs":
        return GridLaplacian.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def laplacian(self) -> SocketLinker:
            """Output socket: Laplacian"""
            return self.get("Laplacian")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return GridLaplacian.Outputs(self)


class GridToMesh(NodeBuilder):
    """
    Generate a mesh on the "surface" of a volume grid
    """

    _bl_idname = "GeometryNodeGridToMesh"
    node: bpy.types.GeometryNodeGridToMesh

    def __init__(
        self,
        grid: InputFloat = 0.0,
        threshold: InputFloat = 0.1,
        adaptivity: InputFloat = 0.0,
    ):
        super().__init__()
        key_args = {"Grid": grid, "Threshold": threshold, "Adaptivity": adaptivity}

        self._establish_links(**key_args)

    class Inputs(TypedInputs):
        @property
        def grid(self) -> SocketLinker:
            """Input socket: Grid"""
            return self.get("Grid")

        @property
        def threshold(self) -> SocketLinker:
            """Input socket: Threshold"""
            return self.get("Threshold")

        @property
        def adaptivity(self) -> SocketLinker:
            """Input socket: Adaptivity"""
            return self.get("Adaptivity")

    @property
    def i(self) -> "Inputs":
        return GridToMesh.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def mesh(self) -> GeometrySocketLinker:
            """Output socket: Mesh"""
            return self.get("Mesh")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return GridToMesh.Outputs(self)


class MeshToDensityGrid(NodeBuilder):
    """
    Create a filled volume grid from a mesh
    """

    _bl_idname = "GeometryNodeMeshToDensityGrid"
    node: bpy.types.GeometryNodeMeshToDensityGrid

    def __init__(
        self,
        mesh: InputGeometry = None,
        density: InputFloat = 1.0,
        voxel_size: InputFloat = 0.3,
        gradient_width: InputFloat = 0.2,
    ):
        super().__init__()
        key_args = {
            "Mesh": mesh,
            "Density": density,
            "Voxel Size": voxel_size,
            "Gradient Width": gradient_width,
        }

        self._establish_links(**key_args)

    class Inputs(TypedInputs):
        @property
        def mesh(self) -> SocketLinker:
            """Input socket: Mesh"""
            return self.get("Mesh")

        @property
        def density(self) -> SocketLinker:
            """Input socket: Density"""
            return self.get("Density")

        @property
        def voxel_size(self) -> SocketLinker:
            """Input socket: Voxel Size"""
            return self.get("Voxel Size")

        @property
        def gradient_width(self) -> SocketLinker:
            """Input socket: Gradient Width"""
            return self.get("Gradient Width")

    @property
    def i(self) -> "Inputs":
        return MeshToDensityGrid.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def density_grid(self) -> SocketLinker:
            """Output socket: Density Grid"""
            return self.get("Density Grid")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return MeshToDensityGrid.Outputs(self)


class MeshToSDFGrid(NodeBuilder):
    """
    Create a signed distance volume grid from a mesh
    """

    _bl_idname = "GeometryNodeMeshToSDFGrid"
    node: bpy.types.GeometryNodeMeshToSDFGrid

    def __init__(
        self,
        mesh: InputGeometry = None,
        voxel_size: InputFloat = 0.3,
        band_width: InputInteger = 3,
    ):
        super().__init__()
        key_args = {"Mesh": mesh, "Voxel Size": voxel_size, "Band Width": band_width}

        self._establish_links(**key_args)

    class Inputs(TypedInputs):
        @property
        def mesh(self) -> SocketLinker:
            """Input socket: Mesh"""
            return self.get("Mesh")

        @property
        def voxel_size(self) -> SocketLinker:
            """Input socket: Voxel Size"""
            return self.get("Voxel Size")

        @property
        def band_width(self) -> SocketLinker:
            """Input socket: Band Width"""
            return self.get("Band Width")

    @property
    def i(self) -> "Inputs":
        return MeshToSDFGrid.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def sdf_grid(self) -> SocketLinker:
            """Output socket: SDF Grid"""
            return self.get("SDF Grid")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return MeshToSDFGrid.Outputs(self)


class MeshToVolume(NodeBuilder):
    """
    Create a fog volume with the shape of the input mesh's surface
    """

    _bl_idname = "GeometryNodeMeshToVolume"
    node: bpy.types.GeometryNodeMeshToVolume

    def __init__(
        self,
        mesh: InputGeometry = None,
        density: InputFloat = 1.0,
        resolution_mode: InputMenu | Literal["Amount", "Size"] = "Amount",
        voxel_size: InputFloat = 0.3,
        voxel_amount: InputFloat = 64.0,
        interior_band_width: InputFloat = 0.2,
    ):
        super().__init__()
        key_args = {
            "Mesh": mesh,
            "Density": density,
            "Resolution Mode": resolution_mode,
            "Voxel Size": voxel_size,
            "Voxel Amount": voxel_amount,
            "Interior Band Width": interior_band_width,
        }

        self._establish_links(**key_args)

    class Inputs(TypedInputs):
        @property
        def mesh(self) -> SocketLinker:
            """Input socket: Mesh"""
            return self.get("Mesh")

        @property
        def density(self) -> SocketLinker:
            """Input socket: Density"""
            return self.get("Density")

        @property
        def resolution_mode(self) -> SocketLinker:
            """Input socket: Resolution Mode"""
            return self.get("Resolution Mode")

        @property
        def voxel_size(self) -> SocketLinker:
            """Input socket: Voxel Size"""
            return self.get("Voxel Size")

        @property
        def voxel_amount(self) -> SocketLinker:
            """Input socket: Voxel Amount"""
            return self.get("Voxel Amount")

        @property
        def interior_band_width(self) -> SocketLinker:
            """Input socket: Interior Band Width"""
            return self.get("Interior Band Width")

    @property
    def i(self) -> "Inputs":
        return MeshToVolume.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def volume(self) -> GeometrySocketLinker:
            """Output socket: Volume"""
            return self.get("Volume")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return MeshToVolume.Outputs(self)


class PointsToSDFGrid(NodeBuilder):
    """
    Create a signed distance volume grid from points
    """

    _bl_idname = "GeometryNodePointsToSDFGrid"
    node: bpy.types.GeometryNodePointsToSDFGrid

    def __init__(
        self,
        points: InputGeometry = None,
        radius: InputFloat = 0.5,
        voxel_size: InputFloat = 0.3,
    ):
        super().__init__()
        key_args = {"Points": points, "Radius": radius, "Voxel Size": voxel_size}

        self._establish_links(**key_args)

    class Inputs(TypedInputs):
        @property
        def points(self) -> SocketLinker:
            """Input socket: Points"""
            return self.get("Points")

        @property
        def radius(self) -> SocketLinker:
            """Input socket: Radius"""
            return self.get("Radius")

        @property
        def voxel_size(self) -> SocketLinker:
            """Input socket: Voxel Size"""
            return self.get("Voxel Size")

    @property
    def i(self) -> "Inputs":
        return PointsToSDFGrid.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def sdf_grid(self) -> SocketLinker:
            """Output socket: SDF Grid"""
            return self.get("SDF Grid")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return PointsToSDFGrid.Outputs(self)


class PointsToVolume(NodeBuilder):
    """
    Generate a fog volume sphere around every point
    """

    _bl_idname = "GeometryNodePointsToVolume"
    node: bpy.types.GeometryNodePointsToVolume

    def __init__(
        self,
        points: InputGeometry = None,
        density: InputFloat = 1.0,
        resolution_mode: InputMenu | Literal["Amount", "Size"] = "Amount",
        voxel_size: InputFloat = 0.3,
        voxel_amount: InputFloat = 64.0,
        radius: InputFloat = 0.5,
    ):
        super().__init__()
        key_args = {
            "Points": points,
            "Density": density,
            "Resolution Mode": resolution_mode,
            "Voxel Size": voxel_size,
            "Voxel Amount": voxel_amount,
            "Radius": radius,
        }

        self._establish_links(**key_args)

    class Inputs(TypedInputs):
        @property
        def points(self) -> SocketLinker:
            """Input socket: Points"""
            return self.get("Points")

        @property
        def density(self) -> SocketLinker:
            """Input socket: Density"""
            return self.get("Density")

        @property
        def resolution_mode(self) -> SocketLinker:
            """Input socket: Resolution Mode"""
            return self.get("Resolution Mode")

        @property
        def voxel_size(self) -> SocketLinker:
            """Input socket: Voxel Size"""
            return self.get("Voxel Size")

        @property
        def voxel_amount(self) -> SocketLinker:
            """Input socket: Voxel Amount"""
            return self.get("Voxel Amount")

        @property
        def radius(self) -> SocketLinker:
            """Input socket: Radius"""
            return self.get("Radius")

    @property
    def i(self) -> "Inputs":
        return PointsToVolume.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def volume(self) -> GeometrySocketLinker:
            """Output socket: Volume"""
            return self.get("Volume")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return PointsToVolume.Outputs(self)


class PruneGrid(NodeBuilder):
    """
    Make the storage of a volume grid more efficient by collapsing data into tiles or inner nodes
    """

    _bl_idname = "GeometryNodeGridPrune"
    node: bpy.types.GeometryNodeGridPrune

    def __init__(
        self,
        grid: InputFloat = 0.0,
        mode: InputMenu | Literal["Inactive", "Threshold", "SDF"] = "Threshold",
        threshold: InputFloat = 0.01,
        *,
        data_type: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"] = "FLOAT",
    ):
        super().__init__()
        key_args = {"Grid": grid, "Mode": mode, "Threshold": threshold}
        self.data_type = data_type
        self._establish_links(**key_args)

    @classmethod
    def float(
        cls,
        grid: InputFloat = 0.0,
        mode: InputMenu | Literal["Inactive", "Threshold", "SDF"] = "Threshold",
        threshold: InputFloat = 0.01,
    ) -> "PruneGrid":
        """Create Prune Grid with operation 'Float'."""
        return cls(data_type="FLOAT", grid=grid, mode=mode, threshold=threshold)

    @classmethod
    def integer(
        cls,
        grid: InputInteger = 0,
        mode: InputMenu | Literal["Inactive", "Threshold", "SDF"] = "Threshold",
        threshold: InputInteger = 0,
    ) -> "PruneGrid":
        """Create Prune Grid with operation 'Integer'."""
        return cls(data_type="INT", grid=grid, mode=mode, threshold=threshold)

    @classmethod
    def boolean(
        cls,
        grid: InputBoolean = False,
        mode: InputMenu | Literal["Inactive", "Threshold", "SDF"] = "Threshold",
    ) -> "PruneGrid":
        """Create Prune Grid with operation 'Boolean'."""
        return cls(data_type="BOOLEAN", grid=grid, mode=mode)

    @classmethod
    def vector(
        cls,
        grid: InputVector = None,
        mode: InputMenu | Literal["Inactive", "Threshold", "SDF"] = "Threshold",
        threshold: InputVector = None,
    ) -> "PruneGrid":
        """Create Prune Grid with operation 'Vector'."""
        return cls(data_type="VECTOR", grid=grid, mode=mode, threshold=threshold)

    class Inputs(TypedInputs):
        @property
        def grid(self) -> SocketLinker:
            """Input socket: Grid"""
            return self.get("Grid")

        @property
        def mode(self) -> SocketLinker:
            """Input socket: Mode"""
            return self.get("Mode")

        @property
        def threshold(self) -> SocketLinker:
            """Input socket: Threshold"""
            return self.get("Threshold")

    @property
    def i(self) -> "Inputs":
        return PruneGrid.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def grid(self) -> SocketLinker:
            """Output socket: Grid"""
            return self.get("Grid")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return PruneGrid.Outputs(self)

    @property
    def data_type(self) -> Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]:
        return self.node.data_type

    @data_type.setter
    def data_type(self, value: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]):
        self.node.data_type = value


class SDFGridFillet(NodeBuilder):
    """
    Round off concave internal corners in a signed distance field. Only affects areas with negative principal curvature, creating smoother transitions between surfaces
    """

    _bl_idname = "GeometryNodeSDFGridFillet"
    node: bpy.types.GeometryNodeSDFGridFillet

    def __init__(
        self,
        grid: InputFloat = 0.0,
        iterations: InputInteger = 1,
    ):
        super().__init__()
        key_args = {"Grid": grid, "Iterations": iterations}

        self._establish_links(**key_args)

    class Inputs(TypedInputs):
        @property
        def grid(self) -> SocketLinker:
            """Input socket: Grid"""
            return self.get("Grid")

        @property
        def iterations(self) -> SocketLinker:
            """Input socket: Iterations"""
            return self.get("Iterations")

    @property
    def i(self) -> "Inputs":
        return SDFGridFillet.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def grid(self) -> SocketLinker:
            """Output socket: Grid"""
            return self.get("Grid")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return SDFGridFillet.Outputs(self)


class SDFGridLaplacian(NodeBuilder):
    """
    Apply Laplacian flow smoothing to a signed distance field. Computationally efficient alternative to mean curvature flow, ideal when combined with SDF normalization
    """

    _bl_idname = "GeometryNodeSDFGridLaplacian"
    node: bpy.types.GeometryNodeSDFGridLaplacian

    def __init__(
        self,
        grid: InputFloat = 0.0,
        iterations: InputInteger = 1,
    ):
        super().__init__()
        key_args = {"Grid": grid, "Iterations": iterations}

        self._establish_links(**key_args)

    class Inputs(TypedInputs):
        @property
        def grid(self) -> SocketLinker:
            """Input socket: Grid"""
            return self.get("Grid")

        @property
        def iterations(self) -> SocketLinker:
            """Input socket: Iterations"""
            return self.get("Iterations")

    @property
    def i(self) -> "Inputs":
        return SDFGridLaplacian.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def grid(self) -> SocketLinker:
            """Output socket: Grid"""
            return self.get("Grid")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return SDFGridLaplacian.Outputs(self)


class SDFGridMean(NodeBuilder):
    """
    Apply mean (box) filter smoothing to a signed distance field. Fast separable averaging filter for general smoothing of the distance field
    """

    _bl_idname = "GeometryNodeSDFGridMean"
    node: bpy.types.GeometryNodeSDFGridMean

    def __init__(
        self,
        grid: InputFloat = 0.0,
        width: InputInteger = 1,
        iterations: InputInteger = 1,
    ):
        super().__init__()
        key_args = {"Grid": grid, "Width": width, "Iterations": iterations}

        self._establish_links(**key_args)

    class Inputs(TypedInputs):
        @property
        def grid(self) -> SocketLinker:
            """Input socket: Grid"""
            return self.get("Grid")

        @property
        def width(self) -> SocketLinker:
            """Input socket: Width"""
            return self.get("Width")

        @property
        def iterations(self) -> SocketLinker:
            """Input socket: Iterations"""
            return self.get("Iterations")

    @property
    def i(self) -> "Inputs":
        return SDFGridMean.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def grid(self) -> SocketLinker:
            """Output socket: Grid"""
            return self.get("Grid")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return SDFGridMean.Outputs(self)


class SDFGridMeanCurvature(NodeBuilder):
    """
    Apply mean curvature flow smoothing to a signed distance field. Evolves the surface based on its mean curvature, naturally smoothing high-curvature regions more than flat areas
    """

    _bl_idname = "GeometryNodeSDFGridMeanCurvature"
    node: bpy.types.GeometryNodeSDFGridMeanCurvature

    def __init__(
        self,
        grid: InputFloat = 0.0,
        iterations: InputInteger = 1,
    ):
        super().__init__()
        key_args = {"Grid": grid, "Iterations": iterations}

        self._establish_links(**key_args)

    class Inputs(TypedInputs):
        @property
        def grid(self) -> SocketLinker:
            """Input socket: Grid"""
            return self.get("Grid")

        @property
        def iterations(self) -> SocketLinker:
            """Input socket: Iterations"""
            return self.get("Iterations")

    @property
    def i(self) -> "Inputs":
        return SDFGridMeanCurvature.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def grid(self) -> SocketLinker:
            """Output socket: Grid"""
            return self.get("Grid")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return SDFGridMeanCurvature.Outputs(self)


class SDFGridMedian(NodeBuilder):
    """
    Apply median filter to a signed distance field. Reduces noise while preserving sharp features and edges in the distance field
    """

    _bl_idname = "GeometryNodeSDFGridMedian"
    node: bpy.types.GeometryNodeSDFGridMedian

    def __init__(
        self,
        grid: InputFloat = 0.0,
        width: InputInteger = 1,
        iterations: InputInteger = 1,
    ):
        super().__init__()
        key_args = {"Grid": grid, "Width": width, "Iterations": iterations}

        self._establish_links(**key_args)

    class Inputs(TypedInputs):
        @property
        def grid(self) -> SocketLinker:
            """Input socket: Grid"""
            return self.get("Grid")

        @property
        def width(self) -> SocketLinker:
            """Input socket: Width"""
            return self.get("Width")

        @property
        def iterations(self) -> SocketLinker:
            """Input socket: Iterations"""
            return self.get("Iterations")

    @property
    def i(self) -> "Inputs":
        return SDFGridMedian.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def grid(self) -> SocketLinker:
            """Output socket: Grid"""
            return self.get("Grid")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return SDFGridMedian.Outputs(self)


class SDFGridOffset(NodeBuilder):
    """
    Offset a signed distance field surface by a world-space distance. Dilates (positive) or erodes (negative) while maintaining the signed distance property
    """

    _bl_idname = "GeometryNodeSDFGridOffset"
    node: bpy.types.GeometryNodeSDFGridOffset

    def __init__(
        self,
        grid: InputFloat = 0.0,
        distance: InputFloat = 0.1,
    ):
        super().__init__()
        key_args = {"Grid": grid, "Distance": distance}

        self._establish_links(**key_args)

    class Inputs(TypedInputs):
        @property
        def grid(self) -> SocketLinker:
            """Input socket: Grid"""
            return self.get("Grid")

        @property
        def distance(self) -> SocketLinker:
            """Input socket: Distance"""
            return self.get("Distance")

    @property
    def i(self) -> "Inputs":
        return SDFGridOffset.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def grid(self) -> SocketLinker:
            """Output socket: Grid"""
            return self.get("Grid")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return SDFGridOffset.Outputs(self)


class SampleGrid(NodeBuilder):
    """
    Retrieve values from the specified volume grid
    """

    _bl_idname = "GeometryNodeSampleGrid"
    node: bpy.types.GeometryNodeSampleGrid

    def __init__(
        self,
        grid: InputFloat = 0.0,
        position: InputVector = None,
        interpolation: InputMenu
        | Literal["Nearest Neighbor", "Trilinear", "Triquadratic"] = "Trilinear",
        *,
        data_type: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"] = "FLOAT",
    ):
        super().__init__()
        key_args = {"Grid": grid, "Position": position, "Interpolation": interpolation}
        self.data_type = data_type
        self._establish_links(**key_args)

    @classmethod
    def float(
        cls,
        grid: InputFloat = 0.0,
        position: InputVector = None,
        interpolation: InputMenu
        | Literal["Nearest Neighbor", "Trilinear", "Triquadratic"] = "Trilinear",
    ) -> "SampleGrid":
        """Create Sample Grid with operation 'Float'."""
        return cls(
            data_type="FLOAT", grid=grid, position=position, interpolation=interpolation
        )

    @classmethod
    def integer(
        cls,
        grid: InputInteger = 0,
        position: InputVector = None,
        interpolation: InputMenu
        | Literal["Nearest Neighbor", "Trilinear", "Triquadratic"] = "Trilinear",
    ) -> "SampleGrid":
        """Create Sample Grid with operation 'Integer'."""
        return cls(
            data_type="INT", grid=grid, position=position, interpolation=interpolation
        )

    @classmethod
    def boolean(
        cls,
        grid: InputBoolean = False,
        position: InputVector = None,
        interpolation: InputMenu
        | Literal["Nearest Neighbor", "Trilinear", "Triquadratic"] = "Trilinear",
    ) -> "SampleGrid":
        """Create Sample Grid with operation 'Boolean'."""
        return cls(
            data_type="BOOLEAN",
            grid=grid,
            position=position,
            interpolation=interpolation,
        )

    @classmethod
    def vector(
        cls,
        grid: InputVector = None,
        position: InputVector = None,
        interpolation: InputMenu
        | Literal["Nearest Neighbor", "Trilinear", "Triquadratic"] = "Trilinear",
    ) -> "SampleGrid":
        """Create Sample Grid with operation 'Vector'."""
        return cls(
            data_type="VECTOR",
            grid=grid,
            position=position,
            interpolation=interpolation,
        )

    class Inputs(TypedInputs):
        @property
        def grid(self) -> SocketLinker:
            """Input socket: Grid"""
            return self.get("Grid")

        @property
        def position(self) -> SocketLinker:
            """Input socket: Position"""
            return self.get("Position")

        @property
        def interpolation(self) -> SocketLinker:
            """Input socket: Interpolation"""
            return self.get("Interpolation")

    @property
    def i(self) -> "Inputs":
        return SampleGrid.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def value(self) -> SocketLinker:
            """Output socket: Value"""
            return self.get("Value")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return SampleGrid.Outputs(self)

    @property
    def data_type(self) -> Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]:
        return self.node.data_type

    @data_type.setter
    def data_type(self, value: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]):
        self.node.data_type = value


class SampleGridIndex(NodeBuilder):
    """
    Retrieve volume grid values at specific voxels
    """

    _bl_idname = "GeometryNodeSampleGridIndex"
    node: bpy.types.GeometryNodeSampleGridIndex

    def __init__(
        self,
        grid: InputFloat = 0.0,
        x: InputInteger = 0,
        y: InputInteger = 0,
        z: InputInteger = 0,
        *,
        data_type: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"] = "FLOAT",
    ):
        super().__init__()
        key_args = {"Grid": grid, "X": x, "Y": y, "Z": z}
        self.data_type = data_type
        self._establish_links(**key_args)

    @classmethod
    def float(
        cls,
        grid: InputFloat = 0.0,
        x: InputInteger = 0,
        y: InputInteger = 0,
        z: InputInteger = 0,
    ) -> "SampleGridIndex":
        """Create Sample Grid Index with operation 'Float'."""
        return cls(data_type="FLOAT", grid=grid, x=x, y=y, z=z)

    @classmethod
    def integer(
        cls,
        grid: InputInteger = 0,
        x: InputInteger = 0,
        y: InputInteger = 0,
        z: InputInteger = 0,
    ) -> "SampleGridIndex":
        """Create Sample Grid Index with operation 'Integer'."""
        return cls(data_type="INT", grid=grid, x=x, y=y, z=z)

    @classmethod
    def boolean(
        cls,
        grid: InputBoolean = False,
        x: InputInteger = 0,
        y: InputInteger = 0,
        z: InputInteger = 0,
    ) -> "SampleGridIndex":
        """Create Sample Grid Index with operation 'Boolean'."""
        return cls(data_type="BOOLEAN", grid=grid, x=x, y=y, z=z)

    @classmethod
    def vector(
        cls,
        grid: InputVector = None,
        x: InputInteger = 0,
        y: InputInteger = 0,
        z: InputInteger = 0,
    ) -> "SampleGridIndex":
        """Create Sample Grid Index with operation 'Vector'."""
        return cls(data_type="VECTOR", grid=grid, x=x, y=y, z=z)

    class Inputs(TypedInputs):
        @property
        def grid(self) -> SocketLinker:
            """Input socket: Grid"""
            return self.get("Grid")

        @property
        def x(self) -> SocketLinker:
            """Input socket: X"""
            return self.get("X")

        @property
        def y(self) -> SocketLinker:
            """Input socket: Y"""
            return self.get("Y")

        @property
        def z(self) -> SocketLinker:
            """Input socket: Z"""
            return self.get("Z")

    @property
    def i(self) -> "Inputs":
        return SampleGridIndex.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def value(self) -> SocketLinker:
            """Output socket: Value"""
            return self.get("Value")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return SampleGridIndex.Outputs(self)

    @property
    def data_type(self) -> Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]:
        return self.node.data_type

    @data_type.setter
    def data_type(self, value: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]):
        self.node.data_type = value


class SetGridBackground(NodeBuilder):
    """
    Set the background value used for inactive voxels and tiles
    """

    _bl_idname = "GeometryNodeSetGridBackground"
    node: bpy.types.GeometryNodeSetGridBackground

    def __init__(
        self,
        grid: InputFloat = 0.0,
        background: InputFloat = 0.0,
        *,
        data_type: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"] = "FLOAT",
    ):
        super().__init__()
        key_args = {"Grid": grid, "Background": background}
        self.data_type = data_type
        self._establish_links(**key_args)

    @classmethod
    def float(
        cls, grid: InputFloat = 0.0, background: InputFloat = 0.0
    ) -> "SetGridBackground":
        """Create Set Grid Background with operation 'Float'."""
        return cls(data_type="FLOAT", grid=grid, background=background)

    @classmethod
    def integer(
        cls, grid: InputInteger = 0, background: InputInteger = 0
    ) -> "SetGridBackground":
        """Create Set Grid Background with operation 'Integer'."""
        return cls(data_type="INT", grid=grid, background=background)

    @classmethod
    def boolean(
        cls, grid: InputBoolean = False, background: InputBoolean = False
    ) -> "SetGridBackground":
        """Create Set Grid Background with operation 'Boolean'."""
        return cls(data_type="BOOLEAN", grid=grid, background=background)

    @classmethod
    def vector(
        cls, grid: InputVector = None, background: InputVector = None
    ) -> "SetGridBackground":
        """Create Set Grid Background with operation 'Vector'."""
        return cls(data_type="VECTOR", grid=grid, background=background)

    class Inputs(TypedInputs):
        @property
        def grid(self) -> SocketLinker:
            """Input socket: Grid"""
            return self.get("Grid")

        @property
        def background(self) -> SocketLinker:
            """Input socket: Background"""
            return self.get("Background")

    @property
    def i(self) -> "Inputs":
        return SetGridBackground.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def grid(self) -> SocketLinker:
            """Output socket: Grid"""
            return self.get("Grid")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return SetGridBackground.Outputs(self)

    @property
    def data_type(self) -> Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]:
        return self.node.data_type

    @data_type.setter
    def data_type(self, value: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]):
        self.node.data_type = value


class SetGridTransform(NodeBuilder):
    """
    Set the transform for the grid from index space into object space.
    """

    _bl_idname = "GeometryNodeSetGridTransform"
    node: bpy.types.GeometryNodeSetGridTransform

    def __init__(
        self,
        grid: InputFloat = 0.0,
        transform: InputMatrix = None,
        *,
        data_type: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"] = "FLOAT",
    ):
        super().__init__()
        key_args = {"Grid": grid, "Transform": transform}
        self.data_type = data_type
        self._establish_links(**key_args)

    @classmethod
    def float(
        cls, grid: InputFloat = 0.0, transform: InputMatrix = None
    ) -> "SetGridTransform":
        """Create Set Grid Transform with operation 'Float'."""
        return cls(data_type="FLOAT", grid=grid, transform=transform)

    @classmethod
    def integer(
        cls, grid: InputInteger = 0, transform: InputMatrix = None
    ) -> "SetGridTransform":
        """Create Set Grid Transform with operation 'Integer'."""
        return cls(data_type="INT", grid=grid, transform=transform)

    @classmethod
    def boolean(
        cls, grid: InputBoolean = False, transform: InputMatrix = None
    ) -> "SetGridTransform":
        """Create Set Grid Transform with operation 'Boolean'."""
        return cls(data_type="BOOLEAN", grid=grid, transform=transform)

    @classmethod
    def vector(
        cls, grid: InputVector = None, transform: InputMatrix = None
    ) -> "SetGridTransform":
        """Create Set Grid Transform with operation 'Vector'."""
        return cls(data_type="VECTOR", grid=grid, transform=transform)

    class Inputs(TypedInputs):
        @property
        def grid(self) -> SocketLinker:
            """Input socket: Grid"""
            return self.get("Grid")

        @property
        def transform(self) -> SocketLinker:
            """Input socket: Transform"""
            return self.get("Transform")

    @property
    def i(self) -> "Inputs":
        return SetGridTransform.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def is_valid(self) -> BooleanSocketLinker:
            """Output socket: Is Valid"""
            return self.get("Is Valid")  # type: ignore[return-value]

        @property
        def grid(self) -> SocketLinker:
            """Output socket: Grid"""
            return self.get("Grid")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return SetGridTransform.Outputs(self)

    @property
    def data_type(self) -> Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]:
        return self.node.data_type

    @data_type.setter
    def data_type(self, value: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]):
        self.node.data_type = value


class StoreNamedGrid(NodeBuilder):
    """
    Store grid data in a volume geometry with the specified name
    """

    _bl_idname = "GeometryNodeStoreNamedGrid"
    node: bpy.types.GeometryNodeStoreNamedGrid

    def __init__(
        self,
        volume: InputGeometry = None,
        name: InputString = "",
        grid: InputFloat = 0.0,
        *,
        data_type: Literal["BOOLEAN", "FLOAT", "INT", "VECTOR_FLOAT"] = "FLOAT",
    ):
        super().__init__()
        key_args = {"Volume": volume, "Name": name, "Grid": grid}
        self.data_type = data_type
        self._establish_links(**key_args)

    @classmethod
    def boolean(
        cls,
        volume: InputGeometry = None,
        name: InputString = "",
        grid: InputBoolean = False,
    ) -> "StoreNamedGrid":
        """Create Store Named Grid with operation 'Boolean'."""
        return cls(data_type="BOOLEAN", volume=volume, name=name, grid=grid)

    @classmethod
    def float(
        cls,
        volume: InputGeometry = None,
        name: InputString = "",
        grid: InputFloat = 0.0,
    ) -> "StoreNamedGrid":
        """Create Store Named Grid with operation 'Float'."""
        return cls(data_type="FLOAT", volume=volume, name=name, grid=grid)

    @classmethod
    def integer(
        cls,
        volume: InputGeometry = None,
        name: InputString = "",
        grid: InputInteger = 0,
    ) -> "StoreNamedGrid":
        """Create Store Named Grid with operation 'Integer'."""
        return cls(data_type="INT", volume=volume, name=name, grid=grid)

    @classmethod
    def vector(
        cls,
        volume: InputGeometry = None,
        name: InputString = "",
        grid: InputVector = None,
    ) -> "StoreNamedGrid":
        """Create Store Named Grid with operation 'Vector'."""
        return cls(data_type="VECTOR_FLOAT", volume=volume, name=name, grid=grid)

    class Inputs(TypedInputs):
        @property
        def volume(self) -> SocketLinker:
            """Input socket: Volume"""
            return self.get("Volume")

        @property
        def name(self) -> SocketLinker:
            """Input socket: Name"""
            return self.get("Name")

        @property
        def grid(self) -> SocketLinker:
            """Input socket: Grid"""
            return self.get("Grid")

    @property
    def i(self) -> "Inputs":
        return StoreNamedGrid.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def volume(self) -> GeometrySocketLinker:
            """Output socket: Volume"""
            return self.get("Volume")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return StoreNamedGrid.Outputs(self)

    @property
    def data_type(self) -> Literal["BOOLEAN", "FLOAT", "INT", "VECTOR_FLOAT"]:
        return self.node.data_type

    @data_type.setter
    def data_type(self, value: Literal["BOOLEAN", "FLOAT", "INT", "VECTOR_FLOAT"]):
        self.node.data_type = value


class VolumeCube(NodeBuilder):
    """
    Generate a dense volume with a field that controls the density at each grid voxel based on its position
    """

    _bl_idname = "GeometryNodeVolumeCube"
    node: bpy.types.GeometryNodeVolumeCube

    def __init__(
        self,
        density: InputFloat = 1.0,
        background: InputFloat = 0.0,
        min: InputVector = None,
        max: InputVector = None,
        resolution_x: InputInteger = 32,
        resolution_y: InputInteger = 32,
        resolution_z: InputInteger = 32,
    ):
        super().__init__()
        key_args = {
            "Density": density,
            "Background": background,
            "Min": min,
            "Max": max,
            "Resolution X": resolution_x,
            "Resolution Y": resolution_y,
            "Resolution Z": resolution_z,
        }

        self._establish_links(**key_args)

    class Inputs(TypedInputs):
        @property
        def density(self) -> SocketLinker:
            """Input socket: Density"""
            return self.get("Density")

        @property
        def background(self) -> SocketLinker:
            """Input socket: Background"""
            return self.get("Background")

        @property
        def min(self) -> SocketLinker:
            """Input socket: Min"""
            return self.get("Min")

        @property
        def max(self) -> SocketLinker:
            """Input socket: Max"""
            return self.get("Max")

        @property
        def resolution_x(self) -> SocketLinker:
            """Input socket: Resolution X"""
            return self.get("Resolution X")

        @property
        def resolution_y(self) -> SocketLinker:
            """Input socket: Resolution Y"""
            return self.get("Resolution Y")

        @property
        def resolution_z(self) -> SocketLinker:
            """Input socket: Resolution Z"""
            return self.get("Resolution Z")

    @property
    def i(self) -> "Inputs":
        return VolumeCube.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def volume(self) -> GeometrySocketLinker:
            """Output socket: Volume"""
            return self.get("Volume")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return VolumeCube.Outputs(self)


class VolumeToMesh(NodeBuilder):
    """
    Generate a mesh on the "surface" of a volume
    """

    _bl_idname = "GeometryNodeVolumeToMesh"
    node: bpy.types.GeometryNodeVolumeToMesh

    def __init__(
        self,
        volume: InputGeometry = None,
        resolution_mode: InputMenu | Literal["Grid", "Amount", "Size"] = "Grid",
        voxel_size: InputFloat = 0.3,
        voxel_amount: InputFloat = 64.0,
        threshold: InputFloat = 0.1,
        adaptivity: InputFloat = 0.0,
    ):
        super().__init__()
        key_args = {
            "Volume": volume,
            "Resolution Mode": resolution_mode,
            "Voxel Size": voxel_size,
            "Voxel Amount": voxel_amount,
            "Threshold": threshold,
            "Adaptivity": adaptivity,
        }

        self._establish_links(**key_args)

    class Inputs(TypedInputs):
        @property
        def volume(self) -> SocketLinker:
            """Input socket: Volume"""
            return self.get("Volume")

        @property
        def resolution_mode(self) -> SocketLinker:
            """Input socket: Resolution Mode"""
            return self.get("Resolution Mode")

        @property
        def voxel_size(self) -> SocketLinker:
            """Input socket: Voxel Size"""
            return self.get("Voxel Size")

        @property
        def voxel_amount(self) -> SocketLinker:
            """Input socket: Voxel Amount"""
            return self.get("Voxel Amount")

        @property
        def threshold(self) -> SocketLinker:
            """Input socket: Threshold"""
            return self.get("Threshold")

        @property
        def adaptivity(self) -> SocketLinker:
            """Input socket: Adaptivity"""
            return self.get("Adaptivity")

    @property
    def i(self) -> "Inputs":
        return VolumeToMesh.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def mesh(self) -> GeometrySocketLinker:
            """Output socket: Mesh"""
            return self.get("Mesh")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return VolumeToMesh.Outputs(self)


class VoxelizeGrid(NodeBuilder):
    """
    Remove sparseness from a volume grid by making the active tiles into voxels
    """

    _bl_idname = "GeometryNodeGridVoxelize"
    node: bpy.types.GeometryNodeGridVoxelize

    def __init__(
        self,
        grid: InputFloat = 0.0,
        *,
        data_type: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"] = "FLOAT",
    ):
        super().__init__()
        key_args = {"Grid": grid}
        self.data_type = data_type
        self._establish_links(**key_args)

    @classmethod
    def float(cls, grid: InputFloat = 0.0) -> "VoxelizeGrid":
        """Create Voxelize Grid with operation 'Float'."""
        return cls(data_type="FLOAT", grid=grid)

    @classmethod
    def integer(cls, grid: InputInteger = 0) -> "VoxelizeGrid":
        """Create Voxelize Grid with operation 'Integer'."""
        return cls(data_type="INT", grid=grid)

    @classmethod
    def boolean(cls, grid: InputBoolean = False) -> "VoxelizeGrid":
        """Create Voxelize Grid with operation 'Boolean'."""
        return cls(data_type="BOOLEAN", grid=grid)

    @classmethod
    def vector(cls, grid: InputVector = None) -> "VoxelizeGrid":
        """Create Voxelize Grid with operation 'Vector'."""
        return cls(data_type="VECTOR", grid=grid)

    class Inputs(TypedInputs):
        @property
        def grid(self) -> SocketLinker:
            """Input socket: Grid"""
            return self.get("Grid")

    @property
    def i(self) -> "Inputs":
        return VoxelizeGrid.Inputs(self)

    class Outputs(TypedOutputs):
        @property
        def grid(self) -> SocketLinker:
            """Output socket: Grid"""
            return self.get("Grid")  # type: ignore[return-value]

    @property
    def o(self) -> "Outputs":
        return VoxelizeGrid.Outputs(self)

    @property
    def data_type(self) -> Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]:
        return self.node.data_type

    @data_type.setter
    def data_type(self, value: Literal["FLOAT", "INT", "BOOLEAN", "VECTOR"]):
        self.node.data_type = value
