# Auto-generated by generate.py — do not edit manually.

from typing import Literal

import bpy

from ...builder import BaseNode as NodeBuilder, Socket, FloatSocket, VectorSocket

from ...types import (
    InputFloat,
    InputVector,
)


class RadialTiling(NodeBuilder):
    """
    Transform Coordinate System for Radial Tiling
    """

    _bl_idname = "ShaderNodeRadialTiling"
    node: bpy.types.ShaderNodeRadialTiling

    def __init__(
        self,
        vector: InputVector = None,
        sides: InputFloat = 5.0,
        roundness: InputFloat = 0.0,
        *,
        normalize: bool = False,
    ):
        super().__init__()
        key_args = {"Vector": vector, "Sides": sides, "Roundness": roundness}
        self.normalize = normalize
        self._establish_links(**key_args)

    @property
    def i_vector(self) -> Socket:
        """Input socket: Vector"""
        return self.inputs.get("Vector")

    @property
    def i_sides(self) -> Socket:
        """Input socket: Sides"""
        return self.inputs.get("Sides")

    @property
    def i_roundness(self) -> Socket:
        """Input socket: Roundness"""
        return self.inputs.get("Roundness")

    @property
    def o_segment_coordinates(self) -> VectorSocket:
        """Output socket: Segment Coordinates"""
        return self.outputs.get("Segment Coordinates")

    @property
    def o_segment_id(self) -> FloatSocket:
        """Output socket: Segment ID"""
        return self.outputs.get("Segment ID")

    @property
    def o_segment_width(self) -> FloatSocket:
        """Output socket: Segment Width"""
        return self.outputs.get("Segment Width")

    @property
    def o_segment_rotation(self) -> FloatSocket:
        """Output socket: Segment Rotation"""
        return self.outputs.get("Segment Rotation")

    @property
    def normalize(self) -> bool:
        return self.node.normalize

    @normalize.setter
    def normalize(self, value: bool):
        self.node.normalize = value


class VectorCurves(NodeBuilder):
    """
    Map input vector components with curves
    """

    _bl_idname = "ShaderNodeVectorCurve"
    node: bpy.types.ShaderNodeVectorCurve

    def __init__(
        self,
        fac: InputFloat = 1.0,
        vector: InputVector = None,
    ):
        super().__init__()
        key_args = {"Fac": fac, "Vector": vector}

        self._establish_links(**key_args)

    @property
    def i_fac(self) -> Socket:
        """Input socket: Factor"""
        return self.inputs.get("Fac")

    @property
    def i_vector(self) -> Socket:
        """Input socket: Vector"""
        return self.inputs.get("Vector")

    @property
    def o_vector(self) -> VectorSocket:
        """Output socket: Vector"""
        return self.outputs.get("Vector")


class VectorMath(NodeBuilder):
    """
    Perform vector math operation
    """

    _bl_idname = "ShaderNodeVectorMath"
    node: bpy.types.ShaderNodeVectorMath

    def __init__(
        self,
        vector: InputVector = None,
        vector_001: InputVector = None,
        vector_002: InputVector = None,
        scale: InputFloat = 1.0,
        *,
        operation: Literal[
            "ADD",
            "SUBTRACT",
            "MULTIPLY",
            "DIVIDE",
            "MULTIPLY_ADD",
            "CROSS_PRODUCT",
            "PROJECT",
            "REFLECT",
            "REFRACT",
            "FACEFORWARD",
            "DOT_PRODUCT",
            "DISTANCE",
            "LENGTH",
            "SCALE",
            "NORMALIZE",
            "ABSOLUTE",
            "POWER",
            "SIGN",
            "MINIMUM",
            "MAXIMUM",
            "FLOOR",
            "CEIL",
            "FRACTION",
            "MODULO",
            "WRAP",
            "SNAP",
            "SINE",
            "COSINE",
            "TANGENT",
        ] = "ADD",
    ):
        super().__init__()
        key_args = {
            "Vector": vector,
            "Vector_001": vector_001,
            "Vector_002": vector_002,
            "Scale": scale,
        }
        self.operation = operation
        self._establish_links(**key_args)

    @classmethod
    def add(
        cls, vector: InputVector = None, vector_001: InputVector = None
    ) -> "VectorMath":
        """Create Vector Math with operation 'Add'. A + B"""
        return cls(operation="ADD", vector=vector, vector_001=vector_001)

    @classmethod
    def subtract(
        cls, vector: InputVector = None, vector_001: InputVector = None
    ) -> "VectorMath":
        """Create Vector Math with operation 'Subtract'. A - B"""
        return cls(operation="SUBTRACT", vector=vector, vector_001=vector_001)

    @classmethod
    def multiply(
        cls, vector: InputVector = None, vector_001: InputVector = None
    ) -> "VectorMath":
        """Create Vector Math with operation 'Multiply'. Entry-wise multiply"""
        return cls(operation="MULTIPLY", vector=vector, vector_001=vector_001)

    @classmethod
    def divide(
        cls, vector: InputVector = None, vector_001: InputVector = None
    ) -> "VectorMath":
        """Create Vector Math with operation 'Divide'. Entry-wise divide"""
        return cls(operation="DIVIDE", vector=vector, vector_001=vector_001)

    @classmethod
    def multiply_add(
        cls,
        vector: InputVector = None,
        vector_001: InputVector = None,
        vector_002: InputVector = None,
    ) -> "VectorMath":
        """Create Vector Math with operation 'Multiply Add'. A * B + C"""
        return cls(
            operation="MULTIPLY_ADD",
            vector=vector,
            vector_001=vector_001,
            vector_002=vector_002,
        )

    @classmethod
    def cross_product(
        cls, vector: InputVector = None, vector_001: InputVector = None
    ) -> "VectorMath":
        """Create Vector Math with operation 'Cross Product'. A cross B"""
        return cls(operation="CROSS_PRODUCT", vector=vector, vector_001=vector_001)

    @classmethod
    def project(
        cls, vector: InputVector = None, vector_001: InputVector = None
    ) -> "VectorMath":
        """Create Vector Math with operation 'Project'. Project A onto B"""
        return cls(operation="PROJECT", vector=vector, vector_001=vector_001)

    @classmethod
    def reflect(
        cls, vector: InputVector = None, vector_001: InputVector = None
    ) -> "VectorMath":
        """Create Vector Math with operation 'Reflect'. Reflect A around the normal B. B does not need to be normalized."""
        return cls(operation="REFLECT", vector=vector, vector_001=vector_001)

    @classmethod
    def refract(
        cls,
        vector: InputVector = None,
        vector_001: InputVector = None,
        scale: InputFloat = 1.0,
    ) -> "VectorMath":
        """Create Vector Math with operation 'Refract'. For a given incident vector A, surface normal B and ratio of indices of refraction, Ior, refract returns the refraction vector, R"""
        return cls(
            operation="REFRACT", vector=vector, vector_001=vector_001, scale=scale
        )

    @classmethod
    def faceforward(
        cls,
        vector: InputVector = None,
        vector_001: InputVector = None,
        vector_002: InputVector = None,
    ) -> "VectorMath":
        """Create Vector Math with operation 'Faceforward'. Orients a vector A to point away from a surface B as defined by its normal C. Returns (dot(B, C) < 0) ? A : -A"""
        return cls(
            operation="FACEFORWARD",
            vector=vector,
            vector_001=vector_001,
            vector_002=vector_002,
        )

    @classmethod
    def dot_product(
        cls, vector: InputVector = None, vector_001: InputVector = None
    ) -> "VectorMath":
        """Create Vector Math with operation 'Dot Product'. A dot B"""
        return cls(operation="DOT_PRODUCT", vector=vector, vector_001=vector_001)

    @classmethod
    def distance(
        cls, vector: InputVector = None, vector_001: InputVector = None
    ) -> "VectorMath":
        """Create Vector Math with operation 'Distance'. Distance between A and B"""
        return cls(operation="DISTANCE", vector=vector, vector_001=vector_001)

    @classmethod
    def length(cls, vector: InputVector = None) -> "VectorMath":
        """Create Vector Math with operation 'Length'. Length of A"""
        return cls(operation="LENGTH", vector=vector)

    @classmethod
    def scale(cls, vector: InputVector = None, scale: InputFloat = 1.0) -> "VectorMath":
        """Create Vector Math with operation 'Scale'. A multiplied by Scale"""
        return cls(operation="SCALE", vector=vector, scale=scale)

    @classmethod
    def normalize(cls, vector: InputVector = None) -> "VectorMath":
        """Create Vector Math with operation 'Normalize'. Normalize A"""
        return cls(operation="NORMALIZE", vector=vector)

    @classmethod
    def absolute(cls, vector: InputVector = None) -> "VectorMath":
        """Create Vector Math with operation 'Absolute'. Entry-wise absolute"""
        return cls(operation="ABSOLUTE", vector=vector)

    @classmethod
    def power(
        cls, vector: InputVector = None, vector_001: InputVector = None
    ) -> "VectorMath":
        """Create Vector Math with operation 'Power'. Entry-wise power"""
        return cls(operation="POWER", vector=vector, vector_001=vector_001)

    @classmethod
    def sign(cls, vector: InputVector = None) -> "VectorMath":
        """Create Vector Math with operation 'Sign'. Entry-wise sign"""
        return cls(operation="SIGN", vector=vector)

    @classmethod
    def minimum(
        cls, vector: InputVector = None, vector_001: InputVector = None
    ) -> "VectorMath":
        """Create Vector Math with operation 'Minimum'. Entry-wise minimum"""
        return cls(operation="MINIMUM", vector=vector, vector_001=vector_001)

    @classmethod
    def maximum(
        cls, vector: InputVector = None, vector_001: InputVector = None
    ) -> "VectorMath":
        """Create Vector Math with operation 'Maximum'. Entry-wise maximum"""
        return cls(operation="MAXIMUM", vector=vector, vector_001=vector_001)

    @classmethod
    def floor(cls, vector: InputVector = None) -> "VectorMath":
        """Create Vector Math with operation 'Floor'. Entry-wise floor"""
        return cls(operation="FLOOR", vector=vector)

    @classmethod
    def ceil(cls, vector: InputVector = None) -> "VectorMath":
        """Create Vector Math with operation 'Ceil'. Entry-wise ceil"""
        return cls(operation="CEIL", vector=vector)

    @classmethod
    def fraction(cls, vector: InputVector = None) -> "VectorMath":
        """Create Vector Math with operation 'Fraction'. The fraction part of A entry-wise"""
        return cls(operation="FRACTION", vector=vector)

    @classmethod
    def modulo(
        cls, vector: InputVector = None, vector_001: InputVector = None
    ) -> "VectorMath":
        """Create Vector Math with operation 'Modulo'. Entry-wise modulo using fmod(A,B)"""
        return cls(operation="MODULO", vector=vector, vector_001=vector_001)

    @classmethod
    def wrap(
        cls,
        vector: InputVector = None,
        vector_001: InputVector = None,
        vector_002: InputVector = None,
    ) -> "VectorMath":
        """Create Vector Math with operation 'Wrap'. Entry-wise wrap(A,B)"""
        return cls(
            operation="WRAP",
            vector=vector,
            vector_001=vector_001,
            vector_002=vector_002,
        )

    @classmethod
    def snap(
        cls, vector: InputVector = None, vector_001: InputVector = None
    ) -> "VectorMath":
        """Create Vector Math with operation 'Snap'. Round A to the largest integer multiple of B less than or equal A"""
        return cls(operation="SNAP", vector=vector, vector_001=vector_001)

    @classmethod
    def sine(cls, vector: InputVector = None) -> "VectorMath":
        """Create Vector Math with operation 'Sine'. Entry-wise sin(A)"""
        return cls(operation="SINE", vector=vector)

    @classmethod
    def cosine(cls, vector: InputVector = None) -> "VectorMath":
        """Create Vector Math with operation 'Cosine'. Entry-wise cos(A)"""
        return cls(operation="COSINE", vector=vector)

    @classmethod
    def tangent(cls, vector: InputVector = None) -> "VectorMath":
        """Create Vector Math with operation 'Tangent'. Entry-wise tan(A)"""
        return cls(operation="TANGENT", vector=vector)

    @property
    def i_vector(self) -> Socket:
        """Input socket: Vector"""
        return self.inputs.get("Vector")

    @property
    def i_vector_001(self) -> Socket:
        """Input socket: Vector"""
        return self.inputs.get("Vector_001")

    @property
    def i_vector_002(self) -> Socket:
        """Input socket: Vector"""
        return self.inputs.get("Vector_002")

    @property
    def i_scale(self) -> Socket:
        """Input socket: Scale"""
        return self.inputs.get("Scale")

    @property
    def o_vector(self) -> VectorSocket:
        """Output socket: Vector"""
        return self.outputs.get("Vector")

    @property
    def o_value(self) -> FloatSocket:
        """Output socket: Value"""
        return self.outputs.get("Value")

    @property
    def operation(
        self,
    ) -> Literal[
        "ADD",
        "SUBTRACT",
        "MULTIPLY",
        "DIVIDE",
        "MULTIPLY_ADD",
        "CROSS_PRODUCT",
        "PROJECT",
        "REFLECT",
        "REFRACT",
        "FACEFORWARD",
        "DOT_PRODUCT",
        "DISTANCE",
        "LENGTH",
        "SCALE",
        "NORMALIZE",
        "ABSOLUTE",
        "POWER",
        "SIGN",
        "MINIMUM",
        "MAXIMUM",
        "FLOOR",
        "CEIL",
        "FRACTION",
        "MODULO",
        "WRAP",
        "SNAP",
        "SINE",
        "COSINE",
        "TANGENT",
    ]:
        return self.node.operation

    @operation.setter
    def operation(
        self,
        value: Literal[
            "ADD",
            "SUBTRACT",
            "MULTIPLY",
            "DIVIDE",
            "MULTIPLY_ADD",
            "CROSS_PRODUCT",
            "PROJECT",
            "REFLECT",
            "REFRACT",
            "FACEFORWARD",
            "DOT_PRODUCT",
            "DISTANCE",
            "LENGTH",
            "SCALE",
            "NORMALIZE",
            "ABSOLUTE",
            "POWER",
            "SIGN",
            "MINIMUM",
            "MAXIMUM",
            "FLOOR",
            "CEIL",
            "FRACTION",
            "MODULO",
            "WRAP",
            "SNAP",
            "SINE",
            "COSINE",
            "TANGENT",
        ],
    ):
        self.node.operation = value


class VectorRotate(NodeBuilder):
    """
    Rotate a vector around a pivot point (center)
    """

    _bl_idname = "ShaderNodeVectorRotate"
    node: bpy.types.ShaderNodeVectorRotate

    def __init__(
        self,
        vector: InputVector = None,
        center: InputVector = None,
        axis: InputVector = None,
        angle: InputFloat = 0.0,
        rotation: InputVector = None,
        *,
        rotation_type: Literal[
            "AXIS_ANGLE", "X_AXIS", "Y_AXIS", "Z_AXIS", "EULER_XYZ"
        ] = "AXIS_ANGLE",
        invert: bool = False,
    ):
        super().__init__()
        key_args = {
            "Vector": vector,
            "Center": center,
            "Axis": axis,
            "Angle": angle,
            "Rotation": rotation,
        }
        self.rotation_type = rotation_type
        self.invert = invert
        self._establish_links(**key_args)

    @property
    def i_vector(self) -> Socket:
        """Input socket: Vector"""
        return self.inputs.get("Vector")

    @property
    def i_center(self) -> Socket:
        """Input socket: Center"""
        return self.inputs.get("Center")

    @property
    def i_axis(self) -> Socket:
        """Input socket: Axis"""
        return self.inputs.get("Axis")

    @property
    def i_angle(self) -> Socket:
        """Input socket: Angle"""
        return self.inputs.get("Angle")

    @property
    def i_rotation(self) -> Socket:
        """Input socket: Rotation"""
        return self.inputs.get("Rotation")

    @property
    def o_vector(self) -> VectorSocket:
        """Output socket: Vector"""
        return self.outputs.get("Vector")

    @property
    def rotation_type(
        self,
    ) -> Literal["AXIS_ANGLE", "X_AXIS", "Y_AXIS", "Z_AXIS", "EULER_XYZ"]:
        return self.node.rotation_type

    @rotation_type.setter
    def rotation_type(
        self, value: Literal["AXIS_ANGLE", "X_AXIS", "Y_AXIS", "Z_AXIS", "EULER_XYZ"]
    ):
        self.node.rotation_type = value

    @property
    def invert(self) -> bool:
        return self.node.invert

    @invert.setter
    def invert(self, value: bool):
        self.node.invert = value
