# Function reference {.doc .doc-index}

## Some functions

Functions to inspect docstrings.

| | |
| --- | --- |
| [nodes.geometry.input](nodes.geometry.input.qmd#nodebpy.nodes.geometry.input) |  |
| [nodes.geometry.attribute](nodes.geometry.attribute.qmd#nodebpy.nodes.geometry.attribute) |  |
| [nodes.geometry.color](nodes.geometry.color.qmd#nodebpy.nodes.geometry.color) |  |
| [nodes.geometry.converter](nodes.geometry.converter.qmd#nodebpy.nodes.geometry.converter) |  |
| [nodes.geometry.texture](nodes.geometry.texture.qmd#nodebpy.nodes.geometry.texture) |  |
| [nodes.geometry.grid](nodes.geometry.grid.qmd#nodebpy.nodes.geometry.grid) |  |
| [nodes.geometry.geometry](nodes.geometry.geometry.qmd#nodebpy.nodes.geometry.geometry) |  |
| [nodes.geometry.attribute](nodes.geometry.attribute.qmd#nodebpy.nodes.geometry.attribute) |  |
| [nodes.geometry.vector](nodes.geometry.vector.qmd#nodebpy.nodes.geometry.vector) |  |
| [nodes.geometry.manual](nodes.geometry.manual.qmd#nodebpy.nodes.geometry.manual) |  |
| [nodes.geometry.zone](nodes.geometry.zone.qmd#nodebpy.nodes.geometry.zone) |  |