# nodes.geometry.vector { #nodebpy.nodes.geometry.vector }

`nodes.geometry.vector`



## Classes

| Name | Description |
| --- | --- |
| [RadialTiling](#nodebpy.nodes.geometry.vector.RadialTiling) | Transform Coordinate System for Radial Tiling |
| [VectorCurves](#nodebpy.nodes.geometry.vector.VectorCurves) | Map input vector components with curves |
| [VectorMath](#nodebpy.nodes.geometry.vector.VectorMath) | Perform vector math operation |
| [VectorRotate](#nodebpy.nodes.geometry.vector.VectorRotate) | Rotate a vector around a pivot point (center) |

### RadialTiling { #nodebpy.nodes.geometry.vector.RadialTiling }

```python
nodes.geometry.vector.RadialTiling(
    vector=None,
    sides=5.0,
    roundness=0.0,
    *,
    normalize=False,
)
```

Transform Coordinate System for Radial Tiling

#### Attributes

| Name | Description |
| --- | --- |
| [i_roundness](#nodebpy.nodes.geometry.vector.RadialTiling.i_roundness) | Input socket: Roundness |
| [i_sides](#nodebpy.nodes.geometry.vector.RadialTiling.i_sides) | Input socket: Sides |
| [i_vector](#nodebpy.nodes.geometry.vector.RadialTiling.i_vector) | Input socket: Vector |
| [name](#nodebpy.nodes.geometry.vector.RadialTiling.name) |  |
| [node](#nodebpy.nodes.geometry.vector.RadialTiling.node) |  |
| [normalize](#nodebpy.nodes.geometry.vector.RadialTiling.normalize) |  |
| [o_segment_coordinates](#nodebpy.nodes.geometry.vector.RadialTiling.o_segment_coordinates) | Output socket: Segment Coordinates |
| [o_segment_id](#nodebpy.nodes.geometry.vector.RadialTiling.o_segment_id) | Output socket: Segment ID |
| [o_segment_rotation](#nodebpy.nodes.geometry.vector.RadialTiling.o_segment_rotation) | Output socket: Segment Rotation |
| [o_segment_width](#nodebpy.nodes.geometry.vector.RadialTiling.o_segment_width) | Output socket: Segment Width |
| [tree](#nodebpy.nodes.geometry.vector.RadialTiling.tree) |  |
| [type](#nodebpy.nodes.geometry.vector.RadialTiling.type) |  |

### VectorCurves { #nodebpy.nodes.geometry.vector.VectorCurves }

```python
nodes.geometry.vector.VectorCurves(fac=1.0, vector=None)
```

Map input vector components with curves

#### Attributes

| Name | Description |
| --- | --- |
| [i_fac](#nodebpy.nodes.geometry.vector.VectorCurves.i_fac) | Input socket: Factor |
| [i_vector](#nodebpy.nodes.geometry.vector.VectorCurves.i_vector) | Input socket: Vector |
| [name](#nodebpy.nodes.geometry.vector.VectorCurves.name) |  |
| [node](#nodebpy.nodes.geometry.vector.VectorCurves.node) |  |
| [o_vector](#nodebpy.nodes.geometry.vector.VectorCurves.o_vector) | Output socket: Vector |
| [tree](#nodebpy.nodes.geometry.vector.VectorCurves.tree) |  |
| [type](#nodebpy.nodes.geometry.vector.VectorCurves.type) |  |

### VectorMath { #nodebpy.nodes.geometry.vector.VectorMath }

```python
nodes.geometry.vector.VectorMath(
    vector=None,
    vector_001=None,
    vector_002=None,
    scale=1.0,
    *,
    operation='ADD',
)
```

Perform vector math operation

#### Attributes

| Name | Description |
| --- | --- |
| [i_scale](#nodebpy.nodes.geometry.vector.VectorMath.i_scale) | Input socket: Scale |
| [i_vector](#nodebpy.nodes.geometry.vector.VectorMath.i_vector) | Input socket: Vector |
| [i_vector_001](#nodebpy.nodes.geometry.vector.VectorMath.i_vector_001) | Input socket: Vector |
| [i_vector_002](#nodebpy.nodes.geometry.vector.VectorMath.i_vector_002) | Input socket: Vector |
| [name](#nodebpy.nodes.geometry.vector.VectorMath.name) |  |
| [node](#nodebpy.nodes.geometry.vector.VectorMath.node) |  |
| [o_value](#nodebpy.nodes.geometry.vector.VectorMath.o_value) | Output socket: Value |
| [o_vector](#nodebpy.nodes.geometry.vector.VectorMath.o_vector) | Output socket: Vector |
| [operation](#nodebpy.nodes.geometry.vector.VectorMath.operation) |  |
| [tree](#nodebpy.nodes.geometry.vector.VectorMath.tree) |  |
| [type](#nodebpy.nodes.geometry.vector.VectorMath.type) |  |

#### Methods

| Name | Description |
| --- | --- |
| [absolute](#nodebpy.nodes.geometry.vector.VectorMath.absolute) | Create Vector Math with operation 'Absolute'. |
| [add](#nodebpy.nodes.geometry.vector.VectorMath.add) | Create Vector Math with operation 'Add'. |
| [ceil](#nodebpy.nodes.geometry.vector.VectorMath.ceil) | Create Vector Math with operation 'Ceil'. |
| [cosine](#nodebpy.nodes.geometry.vector.VectorMath.cosine) | Create Vector Math with operation 'Cosine'. |
| [cross_product](#nodebpy.nodes.geometry.vector.VectorMath.cross_product) | Create Vector Math with operation 'Cross Product'. |
| [distance](#nodebpy.nodes.geometry.vector.VectorMath.distance) | Create Vector Math with operation 'Distance'. |
| [divide](#nodebpy.nodes.geometry.vector.VectorMath.divide) | Create Vector Math with operation 'Divide'. |
| [dot_product](#nodebpy.nodes.geometry.vector.VectorMath.dot_product) | Create Vector Math with operation 'Dot Product'. |
| [faceforward](#nodebpy.nodes.geometry.vector.VectorMath.faceforward) | Create Vector Math with operation 'Faceforward'. |
| [floor](#nodebpy.nodes.geometry.vector.VectorMath.floor) | Create Vector Math with operation 'Floor'. |
| [fraction](#nodebpy.nodes.geometry.vector.VectorMath.fraction) | Create Vector Math with operation 'Fraction'. |
| [length](#nodebpy.nodes.geometry.vector.VectorMath.length) | Create Vector Math with operation 'Length'. |
| [maximum](#nodebpy.nodes.geometry.vector.VectorMath.maximum) | Create Vector Math with operation 'Maximum'. |
| [minimum](#nodebpy.nodes.geometry.vector.VectorMath.minimum) | Create Vector Math with operation 'Minimum'. |
| [modulo](#nodebpy.nodes.geometry.vector.VectorMath.modulo) | Create Vector Math with operation 'Modulo'. |
| [multiply](#nodebpy.nodes.geometry.vector.VectorMath.multiply) | Create Vector Math with operation 'Multiply'. |
| [multiply_add](#nodebpy.nodes.geometry.vector.VectorMath.multiply_add) | Create Vector Math with operation 'Multiply Add'. |
| [normalize](#nodebpy.nodes.geometry.vector.VectorMath.normalize) | Create Vector Math with operation 'Normalize'. |
| [power](#nodebpy.nodes.geometry.vector.VectorMath.power) | Create Vector Math with operation 'Power'. |
| [project](#nodebpy.nodes.geometry.vector.VectorMath.project) | Create Vector Math with operation 'Project'. |
| [reflect](#nodebpy.nodes.geometry.vector.VectorMath.reflect) | Create Vector Math with operation 'Reflect'. |
| [refract](#nodebpy.nodes.geometry.vector.VectorMath.refract) | Create Vector Math with operation 'Refract'. |
| [scale](#nodebpy.nodes.geometry.vector.VectorMath.scale) | Create Vector Math with operation 'Scale'. |
| [sign](#nodebpy.nodes.geometry.vector.VectorMath.sign) | Create Vector Math with operation 'Sign'. |
| [sine](#nodebpy.nodes.geometry.vector.VectorMath.sine) | Create Vector Math with operation 'Sine'. |
| [snap](#nodebpy.nodes.geometry.vector.VectorMath.snap) | Create Vector Math with operation 'Snap'. |
| [subtract](#nodebpy.nodes.geometry.vector.VectorMath.subtract) | Create Vector Math with operation 'Subtract'. |
| [tangent](#nodebpy.nodes.geometry.vector.VectorMath.tangent) | Create Vector Math with operation 'Tangent'. |
| [wrap](#nodebpy.nodes.geometry.vector.VectorMath.wrap) | Create Vector Math with operation 'Wrap'. |

##### absolute { #nodebpy.nodes.geometry.vector.VectorMath.absolute }

```python
nodes.geometry.vector.VectorMath.absolute(vector=None)
```

Create Vector Math with operation 'Absolute'.

##### add { #nodebpy.nodes.geometry.vector.VectorMath.add }

```python
nodes.geometry.vector.VectorMath.add(vector=None, vector_001=None)
```

Create Vector Math with operation 'Add'.

##### ceil { #nodebpy.nodes.geometry.vector.VectorMath.ceil }

```python
nodes.geometry.vector.VectorMath.ceil(vector=None)
```

Create Vector Math with operation 'Ceil'.

##### cosine { #nodebpy.nodes.geometry.vector.VectorMath.cosine }

```python
nodes.geometry.vector.VectorMath.cosine(vector=None)
```

Create Vector Math with operation 'Cosine'.

##### cross_product { #nodebpy.nodes.geometry.vector.VectorMath.cross_product }

```python
nodes.geometry.vector.VectorMath.cross_product(vector=None, vector_001=None)
```

Create Vector Math with operation 'Cross Product'.

##### distance { #nodebpy.nodes.geometry.vector.VectorMath.distance }

```python
nodes.geometry.vector.VectorMath.distance(vector=None, vector_001=None)
```

Create Vector Math with operation 'Distance'.

##### divide { #nodebpy.nodes.geometry.vector.VectorMath.divide }

```python
nodes.geometry.vector.VectorMath.divide(vector=None, vector_001=None)
```

Create Vector Math with operation 'Divide'.

##### dot_product { #nodebpy.nodes.geometry.vector.VectorMath.dot_product }

```python
nodes.geometry.vector.VectorMath.dot_product(vector=None, vector_001=None)
```

Create Vector Math with operation 'Dot Product'.

##### faceforward { #nodebpy.nodes.geometry.vector.VectorMath.faceforward }

```python
nodes.geometry.vector.VectorMath.faceforward(
    vector=None,
    vector_001=None,
    vector_002=None,
)
```

Create Vector Math with operation 'Faceforward'.

##### floor { #nodebpy.nodes.geometry.vector.VectorMath.floor }

```python
nodes.geometry.vector.VectorMath.floor(vector=None)
```

Create Vector Math with operation 'Floor'.

##### fraction { #nodebpy.nodes.geometry.vector.VectorMath.fraction }

```python
nodes.geometry.vector.VectorMath.fraction(vector=None)
```

Create Vector Math with operation 'Fraction'.

##### length { #nodebpy.nodes.geometry.vector.VectorMath.length }

```python
nodes.geometry.vector.VectorMath.length(vector=None)
```

Create Vector Math with operation 'Length'.

##### maximum { #nodebpy.nodes.geometry.vector.VectorMath.maximum }

```python
nodes.geometry.vector.VectorMath.maximum(vector=None, vector_001=None)
```

Create Vector Math with operation 'Maximum'.

##### minimum { #nodebpy.nodes.geometry.vector.VectorMath.minimum }

```python
nodes.geometry.vector.VectorMath.minimum(vector=None, vector_001=None)
```

Create Vector Math with operation 'Minimum'.

##### modulo { #nodebpy.nodes.geometry.vector.VectorMath.modulo }

```python
nodes.geometry.vector.VectorMath.modulo(vector=None, vector_001=None)
```

Create Vector Math with operation 'Modulo'.

##### multiply { #nodebpy.nodes.geometry.vector.VectorMath.multiply }

```python
nodes.geometry.vector.VectorMath.multiply(vector=None, vector_001=None)
```

Create Vector Math with operation 'Multiply'.

##### multiply_add { #nodebpy.nodes.geometry.vector.VectorMath.multiply_add }

```python
nodes.geometry.vector.VectorMath.multiply_add(
    vector=None,
    vector_001=None,
    vector_002=None,
)
```

Create Vector Math with operation 'Multiply Add'.

##### normalize { #nodebpy.nodes.geometry.vector.VectorMath.normalize }

```python
nodes.geometry.vector.VectorMath.normalize(vector=None)
```

Create Vector Math with operation 'Normalize'.

##### power { #nodebpy.nodes.geometry.vector.VectorMath.power }

```python
nodes.geometry.vector.VectorMath.power(vector=None, vector_001=None)
```

Create Vector Math with operation 'Power'.

##### project { #nodebpy.nodes.geometry.vector.VectorMath.project }

```python
nodes.geometry.vector.VectorMath.project(vector=None, vector_001=None)
```

Create Vector Math with operation 'Project'.

##### reflect { #nodebpy.nodes.geometry.vector.VectorMath.reflect }

```python
nodes.geometry.vector.VectorMath.reflect(vector=None, vector_001=None)
```

Create Vector Math with operation 'Reflect'.

##### refract { #nodebpy.nodes.geometry.vector.VectorMath.refract }

```python
nodes.geometry.vector.VectorMath.refract(
    vector=None,
    vector_001=None,
    scale=1.0,
)
```

Create Vector Math with operation 'Refract'.

##### scale { #nodebpy.nodes.geometry.vector.VectorMath.scale }

```python
nodes.geometry.vector.VectorMath.scale(vector=None, scale=1.0)
```

Create Vector Math with operation 'Scale'.

##### sign { #nodebpy.nodes.geometry.vector.VectorMath.sign }

```python
nodes.geometry.vector.VectorMath.sign(vector=None)
```

Create Vector Math with operation 'Sign'.

##### sine { #nodebpy.nodes.geometry.vector.VectorMath.sine }

```python
nodes.geometry.vector.VectorMath.sine(vector=None)
```

Create Vector Math with operation 'Sine'.

##### snap { #nodebpy.nodes.geometry.vector.VectorMath.snap }

```python
nodes.geometry.vector.VectorMath.snap(vector=None, vector_001=None)
```

Create Vector Math with operation 'Snap'.

##### subtract { #nodebpy.nodes.geometry.vector.VectorMath.subtract }

```python
nodes.geometry.vector.VectorMath.subtract(vector=None, vector_001=None)
```

Create Vector Math with operation 'Subtract'.

##### tangent { #nodebpy.nodes.geometry.vector.VectorMath.tangent }

```python
nodes.geometry.vector.VectorMath.tangent(vector=None)
```

Create Vector Math with operation 'Tangent'.

##### wrap { #nodebpy.nodes.geometry.vector.VectorMath.wrap }

```python
nodes.geometry.vector.VectorMath.wrap(
    vector=None,
    vector_001=None,
    vector_002=None,
)
```

Create Vector Math with operation 'Wrap'.

### VectorRotate { #nodebpy.nodes.geometry.vector.VectorRotate }

```python
nodes.geometry.vector.VectorRotate(
    vector=None,
    center=None,
    axis=None,
    angle=0.0,
    rotation=None,
    *,
    rotation_type='AXIS_ANGLE',
    invert=False,
)
```

Rotate a vector around a pivot point (center)

#### Attributes

| Name | Description |
| --- | --- |
| [i_angle](#nodebpy.nodes.geometry.vector.VectorRotate.i_angle) | Input socket: Angle |
| [i_axis](#nodebpy.nodes.geometry.vector.VectorRotate.i_axis) | Input socket: Axis |
| [i_center](#nodebpy.nodes.geometry.vector.VectorRotate.i_center) | Input socket: Center |
| [i_rotation](#nodebpy.nodes.geometry.vector.VectorRotate.i_rotation) | Input socket: Rotation |
| [i_vector](#nodebpy.nodes.geometry.vector.VectorRotate.i_vector) | Input socket: Vector |
| [invert](#nodebpy.nodes.geometry.vector.VectorRotate.invert) |  |
| [name](#nodebpy.nodes.geometry.vector.VectorRotate.name) |  |
| [node](#nodebpy.nodes.geometry.vector.VectorRotate.node) |  |
| [o_vector](#nodebpy.nodes.geometry.vector.VectorRotate.o_vector) | Output socket: Vector |
| [rotation_type](#nodebpy.nodes.geometry.vector.VectorRotate.rotation_type) |  |
| [tree](#nodebpy.nodes.geometry.vector.VectorRotate.tree) |  |
| [type](#nodebpy.nodes.geometry.vector.VectorRotate.type) |  |