# nodes.geometry.attribute { #nodebpy.nodes.geometry.attribute }

`nodes.geometry.attribute`



## Classes

| Name | Description |
| --- | --- |
| [BlurAttribute](#nodebpy.nodes.geometry.attribute.BlurAttribute) | Mix attribute values of neighboring elements |
| [DomainSize](#nodebpy.nodes.geometry.attribute.DomainSize) | Retrieve the number of elements in a geometry for each attribute domain |
| [RemoveNamedAttribute](#nodebpy.nodes.geometry.attribute.RemoveNamedAttribute) | Delete an attribute with a specified name from a geometry. Typically used to optimize performance |
| [StoreNamedAttribute](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute) | Store the result of a field on a geometry as an attribute with the specified name |

### BlurAttribute { #nodebpy.nodes.geometry.attribute.BlurAttribute }

```python
nodes.geometry.attribute.BlurAttribute(
    value=0.0,
    iterations=1,
    weight=1.0,
    *,
    data_type='FLOAT',
)
```

Mix attribute values of neighboring elements

#### Attributes

| Name | Description |
| --- | --- |
| [data_type](#nodebpy.nodes.geometry.attribute.BlurAttribute.data_type) |  |
| [i_iterations](#nodebpy.nodes.geometry.attribute.BlurAttribute.i_iterations) | Input socket: Iterations |
| [i_value](#nodebpy.nodes.geometry.attribute.BlurAttribute.i_value) | Input socket: Value |
| [i_weight](#nodebpy.nodes.geometry.attribute.BlurAttribute.i_weight) | Input socket: Weight |
| [name](#nodebpy.nodes.geometry.attribute.BlurAttribute.name) |  |
| [node](#nodebpy.nodes.geometry.attribute.BlurAttribute.node) |  |
| [o_value](#nodebpy.nodes.geometry.attribute.BlurAttribute.o_value) | Output socket: Value |
| [tree](#nodebpy.nodes.geometry.attribute.BlurAttribute.tree) |  |
| [type](#nodebpy.nodes.geometry.attribute.BlurAttribute.type) |  |

#### Methods

| Name | Description |
| --- | --- |
| [color](#nodebpy.nodes.geometry.attribute.BlurAttribute.color) | Create Blur Attribute with operation 'Color'. |
| [float](#nodebpy.nodes.geometry.attribute.BlurAttribute.float) | Create Blur Attribute with operation 'Float'. |
| [integer](#nodebpy.nodes.geometry.attribute.BlurAttribute.integer) | Create Blur Attribute with operation 'Integer'. |
| [vector](#nodebpy.nodes.geometry.attribute.BlurAttribute.vector) | Create Blur Attribute with operation 'Vector'. |

##### color { #nodebpy.nodes.geometry.attribute.BlurAttribute.color }

```python
nodes.geometry.attribute.BlurAttribute.color(
    value=None,
    iterations=1,
    weight=1.0,
)
```

Create Blur Attribute with operation 'Color'.

##### float { #nodebpy.nodes.geometry.attribute.BlurAttribute.float }

```python
nodes.geometry.attribute.BlurAttribute.float(
    value=0.0,
    iterations=1,
    weight=1.0,
)
```

Create Blur Attribute with operation 'Float'.

##### integer { #nodebpy.nodes.geometry.attribute.BlurAttribute.integer }

```python
nodes.geometry.attribute.BlurAttribute.integer(
    value=0,
    iterations=1,
    weight=1.0,
)
```

Create Blur Attribute with operation 'Integer'.

##### vector { #nodebpy.nodes.geometry.attribute.BlurAttribute.vector }

```python
nodes.geometry.attribute.BlurAttribute.vector(
    value=None,
    iterations=1,
    weight=1.0,
)
```

Create Blur Attribute with operation 'Vector'.

### DomainSize { #nodebpy.nodes.geometry.attribute.DomainSize }

```python
nodes.geometry.attribute.DomainSize(geometry=None, *, component='MESH')
```

Retrieve the number of elements in a geometry for each attribute domain

#### Attributes

| Name | Description |
| --- | --- |
| [component](#nodebpy.nodes.geometry.attribute.DomainSize.component) |  |
| [i_geometry](#nodebpy.nodes.geometry.attribute.DomainSize.i_geometry) | Input socket: Geometry |
| [name](#nodebpy.nodes.geometry.attribute.DomainSize.name) |  |
| [node](#nodebpy.nodes.geometry.attribute.DomainSize.node) |  |
| [o_edge_count](#nodebpy.nodes.geometry.attribute.DomainSize.o_edge_count) | Output socket: Edge Count |
| [o_face_corner_count](#nodebpy.nodes.geometry.attribute.DomainSize.o_face_corner_count) | Output socket: Face Corner Count |
| [o_face_count](#nodebpy.nodes.geometry.attribute.DomainSize.o_face_count) | Output socket: Face Count |
| [o_instance_count](#nodebpy.nodes.geometry.attribute.DomainSize.o_instance_count) | Output socket: Instance Count |
| [o_layer_count](#nodebpy.nodes.geometry.attribute.DomainSize.o_layer_count) | Output socket: Layer Count |
| [o_point_count](#nodebpy.nodes.geometry.attribute.DomainSize.o_point_count) | Output socket: Point Count |
| [o_spline_count](#nodebpy.nodes.geometry.attribute.DomainSize.o_spline_count) | Output socket: Spline Count |
| [tree](#nodebpy.nodes.geometry.attribute.DomainSize.tree) |  |
| [type](#nodebpy.nodes.geometry.attribute.DomainSize.type) |  |

### RemoveNamedAttribute { #nodebpy.nodes.geometry.attribute.RemoveNamedAttribute }

```python
nodes.geometry.attribute.RemoveNamedAttribute(
    geometry=None,
    pattern_mode='Exact',
    name='',
)
```

Delete an attribute with a specified name from a geometry. Typically used to optimize performance

#### Attributes

| Name | Description |
| --- | --- |
| [i_geometry](#nodebpy.nodes.geometry.attribute.RemoveNamedAttribute.i_geometry) | Input socket: Geometry |
| [i_name](#nodebpy.nodes.geometry.attribute.RemoveNamedAttribute.i_name) | Input socket: Name |
| [i_pattern_mode](#nodebpy.nodes.geometry.attribute.RemoveNamedAttribute.i_pattern_mode) | Input socket: Pattern Mode |
| [name](#nodebpy.nodes.geometry.attribute.RemoveNamedAttribute.name) |  |
| [node](#nodebpy.nodes.geometry.attribute.RemoveNamedAttribute.node) |  |
| [o_geometry](#nodebpy.nodes.geometry.attribute.RemoveNamedAttribute.o_geometry) | Output socket: Geometry |
| [tree](#nodebpy.nodes.geometry.attribute.RemoveNamedAttribute.tree) |  |
| [type](#nodebpy.nodes.geometry.attribute.RemoveNamedAttribute.type) |  |

### StoreNamedAttribute { #nodebpy.nodes.geometry.attribute.StoreNamedAttribute }

```python
nodes.geometry.attribute.StoreNamedAttribute(
    geometry=None,
    selection=True,
    name='',
    value=0.0,
    *,
    data_type='FLOAT',
    domain='POINT',
)
```

Store the result of a field on a geometry as an attribute with the specified name

#### Attributes

| Name | Description |
| --- | --- |
| [data_type](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.data_type) |  |
| [domain](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.domain) |  |
| [i_geometry](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.i_geometry) | Input socket: Geometry |
| [i_name](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.i_name) | Input socket: Name |
| [i_selection](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.i_selection) | Input socket: Selection |
| [i_value](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.i_value) | Input socket: Value |
| [name](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.name) |  |
| [node](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.node) |  |
| [o_geometry](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.o_geometry) | Output socket: Geometry |
| [tree](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.tree) |  |
| [type](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.type) |  |

#### Methods

| Name | Description |
| --- | --- |
| [boolean](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.boolean) | Create Store Named Attribute with operation 'Boolean'. |
| [byte_color](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.byte_color) | Create Store Named Attribute with operation 'Byte Color'. |
| [color](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.color) | Create Store Named Attribute with operation 'Color'. |
| [edge](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.edge) | Create Store Named Attribute with operation 'Edge'. |
| [face](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.face) | Create Store Named Attribute with operation 'Face'. |
| [face_corner](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.face_corner) | Create Store Named Attribute with operation 'Face Corner'. |
| [float](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.float) | Create Store Named Attribute with operation 'Float'. |
| [instance](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.instance) | Create Store Named Attribute with operation 'Instance'. |
| [int8](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.int8) | Create Store Named Attribute with operation '8-Bit Integer'. |
| [integer](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.integer) | Create Store Named Attribute with operation 'Integer'. |
| [layer](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.layer) | Create Store Named Attribute with operation 'Layer'. |
| [matrix](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.matrix) | Create Store Named Attribute with operation '4x4 Matrix'. |
| [point](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.point) | Create Store Named Attribute with operation 'Point'. |
| [quaternion](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.quaternion) | Create Store Named Attribute with operation 'Quaternion'. |
| [spline](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.spline) | Create Store Named Attribute with operation 'Spline'. |
| [vector](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.vector) | Create Store Named Attribute with operation 'Vector'. |
| [vector2](#nodebpy.nodes.geometry.attribute.StoreNamedAttribute.vector2) | Create Store Named Attribute with operation '2D Vector'. |

##### boolean { #nodebpy.nodes.geometry.attribute.StoreNamedAttribute.boolean }

```python
nodes.geometry.attribute.StoreNamedAttribute.boolean(
    geometry=None,
    selection=True,
    name='',
    value=False,
)
```

Create Store Named Attribute with operation 'Boolean'.

##### byte_color { #nodebpy.nodes.geometry.attribute.StoreNamedAttribute.byte_color }

```python
nodes.geometry.attribute.StoreNamedAttribute.byte_color(
    geometry=None,
    selection=True,
    name='',
    value=None,
)
```

Create Store Named Attribute with operation 'Byte Color'.

##### color { #nodebpy.nodes.geometry.attribute.StoreNamedAttribute.color }

```python
nodes.geometry.attribute.StoreNamedAttribute.color(
    geometry=None,
    selection=True,
    name='',
    value=None,
)
```

Create Store Named Attribute with operation 'Color'.

##### edge { #nodebpy.nodes.geometry.attribute.StoreNamedAttribute.edge }

```python
nodes.geometry.attribute.StoreNamedAttribute.edge(
    geometry=None,
    selection=True,
    name='',
    value=None,
)
```

Create Store Named Attribute with operation 'Edge'.

##### face { #nodebpy.nodes.geometry.attribute.StoreNamedAttribute.face }

```python
nodes.geometry.attribute.StoreNamedAttribute.face(
    geometry=None,
    selection=True,
    name='',
    value=None,
)
```

Create Store Named Attribute with operation 'Face'.

##### face_corner { #nodebpy.nodes.geometry.attribute.StoreNamedAttribute.face_corner }

```python
nodes.geometry.attribute.StoreNamedAttribute.face_corner(
    geometry=None,
    selection=True,
    name='',
    value=None,
)
```

Create Store Named Attribute with operation 'Face Corner'.

##### float { #nodebpy.nodes.geometry.attribute.StoreNamedAttribute.float }

```python
nodes.geometry.attribute.StoreNamedAttribute.float(
    geometry=None,
    selection=True,
    name='',
    value=0.0,
)
```

Create Store Named Attribute with operation 'Float'.

##### instance { #nodebpy.nodes.geometry.attribute.StoreNamedAttribute.instance }

```python
nodes.geometry.attribute.StoreNamedAttribute.instance(
    geometry=None,
    selection=True,
    name='',
    value=None,
)
```

Create Store Named Attribute with operation 'Instance'.

##### int8 { #nodebpy.nodes.geometry.attribute.StoreNamedAttribute.int8 }

```python
nodes.geometry.attribute.StoreNamedAttribute.int8(
    geometry=None,
    selection=True,
    name='',
    value=0,
)
```

Create Store Named Attribute with operation '8-Bit Integer'.

##### integer { #nodebpy.nodes.geometry.attribute.StoreNamedAttribute.integer }

```python
nodes.geometry.attribute.StoreNamedAttribute.integer(
    geometry=None,
    selection=True,
    name='',
    value=0,
)
```

Create Store Named Attribute with operation 'Integer'.

##### layer { #nodebpy.nodes.geometry.attribute.StoreNamedAttribute.layer }

```python
nodes.geometry.attribute.StoreNamedAttribute.layer(
    geometry=None,
    selection=True,
    name='',
    value=None,
)
```

Create Store Named Attribute with operation 'Layer'.

##### matrix { #nodebpy.nodes.geometry.attribute.StoreNamedAttribute.matrix }

```python
nodes.geometry.attribute.StoreNamedAttribute.matrix(
    geometry=None,
    selection=True,
    name='',
    value=None,
)
```

Create Store Named Attribute with operation '4x4 Matrix'.

##### point { #nodebpy.nodes.geometry.attribute.StoreNamedAttribute.point }

```python
nodes.geometry.attribute.StoreNamedAttribute.point(
    geometry=None,
    selection=True,
    name='',
    value=None,
)
```

Create Store Named Attribute with operation 'Point'.

##### quaternion { #nodebpy.nodes.geometry.attribute.StoreNamedAttribute.quaternion }

```python
nodes.geometry.attribute.StoreNamedAttribute.quaternion(
    geometry=None,
    selection=True,
    name='',
    value=None,
)
```

Create Store Named Attribute with operation 'Quaternion'.

##### spline { #nodebpy.nodes.geometry.attribute.StoreNamedAttribute.spline }

```python
nodes.geometry.attribute.StoreNamedAttribute.spline(
    geometry=None,
    selection=True,
    name='',
    value=None,
)
```

Create Store Named Attribute with operation 'Spline'.

##### vector { #nodebpy.nodes.geometry.attribute.StoreNamedAttribute.vector }

```python
nodes.geometry.attribute.StoreNamedAttribute.vector(
    geometry=None,
    selection=True,
    name='',
    value=None,
)
```

Create Store Named Attribute with operation 'Vector'.

##### vector2 { #nodebpy.nodes.geometry.attribute.StoreNamedAttribute.vector2 }

```python
nodes.geometry.attribute.StoreNamedAttribute.vector2(
    geometry=None,
    selection=True,
    name='',
    value=None,
)
```

Create Store Named Attribute with operation '2D Vector'.