# nodes.geometry.color { #nodebpy.nodes.geometry.color }

`nodes.geometry.color`



## Classes

| Name | Description |
| --- | --- |
| [Gamma](#nodebpy.nodes.geometry.color.Gamma) | Apply a gamma correction |
| [RgbCurves](#nodebpy.nodes.geometry.color.RgbCurves) | Apply color corrections for each color channel |

### Gamma { #nodebpy.nodes.geometry.color.Gamma }

```python
nodes.geometry.color.Gamma(color=None, gamma=1.0)
```

Apply a gamma correction

#### Attributes

| Name | Description |
| --- | --- |
| [i_color](#nodebpy.nodes.geometry.color.Gamma.i_color) | Input socket: Color |
| [i_gamma](#nodebpy.nodes.geometry.color.Gamma.i_gamma) | Input socket: Gamma |
| [name](#nodebpy.nodes.geometry.color.Gamma.name) |  |
| [node](#nodebpy.nodes.geometry.color.Gamma.node) |  |
| [o_color](#nodebpy.nodes.geometry.color.Gamma.o_color) | Output socket: Color |
| [tree](#nodebpy.nodes.geometry.color.Gamma.tree) |  |
| [type](#nodebpy.nodes.geometry.color.Gamma.type) |  |

### RgbCurves { #nodebpy.nodes.geometry.color.RgbCurves }

```python
nodes.geometry.color.RgbCurves(fac=1.0, color=None)
```

Apply color corrections for each color channel

#### Attributes

| Name | Description |
| --- | --- |
| [i_color](#nodebpy.nodes.geometry.color.RgbCurves.i_color) | Input socket: Color |
| [i_fac](#nodebpy.nodes.geometry.color.RgbCurves.i_fac) | Input socket: Factor |
| [name](#nodebpy.nodes.geometry.color.RgbCurves.name) |  |
| [node](#nodebpy.nodes.geometry.color.RgbCurves.node) |  |
| [o_color](#nodebpy.nodes.geometry.color.RgbCurves.o_color) | Output socket: Color |
| [tree](#nodebpy.nodes.geometry.color.RgbCurves.tree) |  |
| [type](#nodebpy.nodes.geometry.color.RgbCurves.type) |  |