# nodes.geometry.converter { #nodebpy.nodes.geometry.converter }

`nodes.geometry.converter`



## Classes

| Name | Description |
| --- | --- |
| [AlignRotationToVector](#nodebpy.nodes.geometry.converter.AlignRotationToVector) | Orient a rotation along the given direction |
| [AxesToRotation](#nodebpy.nodes.geometry.converter.AxesToRotation) | Create a rotation from a primary and (ideally orthogonal) secondary axis |
| [AxisAngleToRotation](#nodebpy.nodes.geometry.converter.AxisAngleToRotation) | Build a rotation from an axis and a rotation around that axis |
| [BitMath](#nodebpy.nodes.geometry.converter.BitMath) | Perform bitwise operations on 32-bit integers |
| [Blackbody](#nodebpy.nodes.geometry.converter.Blackbody) | Convert a blackbody temperature to an RGB value |
| [BooleanMath](#nodebpy.nodes.geometry.converter.BooleanMath) | Perform a logical operation on the given boolean inputs |
| [Clamp](#nodebpy.nodes.geometry.converter.Clamp) | Clamp a value between a minimum and a maximum |
| [ColorRamp](#nodebpy.nodes.geometry.converter.ColorRamp) | Map values to colors with the use of a gradient |
| [CombineBundle](#nodebpy.nodes.geometry.converter.CombineBundle) | Combine multiple socket values into one. |
| [CombineColor](#nodebpy.nodes.geometry.converter.CombineColor) | Combine four channels into a single color, based on a particular color model |
| [CombineMatrix](#nodebpy.nodes.geometry.converter.CombineMatrix) | Construct a 4x4 matrix from its individual values |
| [CombineTransform](#nodebpy.nodes.geometry.converter.CombineTransform) | Combine a translation vector, a rotation, and a scale vector into a transformation matrix |
| [CombineXYZ](#nodebpy.nodes.geometry.converter.CombineXYZ) | Create a vector from X, Y, and Z components |
| [EulerToRotation](#nodebpy.nodes.geometry.converter.EulerToRotation) | Build a rotation from separate angles around each axis |
| [FindInString](#nodebpy.nodes.geometry.converter.FindInString) | Find the number of times a given string occurs in another string and the position of the first match |
| [FloatCurve](#nodebpy.nodes.geometry.converter.FloatCurve) | Map an input float to a curve and outputs a float value |
| [FloatToInteger](#nodebpy.nodes.geometry.converter.FloatToInteger) | Convert the given floating-point number to an integer, with a choice of methods |
| [HashValue](#nodebpy.nodes.geometry.converter.HashValue) | Generate a randomized integer using the given input value as a seed |
| [IndexOfNearest](#nodebpy.nodes.geometry.converter.IndexOfNearest) | Find the nearest element in a group. Similar to the "Sample Nearest" node |
| [IntegerMath](#nodebpy.nodes.geometry.converter.IntegerMath) | Perform various math operations on the given integer inputs |
| [InvertMatrix](#nodebpy.nodes.geometry.converter.InvertMatrix) | Compute the inverse of the given matrix, if one exists |
| [InvertRotation](#nodebpy.nodes.geometry.converter.InvertRotation) | Compute the inverse of the given rotation |
| [JoinBundle](#nodebpy.nodes.geometry.converter.JoinBundle) | Join multiple bundles together |
| [MapRange](#nodebpy.nodes.geometry.converter.MapRange) | Remap a value from a range to a target range |
| [MatchString](#nodebpy.nodes.geometry.converter.MatchString) | Check if a given string exists within another string |
| [Math](#nodebpy.nodes.geometry.converter.Math) | Perform math operations |
| [MatrixDeterminant](#nodebpy.nodes.geometry.converter.MatrixDeterminant) | Compute the determinant of the given matrix |
| [Mix](#nodebpy.nodes.geometry.converter.Mix) | Mix values by a factor |
| [MultiplyMatrices](#nodebpy.nodes.geometry.converter.MultiplyMatrices) | Perform a matrix multiplication on two input matrices |
| [PackUVIslands](#nodebpy.nodes.geometry.converter.PackUVIslands) | Scale islands of a UV map and move them so they fill the UV space as much as possible |
| [ProjectPoint](#nodebpy.nodes.geometry.converter.ProjectPoint) | Project a point using a matrix, using location, rotation, scale, and perspective divide |
| [QuaternionToRotation](#nodebpy.nodes.geometry.converter.QuaternionToRotation) | Build a rotation from quaternion components |
| [RandomValue](#nodebpy.nodes.geometry.converter.RandomValue) | Output a randomized value |
| [ReplaceString](#nodebpy.nodes.geometry.converter.ReplaceString) | Replace a given string segment with another |
| [RotateEuler](#nodebpy.nodes.geometry.converter.RotateEuler) | Apply a secondary Euler rotation to a given Euler rotation |
| [RotateRotation](#nodebpy.nodes.geometry.converter.RotateRotation) | Apply a secondary rotation to a given rotation value |
| [RotateVector](#nodebpy.nodes.geometry.converter.RotateVector) | Apply a rotation to a given vector |
| [RotationToAxisAngle](#nodebpy.nodes.geometry.converter.RotationToAxisAngle) | Convert a rotation to axis angle components |
| [RotationToEuler](#nodebpy.nodes.geometry.converter.RotationToEuler) | Convert a standard rotation value to an Euler rotation |
| [RotationToQuaternion](#nodebpy.nodes.geometry.converter.RotationToQuaternion) | Retrieve the quaternion components representing a rotation |
| [SeparateBundle](#nodebpy.nodes.geometry.converter.SeparateBundle) | Split a bundle into multiple sockets. |
| [SeparateColor](#nodebpy.nodes.geometry.converter.SeparateColor) | Split a color into separate channels, based on a particular color model |
| [SeparateMatrix](#nodebpy.nodes.geometry.converter.SeparateMatrix) | Split a 4x4 matrix into its individual values |
| [SeparateTransform](#nodebpy.nodes.geometry.converter.SeparateTransform) | Split a transformation matrix into a translation vector, a rotation, and a scale vector |
| [SeparateXYZ](#nodebpy.nodes.geometry.converter.SeparateXYZ) | Split a vector into its X, Y, and Z components |
| [SliceString](#nodebpy.nodes.geometry.converter.SliceString) | Extract a string segment from a larger string |
| [StringLength](#nodebpy.nodes.geometry.converter.StringLength) | Output the number of characters in the given string |
| [StringToValue](#nodebpy.nodes.geometry.converter.StringToValue) | Derive a numeric value from a given string representation |
| [Switch](#nodebpy.nodes.geometry.converter.Switch) | Switch between two inputs |
| [TransformDirection](#nodebpy.nodes.geometry.converter.TransformDirection) | Apply a transformation matrix (excluding translation) to the given vector |
| [TransformPoint](#nodebpy.nodes.geometry.converter.TransformPoint) | Apply a transformation matrix to the given vector |
| [TransposeMatrix](#nodebpy.nodes.geometry.converter.TransposeMatrix) | Flip a matrix over its diagonal, turning columns into rows and vice-versa |
| [UVUnwrap](#nodebpy.nodes.geometry.converter.UVUnwrap) | Generate a UV map based on seam edges |
| [ValueToString](#nodebpy.nodes.geometry.converter.ValueToString) | Generate a string representation of the given input value |

### AlignRotationToVector { #nodebpy.nodes.geometry.converter.AlignRotationToVector }

```python
nodes.geometry.converter.AlignRotationToVector(
    rotation=None,
    factor=1.0,
    vector=None,
    *,
    axis='Z',
    pivot_axis='AUTO',
)
```

Orient a rotation along the given direction

#### Attributes

| Name | Description |
| --- | --- |
| [axis](#nodebpy.nodes.geometry.converter.AlignRotationToVector.axis) |  |
| [i_factor](#nodebpy.nodes.geometry.converter.AlignRotationToVector.i_factor) | Input socket: Factor |
| [i_rotation](#nodebpy.nodes.geometry.converter.AlignRotationToVector.i_rotation) | Input socket: Rotation |
| [i_vector](#nodebpy.nodes.geometry.converter.AlignRotationToVector.i_vector) | Input socket: Vector |
| [name](#nodebpy.nodes.geometry.converter.AlignRotationToVector.name) |  |
| [node](#nodebpy.nodes.geometry.converter.AlignRotationToVector.node) |  |
| [o_rotation](#nodebpy.nodes.geometry.converter.AlignRotationToVector.o_rotation) | Output socket: Rotation |
| [pivot_axis](#nodebpy.nodes.geometry.converter.AlignRotationToVector.pivot_axis) |  |
| [tree](#nodebpy.nodes.geometry.converter.AlignRotationToVector.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.AlignRotationToVector.type) |  |

### AxesToRotation { #nodebpy.nodes.geometry.converter.AxesToRotation }

```python
nodes.geometry.converter.AxesToRotation(
    primary_axis=None,
    secondary_axis=None,
    *,
    primary='Z',
    secondary='X',
)
```

Create a rotation from a primary and (ideally orthogonal) secondary axis

#### Attributes

| Name | Description |
| --- | --- |
| [i_primary_axis](#nodebpy.nodes.geometry.converter.AxesToRotation.i_primary_axis) | Input socket: Primary Axis |
| [i_secondary_axis](#nodebpy.nodes.geometry.converter.AxesToRotation.i_secondary_axis) | Input socket: Secondary Axis |
| [name](#nodebpy.nodes.geometry.converter.AxesToRotation.name) |  |
| [node](#nodebpy.nodes.geometry.converter.AxesToRotation.node) |  |
| [o_rotation](#nodebpy.nodes.geometry.converter.AxesToRotation.o_rotation) | Output socket: Rotation |
| [primary](#nodebpy.nodes.geometry.converter.AxesToRotation.primary) |  |
| [primary_axis](#nodebpy.nodes.geometry.converter.AxesToRotation.primary_axis) |  |
| [secondary](#nodebpy.nodes.geometry.converter.AxesToRotation.secondary) |  |
| [secondary_axis](#nodebpy.nodes.geometry.converter.AxesToRotation.secondary_axis) |  |
| [tree](#nodebpy.nodes.geometry.converter.AxesToRotation.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.AxesToRotation.type) |  |

### AxisAngleToRotation { #nodebpy.nodes.geometry.converter.AxisAngleToRotation }

```python
nodes.geometry.converter.AxisAngleToRotation(axis=None, angle=0.0)
```

Build a rotation from an axis and a rotation around that axis

#### Attributes

| Name | Description |
| --- | --- |
| [i_angle](#nodebpy.nodes.geometry.converter.AxisAngleToRotation.i_angle) | Input socket: Angle |
| [i_axis](#nodebpy.nodes.geometry.converter.AxisAngleToRotation.i_axis) | Input socket: Axis |
| [name](#nodebpy.nodes.geometry.converter.AxisAngleToRotation.name) |  |
| [node](#nodebpy.nodes.geometry.converter.AxisAngleToRotation.node) |  |
| [o_rotation](#nodebpy.nodes.geometry.converter.AxisAngleToRotation.o_rotation) | Output socket: Rotation |
| [tree](#nodebpy.nodes.geometry.converter.AxisAngleToRotation.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.AxisAngleToRotation.type) |  |

### BitMath { #nodebpy.nodes.geometry.converter.BitMath }

```python
nodes.geometry.converter.BitMath(a=0, b=0, shift=0, *, operation='AND')
```

Perform bitwise operations on 32-bit integers

#### Attributes

| Name | Description |
| --- | --- |
| [i_a](#nodebpy.nodes.geometry.converter.BitMath.i_a) | Input socket: A |
| [i_b](#nodebpy.nodes.geometry.converter.BitMath.i_b) | Input socket: B |
| [i_shift](#nodebpy.nodes.geometry.converter.BitMath.i_shift) | Input socket: Shift |
| [name](#nodebpy.nodes.geometry.converter.BitMath.name) |  |
| [node](#nodebpy.nodes.geometry.converter.BitMath.node) |  |
| [o_value](#nodebpy.nodes.geometry.converter.BitMath.o_value) | Output socket: Value |
| [operation](#nodebpy.nodes.geometry.converter.BitMath.operation) |  |
| [tree](#nodebpy.nodes.geometry.converter.BitMath.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.BitMath.type) |  |

#### Methods

| Name | Description |
| --- | --- |
| [exclusive_or](#nodebpy.nodes.geometry.converter.BitMath.exclusive_or) | Create Bit Math with operation 'Exclusive Or'. |
| [l_and](#nodebpy.nodes.geometry.converter.BitMath.l_and) | Create Bit Math with operation 'And'. |
| [l_not](#nodebpy.nodes.geometry.converter.BitMath.l_not) | Create Bit Math with operation 'Not'. |
| [l_or](#nodebpy.nodes.geometry.converter.BitMath.l_or) | Create Bit Math with operation 'Or'. |
| [rotate](#nodebpy.nodes.geometry.converter.BitMath.rotate) | Create Bit Math with operation 'Rotate'. |
| [shift](#nodebpy.nodes.geometry.converter.BitMath.shift) | Create Bit Math with operation 'Shift'. |

##### exclusive_or { #nodebpy.nodes.geometry.converter.BitMath.exclusive_or }

```python
nodes.geometry.converter.BitMath.exclusive_or(a=0, b=0)
```

Create Bit Math with operation 'Exclusive Or'.

##### l_and { #nodebpy.nodes.geometry.converter.BitMath.l_and }

```python
nodes.geometry.converter.BitMath.l_and(a=0, b=0)
```

Create Bit Math with operation 'And'.

##### l_not { #nodebpy.nodes.geometry.converter.BitMath.l_not }

```python
nodes.geometry.converter.BitMath.l_not(a=0)
```

Create Bit Math with operation 'Not'.

##### l_or { #nodebpy.nodes.geometry.converter.BitMath.l_or }

```python
nodes.geometry.converter.BitMath.l_or(a=0, b=0)
```

Create Bit Math with operation 'Or'.

##### rotate { #nodebpy.nodes.geometry.converter.BitMath.rotate }

```python
nodes.geometry.converter.BitMath.rotate(a=0, shift=0)
```

Create Bit Math with operation 'Rotate'.

##### shift { #nodebpy.nodes.geometry.converter.BitMath.shift }

```python
nodes.geometry.converter.BitMath.shift(a=0, shift=0)
```

Create Bit Math with operation 'Shift'.

### Blackbody { #nodebpy.nodes.geometry.converter.Blackbody }

```python
nodes.geometry.converter.Blackbody(temperature=6500.0)
```

Convert a blackbody temperature to an RGB value

#### Attributes

| Name | Description |
| --- | --- |
| [i_temperature](#nodebpy.nodes.geometry.converter.Blackbody.i_temperature) | Input socket: Temperature |
| [name](#nodebpy.nodes.geometry.converter.Blackbody.name) |  |
| [node](#nodebpy.nodes.geometry.converter.Blackbody.node) |  |
| [o_color](#nodebpy.nodes.geometry.converter.Blackbody.o_color) | Output socket: Color |
| [tree](#nodebpy.nodes.geometry.converter.Blackbody.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.Blackbody.type) |  |

### BooleanMath { #nodebpy.nodes.geometry.converter.BooleanMath }

```python
nodes.geometry.converter.BooleanMath(
    boolean=False,
    boolean_001=False,
    *,
    operation='AND',
)
```

Perform a logical operation on the given boolean inputs

#### Attributes

| Name | Description |
| --- | --- |
| [i_boolean](#nodebpy.nodes.geometry.converter.BooleanMath.i_boolean) | Input socket: Boolean |
| [i_boolean_001](#nodebpy.nodes.geometry.converter.BooleanMath.i_boolean_001) | Input socket: Boolean |
| [name](#nodebpy.nodes.geometry.converter.BooleanMath.name) |  |
| [node](#nodebpy.nodes.geometry.converter.BooleanMath.node) |  |
| [o_boolean](#nodebpy.nodes.geometry.converter.BooleanMath.o_boolean) | Output socket: Boolean |
| [operation](#nodebpy.nodes.geometry.converter.BooleanMath.operation) |  |
| [tree](#nodebpy.nodes.geometry.converter.BooleanMath.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.BooleanMath.type) |  |

#### Methods

| Name | Description |
| --- | --- |
| [equal](#nodebpy.nodes.geometry.converter.BooleanMath.equal) | Create Boolean Math with operation 'Equal'. |
| [imply](#nodebpy.nodes.geometry.converter.BooleanMath.imply) | Create Boolean Math with operation 'Imply'. |
| [l_and](#nodebpy.nodes.geometry.converter.BooleanMath.l_and) | Create Boolean Math with operation 'And'. |
| [l_not](#nodebpy.nodes.geometry.converter.BooleanMath.l_not) | Create Boolean Math with operation 'Not'. |
| [l_or](#nodebpy.nodes.geometry.converter.BooleanMath.l_or) | Create Boolean Math with operation 'Or'. |
| [nor](#nodebpy.nodes.geometry.converter.BooleanMath.nor) | Create Boolean Math with operation 'Nor'. |
| [not_and](#nodebpy.nodes.geometry.converter.BooleanMath.not_and) | Create Boolean Math with operation 'Not And'. |
| [not_equal](#nodebpy.nodes.geometry.converter.BooleanMath.not_equal) | Create Boolean Math with operation 'Not Equal'. |
| [subtract](#nodebpy.nodes.geometry.converter.BooleanMath.subtract) | Create Boolean Math with operation 'Subtract'. |

##### equal { #nodebpy.nodes.geometry.converter.BooleanMath.equal }

```python
nodes.geometry.converter.BooleanMath.equal(boolean=False, boolean_001=False)
```

Create Boolean Math with operation 'Equal'.

##### imply { #nodebpy.nodes.geometry.converter.BooleanMath.imply }

```python
nodes.geometry.converter.BooleanMath.imply(boolean=False, boolean_001=False)
```

Create Boolean Math with operation 'Imply'.

##### l_and { #nodebpy.nodes.geometry.converter.BooleanMath.l_and }

```python
nodes.geometry.converter.BooleanMath.l_and(boolean=False, boolean_001=False)
```

Create Boolean Math with operation 'And'.

##### l_not { #nodebpy.nodes.geometry.converter.BooleanMath.l_not }

```python
nodes.geometry.converter.BooleanMath.l_not(boolean=False)
```

Create Boolean Math with operation 'Not'.

##### l_or { #nodebpy.nodes.geometry.converter.BooleanMath.l_or }

```python
nodes.geometry.converter.BooleanMath.l_or(boolean=False, boolean_001=False)
```

Create Boolean Math with operation 'Or'.

##### nor { #nodebpy.nodes.geometry.converter.BooleanMath.nor }

```python
nodes.geometry.converter.BooleanMath.nor(boolean=False, boolean_001=False)
```

Create Boolean Math with operation 'Nor'.

##### not_and { #nodebpy.nodes.geometry.converter.BooleanMath.not_and }

```python
nodes.geometry.converter.BooleanMath.not_and(boolean=False, boolean_001=False)
```

Create Boolean Math with operation 'Not And'.

##### not_equal { #nodebpy.nodes.geometry.converter.BooleanMath.not_equal }

```python
nodes.geometry.converter.BooleanMath.not_equal(boolean=False, boolean_001=False)
```

Create Boolean Math with operation 'Not Equal'.

##### subtract { #nodebpy.nodes.geometry.converter.BooleanMath.subtract }

```python
nodes.geometry.converter.BooleanMath.subtract(boolean=False, boolean_001=False)
```

Create Boolean Math with operation 'Subtract'.

### Clamp { #nodebpy.nodes.geometry.converter.Clamp }

```python
nodes.geometry.converter.Clamp(
    value=1.0,
    min=0.0,
    max=1.0,
    *,
    clamp_type='MINMAX',
)
```

Clamp a value between a minimum and a maximum

#### Attributes

| Name | Description |
| --- | --- |
| [clamp_type](#nodebpy.nodes.geometry.converter.Clamp.clamp_type) |  |
| [i_max](#nodebpy.nodes.geometry.converter.Clamp.i_max) | Input socket: Max |
| [i_min](#nodebpy.nodes.geometry.converter.Clamp.i_min) | Input socket: Min |
| [i_value](#nodebpy.nodes.geometry.converter.Clamp.i_value) | Input socket: Value |
| [name](#nodebpy.nodes.geometry.converter.Clamp.name) |  |
| [node](#nodebpy.nodes.geometry.converter.Clamp.node) |  |
| [o_result](#nodebpy.nodes.geometry.converter.Clamp.o_result) | Output socket: Result |
| [tree](#nodebpy.nodes.geometry.converter.Clamp.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.Clamp.type) |  |

### ColorRamp { #nodebpy.nodes.geometry.converter.ColorRamp }

```python
nodes.geometry.converter.ColorRamp(fac=0.5)
```

Map values to colors with the use of a gradient

#### Attributes

| Name | Description |
| --- | --- |
| [i_fac](#nodebpy.nodes.geometry.converter.ColorRamp.i_fac) | Input socket: Factor |
| [name](#nodebpy.nodes.geometry.converter.ColorRamp.name) |  |
| [node](#nodebpy.nodes.geometry.converter.ColorRamp.node) |  |
| [o_alpha](#nodebpy.nodes.geometry.converter.ColorRamp.o_alpha) | Output socket: Alpha |
| [o_color](#nodebpy.nodes.geometry.converter.ColorRamp.o_color) | Output socket: Color |
| [tree](#nodebpy.nodes.geometry.converter.ColorRamp.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.ColorRamp.type) |  |

### CombineBundle { #nodebpy.nodes.geometry.converter.CombineBundle }

```python
nodes.geometry.converter.CombineBundle(define_signature=False)
```

Combine multiple socket values into one.

#### Attributes

| Name | Description |
| --- | --- |
| [define_signature](#nodebpy.nodes.geometry.converter.CombineBundle.define_signature) |  |
| [name](#nodebpy.nodes.geometry.converter.CombineBundle.name) |  |
| [node](#nodebpy.nodes.geometry.converter.CombineBundle.node) |  |
| [o_bundle](#nodebpy.nodes.geometry.converter.CombineBundle.o_bundle) | Output socket: Bundle |
| [tree](#nodebpy.nodes.geometry.converter.CombineBundle.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.CombineBundle.type) |  |

### CombineColor { #nodebpy.nodes.geometry.converter.CombineColor }

```python
nodes.geometry.converter.CombineColor(
    red=0.0,
    green=0.0,
    blue=0.0,
    alpha=1.0,
    *,
    mode='RGB',
)
```

Combine four channels into a single color, based on a particular color model

#### Attributes

| Name | Description |
| --- | --- |
| [i_alpha](#nodebpy.nodes.geometry.converter.CombineColor.i_alpha) | Input socket: Alpha |
| [i_blue](#nodebpy.nodes.geometry.converter.CombineColor.i_blue) | Input socket: Blue |
| [i_green](#nodebpy.nodes.geometry.converter.CombineColor.i_green) | Input socket: Green |
| [i_red](#nodebpy.nodes.geometry.converter.CombineColor.i_red) | Input socket: Red |
| [mode](#nodebpy.nodes.geometry.converter.CombineColor.mode) |  |
| [name](#nodebpy.nodes.geometry.converter.CombineColor.name) |  |
| [node](#nodebpy.nodes.geometry.converter.CombineColor.node) |  |
| [o_color](#nodebpy.nodes.geometry.converter.CombineColor.o_color) | Output socket: Color |
| [tree](#nodebpy.nodes.geometry.converter.CombineColor.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.CombineColor.type) |  |

### CombineMatrix { #nodebpy.nodes.geometry.converter.CombineMatrix }

```python
nodes.geometry.converter.CombineMatrix(
    column_1_row_1=1.0,
    column_1_row_2=0.0,
    column_1_row_3=0.0,
    column_1_row_4=0.0,
    column_2_row_1=0.0,
    column_2_row_2=1.0,
    column_2_row_3=0.0,
    column_2_row_4=0.0,
    column_3_row_1=0.0,
    column_3_row_2=0.0,
    column_3_row_3=1.0,
    column_3_row_4=0.0,
    column_4_row_1=0.0,
    column_4_row_2=0.0,
    column_4_row_3=0.0,
    column_4_row_4=1.0,
)
```

Construct a 4x4 matrix from its individual values

#### Attributes

| Name | Description |
| --- | --- |
| [i_column_1_row_1](#nodebpy.nodes.geometry.converter.CombineMatrix.i_column_1_row_1) | Input socket: Column 1 Row 1 |
| [i_column_1_row_2](#nodebpy.nodes.geometry.converter.CombineMatrix.i_column_1_row_2) | Input socket: Column 1 Row 2 |
| [i_column_1_row_3](#nodebpy.nodes.geometry.converter.CombineMatrix.i_column_1_row_3) | Input socket: Column 1 Row 3 |
| [i_column_1_row_4](#nodebpy.nodes.geometry.converter.CombineMatrix.i_column_1_row_4) | Input socket: Column 1 Row 4 |
| [i_column_2_row_1](#nodebpy.nodes.geometry.converter.CombineMatrix.i_column_2_row_1) | Input socket: Column 2 Row 1 |
| [i_column_2_row_2](#nodebpy.nodes.geometry.converter.CombineMatrix.i_column_2_row_2) | Input socket: Column 2 Row 2 |
| [i_column_2_row_3](#nodebpy.nodes.geometry.converter.CombineMatrix.i_column_2_row_3) | Input socket: Column 2 Row 3 |
| [i_column_2_row_4](#nodebpy.nodes.geometry.converter.CombineMatrix.i_column_2_row_4) | Input socket: Column 2 Row 4 |
| [i_column_3_row_1](#nodebpy.nodes.geometry.converter.CombineMatrix.i_column_3_row_1) | Input socket: Column 3 Row 1 |
| [i_column_3_row_2](#nodebpy.nodes.geometry.converter.CombineMatrix.i_column_3_row_2) | Input socket: Column 3 Row 2 |
| [i_column_3_row_3](#nodebpy.nodes.geometry.converter.CombineMatrix.i_column_3_row_3) | Input socket: Column 3 Row 3 |
| [i_column_3_row_4](#nodebpy.nodes.geometry.converter.CombineMatrix.i_column_3_row_4) | Input socket: Column 3 Row 4 |
| [i_column_4_row_1](#nodebpy.nodes.geometry.converter.CombineMatrix.i_column_4_row_1) | Input socket: Column 4 Row 1 |
| [i_column_4_row_2](#nodebpy.nodes.geometry.converter.CombineMatrix.i_column_4_row_2) | Input socket: Column 4 Row 2 |
| [i_column_4_row_3](#nodebpy.nodes.geometry.converter.CombineMatrix.i_column_4_row_3) | Input socket: Column 4 Row 3 |
| [i_column_4_row_4](#nodebpy.nodes.geometry.converter.CombineMatrix.i_column_4_row_4) | Input socket: Column 4 Row 4 |
| [name](#nodebpy.nodes.geometry.converter.CombineMatrix.name) |  |
| [node](#nodebpy.nodes.geometry.converter.CombineMatrix.node) |  |
| [o_matrix](#nodebpy.nodes.geometry.converter.CombineMatrix.o_matrix) | Output socket: Matrix |
| [tree](#nodebpy.nodes.geometry.converter.CombineMatrix.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.CombineMatrix.type) |  |

### CombineTransform { #nodebpy.nodes.geometry.converter.CombineTransform }

```python
nodes.geometry.converter.CombineTransform(
    translation=None,
    rotation=None,
    scale=None,
)
```

Combine a translation vector, a rotation, and a scale vector into a transformation matrix

#### Attributes

| Name | Description |
| --- | --- |
| [i_rotation](#nodebpy.nodes.geometry.converter.CombineTransform.i_rotation) | Input socket: Rotation |
| [i_scale](#nodebpy.nodes.geometry.converter.CombineTransform.i_scale) | Input socket: Scale |
| [i_translation](#nodebpy.nodes.geometry.converter.CombineTransform.i_translation) | Input socket: Translation |
| [name](#nodebpy.nodes.geometry.converter.CombineTransform.name) |  |
| [node](#nodebpy.nodes.geometry.converter.CombineTransform.node) |  |
| [o_transform](#nodebpy.nodes.geometry.converter.CombineTransform.o_transform) | Output socket: Transform |
| [tree](#nodebpy.nodes.geometry.converter.CombineTransform.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.CombineTransform.type) |  |

### CombineXYZ { #nodebpy.nodes.geometry.converter.CombineXYZ }

```python
nodes.geometry.converter.CombineXYZ(x=0.0, y=0.0, z=0.0)
```

Create a vector from X, Y, and Z components

#### Attributes

| Name | Description |
| --- | --- |
| [i_x](#nodebpy.nodes.geometry.converter.CombineXYZ.i_x) | Input socket: X |
| [i_y](#nodebpy.nodes.geometry.converter.CombineXYZ.i_y) | Input socket: Y |
| [i_z](#nodebpy.nodes.geometry.converter.CombineXYZ.i_z) | Input socket: Z |
| [name](#nodebpy.nodes.geometry.converter.CombineXYZ.name) |  |
| [node](#nodebpy.nodes.geometry.converter.CombineXYZ.node) |  |
| [o_vector](#nodebpy.nodes.geometry.converter.CombineXYZ.o_vector) | Output socket: Vector |
| [tree](#nodebpy.nodes.geometry.converter.CombineXYZ.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.CombineXYZ.type) |  |

### EulerToRotation { #nodebpy.nodes.geometry.converter.EulerToRotation }

```python
nodes.geometry.converter.EulerToRotation(euler=None)
```

Build a rotation from separate angles around each axis

#### Attributes

| Name | Description |
| --- | --- |
| [i_euler](#nodebpy.nodes.geometry.converter.EulerToRotation.i_euler) | Input socket: Euler |
| [name](#nodebpy.nodes.geometry.converter.EulerToRotation.name) |  |
| [node](#nodebpy.nodes.geometry.converter.EulerToRotation.node) |  |
| [o_rotation](#nodebpy.nodes.geometry.converter.EulerToRotation.o_rotation) | Output socket: Rotation |
| [tree](#nodebpy.nodes.geometry.converter.EulerToRotation.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.EulerToRotation.type) |  |

### FindInString { #nodebpy.nodes.geometry.converter.FindInString }

```python
nodes.geometry.converter.FindInString(string='', search='')
```

Find the number of times a given string occurs in another string and the position of the first match

#### Attributes

| Name | Description |
| --- | --- |
| [i_search](#nodebpy.nodes.geometry.converter.FindInString.i_search) | Input socket: Search |
| [i_string](#nodebpy.nodes.geometry.converter.FindInString.i_string) | Input socket: String |
| [name](#nodebpy.nodes.geometry.converter.FindInString.name) |  |
| [node](#nodebpy.nodes.geometry.converter.FindInString.node) |  |
| [o_count](#nodebpy.nodes.geometry.converter.FindInString.o_count) | Output socket: Count |
| [o_first_found](#nodebpy.nodes.geometry.converter.FindInString.o_first_found) | Output socket: First Found |
| [tree](#nodebpy.nodes.geometry.converter.FindInString.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.FindInString.type) |  |

### FloatCurve { #nodebpy.nodes.geometry.converter.FloatCurve }

```python
nodes.geometry.converter.FloatCurve(factor=1.0, value=1.0)
```

Map an input float to a curve and outputs a float value

#### Attributes

| Name | Description |
| --- | --- |
| [i_factor](#nodebpy.nodes.geometry.converter.FloatCurve.i_factor) | Input socket: Factor |
| [i_value](#nodebpy.nodes.geometry.converter.FloatCurve.i_value) | Input socket: Value |
| [name](#nodebpy.nodes.geometry.converter.FloatCurve.name) |  |
| [node](#nodebpy.nodes.geometry.converter.FloatCurve.node) |  |
| [o_value](#nodebpy.nodes.geometry.converter.FloatCurve.o_value) | Output socket: Value |
| [tree](#nodebpy.nodes.geometry.converter.FloatCurve.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.FloatCurve.type) |  |

### FloatToInteger { #nodebpy.nodes.geometry.converter.FloatToInteger }

```python
nodes.geometry.converter.FloatToInteger(float=0.0, *, rounding_mode='ROUND')
```

Convert the given floating-point number to an integer, with a choice of methods

#### Attributes

| Name | Description |
| --- | --- |
| [i_float](#nodebpy.nodes.geometry.converter.FloatToInteger.i_float) | Input socket: Float |
| [name](#nodebpy.nodes.geometry.converter.FloatToInteger.name) |  |
| [node](#nodebpy.nodes.geometry.converter.FloatToInteger.node) |  |
| [o_integer](#nodebpy.nodes.geometry.converter.FloatToInteger.o_integer) | Output socket: Integer |
| [rounding_mode](#nodebpy.nodes.geometry.converter.FloatToInteger.rounding_mode) |  |
| [tree](#nodebpy.nodes.geometry.converter.FloatToInteger.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.FloatToInteger.type) |  |

### HashValue { #nodebpy.nodes.geometry.converter.HashValue }

```python
nodes.geometry.converter.HashValue(value=0, seed=0, *, data_type='INT')
```

Generate a randomized integer using the given input value as a seed

#### Attributes

| Name | Description |
| --- | --- |
| [data_type](#nodebpy.nodes.geometry.converter.HashValue.data_type) |  |
| [i_seed](#nodebpy.nodes.geometry.converter.HashValue.i_seed) | Input socket: Seed |
| [i_value](#nodebpy.nodes.geometry.converter.HashValue.i_value) | Input socket: Value |
| [name](#nodebpy.nodes.geometry.converter.HashValue.name) |  |
| [node](#nodebpy.nodes.geometry.converter.HashValue.node) |  |
| [o_hash](#nodebpy.nodes.geometry.converter.HashValue.o_hash) | Output socket: Hash |
| [tree](#nodebpy.nodes.geometry.converter.HashValue.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.HashValue.type) |  |

#### Methods

| Name | Description |
| --- | --- |
| [color](#nodebpy.nodes.geometry.converter.HashValue.color) | Create Hash Value with operation 'Color'. |
| [float](#nodebpy.nodes.geometry.converter.HashValue.float) | Create Hash Value with operation 'Float'. |
| [integer](#nodebpy.nodes.geometry.converter.HashValue.integer) | Create Hash Value with operation 'Integer'. |
| [matrix](#nodebpy.nodes.geometry.converter.HashValue.matrix) | Create Hash Value with operation 'Matrix'. |
| [rotation](#nodebpy.nodes.geometry.converter.HashValue.rotation) | Create Hash Value with operation 'Rotation'. |
| [string](#nodebpy.nodes.geometry.converter.HashValue.string) | Create Hash Value with operation 'String'. |
| [vector](#nodebpy.nodes.geometry.converter.HashValue.vector) | Create Hash Value with operation 'Vector'. |

##### color { #nodebpy.nodes.geometry.converter.HashValue.color }

```python
nodes.geometry.converter.HashValue.color(value=None, seed=0)
```

Create Hash Value with operation 'Color'.

##### float { #nodebpy.nodes.geometry.converter.HashValue.float }

```python
nodes.geometry.converter.HashValue.float(value=0.0, seed=0)
```

Create Hash Value with operation 'Float'.

##### integer { #nodebpy.nodes.geometry.converter.HashValue.integer }

```python
nodes.geometry.converter.HashValue.integer(value=0, seed=0)
```

Create Hash Value with operation 'Integer'.

##### matrix { #nodebpy.nodes.geometry.converter.HashValue.matrix }

```python
nodes.geometry.converter.HashValue.matrix(value=None, seed=0)
```

Create Hash Value with operation 'Matrix'.

##### rotation { #nodebpy.nodes.geometry.converter.HashValue.rotation }

```python
nodes.geometry.converter.HashValue.rotation(value=None, seed=0)
```

Create Hash Value with operation 'Rotation'.

##### string { #nodebpy.nodes.geometry.converter.HashValue.string }

```python
nodes.geometry.converter.HashValue.string(value='', seed=0)
```

Create Hash Value with operation 'String'.

##### vector { #nodebpy.nodes.geometry.converter.HashValue.vector }

```python
nodes.geometry.converter.HashValue.vector(value=None, seed=0)
```

Create Hash Value with operation 'Vector'.

### IndexOfNearest { #nodebpy.nodes.geometry.converter.IndexOfNearest }

```python
nodes.geometry.converter.IndexOfNearest(position=None, group_id=0)
```

Find the nearest element in a group. Similar to the "Sample Nearest" node

#### Attributes

| Name | Description |
| --- | --- |
| [i_group_id](#nodebpy.nodes.geometry.converter.IndexOfNearest.i_group_id) | Input socket: Group ID |
| [i_position](#nodebpy.nodes.geometry.converter.IndexOfNearest.i_position) | Input socket: Position |
| [name](#nodebpy.nodes.geometry.converter.IndexOfNearest.name) |  |
| [node](#nodebpy.nodes.geometry.converter.IndexOfNearest.node) |  |
| [o_has_neighbor](#nodebpy.nodes.geometry.converter.IndexOfNearest.o_has_neighbor) | Output socket: Has Neighbor |
| [o_index](#nodebpy.nodes.geometry.converter.IndexOfNearest.o_index) | Output socket: Index |
| [tree](#nodebpy.nodes.geometry.converter.IndexOfNearest.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.IndexOfNearest.type) |  |

### IntegerMath { #nodebpy.nodes.geometry.converter.IntegerMath }

```python
nodes.geometry.converter.IntegerMath(
    value=0,
    value_001=0,
    value_002=0,
    *,
    operation='ADD',
)
```

Perform various math operations on the given integer inputs

#### Attributes

| Name | Description |
| --- | --- |
| [i_value](#nodebpy.nodes.geometry.converter.IntegerMath.i_value) | Input socket: Value |
| [i_value_001](#nodebpy.nodes.geometry.converter.IntegerMath.i_value_001) | Input socket: Value |
| [i_value_002](#nodebpy.nodes.geometry.converter.IntegerMath.i_value_002) | Input socket: Value |
| [name](#nodebpy.nodes.geometry.converter.IntegerMath.name) |  |
| [node](#nodebpy.nodes.geometry.converter.IntegerMath.node) |  |
| [o_value](#nodebpy.nodes.geometry.converter.IntegerMath.o_value) | Output socket: Value |
| [operation](#nodebpy.nodes.geometry.converter.IntegerMath.operation) |  |
| [tree](#nodebpy.nodes.geometry.converter.IntegerMath.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.IntegerMath.type) |  |

#### Methods

| Name | Description |
| --- | --- |
| [absolute](#nodebpy.nodes.geometry.converter.IntegerMath.absolute) | Create Integer Math with operation 'Absolute'. |
| [add](#nodebpy.nodes.geometry.converter.IntegerMath.add) | Create Integer Math with operation 'Add'. |
| [divide](#nodebpy.nodes.geometry.converter.IntegerMath.divide) | Create Integer Math with operation 'Divide'. |
| [divide_ceiling](#nodebpy.nodes.geometry.converter.IntegerMath.divide_ceiling) | Create Integer Math with operation 'Divide Ceiling'. |
| [divide_floor](#nodebpy.nodes.geometry.converter.IntegerMath.divide_floor) | Create Integer Math with operation 'Divide Floor'. |
| [divide_round](#nodebpy.nodes.geometry.converter.IntegerMath.divide_round) | Create Integer Math with operation 'Divide Round'. |
| [floored_modulo](#nodebpy.nodes.geometry.converter.IntegerMath.floored_modulo) | Create Integer Math with operation 'Floored Modulo'. |
| [greatest_common_divisor](#nodebpy.nodes.geometry.converter.IntegerMath.greatest_common_divisor) | Create Integer Math with operation 'Greatest Common Divisor'. |
| [least_common_multiple](#nodebpy.nodes.geometry.converter.IntegerMath.least_common_multiple) | Create Integer Math with operation 'Least Common Multiple'. |
| [maximum](#nodebpy.nodes.geometry.converter.IntegerMath.maximum) | Create Integer Math with operation 'Maximum'. |
| [minimum](#nodebpy.nodes.geometry.converter.IntegerMath.minimum) | Create Integer Math with operation 'Minimum'. |
| [modulo](#nodebpy.nodes.geometry.converter.IntegerMath.modulo) | Create Integer Math with operation 'Modulo'. |
| [multiply](#nodebpy.nodes.geometry.converter.IntegerMath.multiply) | Create Integer Math with operation 'Multiply'. |
| [multiply_add](#nodebpy.nodes.geometry.converter.IntegerMath.multiply_add) | Create Integer Math with operation 'Multiply Add'. |
| [negate](#nodebpy.nodes.geometry.converter.IntegerMath.negate) | Create Integer Math with operation 'Negate'. |
| [power](#nodebpy.nodes.geometry.converter.IntegerMath.power) | Create Integer Math with operation 'Power'. |
| [sign](#nodebpy.nodes.geometry.converter.IntegerMath.sign) | Create Integer Math with operation 'Sign'. |
| [subtract](#nodebpy.nodes.geometry.converter.IntegerMath.subtract) | Create Integer Math with operation 'Subtract'. |

##### absolute { #nodebpy.nodes.geometry.converter.IntegerMath.absolute }

```python
nodes.geometry.converter.IntegerMath.absolute(value=0)
```

Create Integer Math with operation 'Absolute'.

##### add { #nodebpy.nodes.geometry.converter.IntegerMath.add }

```python
nodes.geometry.converter.IntegerMath.add(value=0, value_001=0)
```

Create Integer Math with operation 'Add'.

##### divide { #nodebpy.nodes.geometry.converter.IntegerMath.divide }

```python
nodes.geometry.converter.IntegerMath.divide(value=0, value_001=0)
```

Create Integer Math with operation 'Divide'.

##### divide_ceiling { #nodebpy.nodes.geometry.converter.IntegerMath.divide_ceiling }

```python
nodes.geometry.converter.IntegerMath.divide_ceiling(value=0, value_001=0)
```

Create Integer Math with operation 'Divide Ceiling'.

##### divide_floor { #nodebpy.nodes.geometry.converter.IntegerMath.divide_floor }

```python
nodes.geometry.converter.IntegerMath.divide_floor(value=0, value_001=0)
```

Create Integer Math with operation 'Divide Floor'.

##### divide_round { #nodebpy.nodes.geometry.converter.IntegerMath.divide_round }

```python
nodes.geometry.converter.IntegerMath.divide_round(value=0, value_001=0)
```

Create Integer Math with operation 'Divide Round'.

##### floored_modulo { #nodebpy.nodes.geometry.converter.IntegerMath.floored_modulo }

```python
nodes.geometry.converter.IntegerMath.floored_modulo(value=0, value_001=0)
```

Create Integer Math with operation 'Floored Modulo'.

##### greatest_common_divisor { #nodebpy.nodes.geometry.converter.IntegerMath.greatest_common_divisor }

```python
nodes.geometry.converter.IntegerMath.greatest_common_divisor(
    value=0,
    value_001=0,
)
```

Create Integer Math with operation 'Greatest Common Divisor'.

##### least_common_multiple { #nodebpy.nodes.geometry.converter.IntegerMath.least_common_multiple }

```python
nodes.geometry.converter.IntegerMath.least_common_multiple(value=0, value_001=0)
```

Create Integer Math with operation 'Least Common Multiple'.

##### maximum { #nodebpy.nodes.geometry.converter.IntegerMath.maximum }

```python
nodes.geometry.converter.IntegerMath.maximum(value=0, value_001=0)
```

Create Integer Math with operation 'Maximum'.

##### minimum { #nodebpy.nodes.geometry.converter.IntegerMath.minimum }

```python
nodes.geometry.converter.IntegerMath.minimum(value=0, value_001=0)
```

Create Integer Math with operation 'Minimum'.

##### modulo { #nodebpy.nodes.geometry.converter.IntegerMath.modulo }

```python
nodes.geometry.converter.IntegerMath.modulo(value=0, value_001=0)
```

Create Integer Math with operation 'Modulo'.

##### multiply { #nodebpy.nodes.geometry.converter.IntegerMath.multiply }

```python
nodes.geometry.converter.IntegerMath.multiply(value=0, value_001=0)
```

Create Integer Math with operation 'Multiply'.

##### multiply_add { #nodebpy.nodes.geometry.converter.IntegerMath.multiply_add }

```python
nodes.geometry.converter.IntegerMath.multiply_add(
    value=0,
    value_001=0,
    value_002=0,
)
```

Create Integer Math with operation 'Multiply Add'.

##### negate { #nodebpy.nodes.geometry.converter.IntegerMath.negate }

```python
nodes.geometry.converter.IntegerMath.negate(value=0)
```

Create Integer Math with operation 'Negate'.

##### power { #nodebpy.nodes.geometry.converter.IntegerMath.power }

```python
nodes.geometry.converter.IntegerMath.power(value=0, value_001=0)
```

Create Integer Math with operation 'Power'.

##### sign { #nodebpy.nodes.geometry.converter.IntegerMath.sign }

```python
nodes.geometry.converter.IntegerMath.sign(value=0)
```

Create Integer Math with operation 'Sign'.

##### subtract { #nodebpy.nodes.geometry.converter.IntegerMath.subtract }

```python
nodes.geometry.converter.IntegerMath.subtract(value=0, value_001=0)
```

Create Integer Math with operation 'Subtract'.

### InvertMatrix { #nodebpy.nodes.geometry.converter.InvertMatrix }

```python
nodes.geometry.converter.InvertMatrix(matrix=None)
```

Compute the inverse of the given matrix, if one exists

#### Attributes

| Name | Description |
| --- | --- |
| [i_matrix](#nodebpy.nodes.geometry.converter.InvertMatrix.i_matrix) | Input socket: Matrix |
| [name](#nodebpy.nodes.geometry.converter.InvertMatrix.name) |  |
| [node](#nodebpy.nodes.geometry.converter.InvertMatrix.node) |  |
| [o_invertible](#nodebpy.nodes.geometry.converter.InvertMatrix.o_invertible) | Output socket: Invertible |
| [o_matrix](#nodebpy.nodes.geometry.converter.InvertMatrix.o_matrix) | Output socket: Matrix |
| [tree](#nodebpy.nodes.geometry.converter.InvertMatrix.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.InvertMatrix.type) |  |

### InvertRotation { #nodebpy.nodes.geometry.converter.InvertRotation }

```python
nodes.geometry.converter.InvertRotation(rotation=None)
```

Compute the inverse of the given rotation

#### Attributes

| Name | Description |
| --- | --- |
| [i_rotation](#nodebpy.nodes.geometry.converter.InvertRotation.i_rotation) | Input socket: Rotation |
| [name](#nodebpy.nodes.geometry.converter.InvertRotation.name) |  |
| [node](#nodebpy.nodes.geometry.converter.InvertRotation.node) |  |
| [o_rotation](#nodebpy.nodes.geometry.converter.InvertRotation.o_rotation) | Output socket: Rotation |
| [tree](#nodebpy.nodes.geometry.converter.InvertRotation.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.InvertRotation.type) |  |

### JoinBundle { #nodebpy.nodes.geometry.converter.JoinBundle }

```python
nodes.geometry.converter.JoinBundle(bundle=None)
```

Join multiple bundles together

#### Attributes

| Name | Description |
| --- | --- |
| [i_bundle](#nodebpy.nodes.geometry.converter.JoinBundle.i_bundle) | Input socket: Bundle |
| [name](#nodebpy.nodes.geometry.converter.JoinBundle.name) |  |
| [node](#nodebpy.nodes.geometry.converter.JoinBundle.node) |  |
| [o_bundle](#nodebpy.nodes.geometry.converter.JoinBundle.o_bundle) | Output socket: Bundle |
| [tree](#nodebpy.nodes.geometry.converter.JoinBundle.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.JoinBundle.type) |  |

### MapRange { #nodebpy.nodes.geometry.converter.MapRange }

```python
nodes.geometry.converter.MapRange(
    value=1.0,
    from_min=0.0,
    from_max=1.0,
    to_min=0.0,
    to_max=1.0,
    steps=4.0,
    vector=None,
    from_min_float3=None,
    from_max_float3=None,
    to_min_float3=None,
    to_max_float3=None,
    steps_float3=None,
    *,
    clamp=False,
    interpolation_type='LINEAR',
    data_type='FLOAT',
)
```

Remap a value from a range to a target range

#### Attributes

| Name | Description |
| --- | --- |
| [clamp](#nodebpy.nodes.geometry.converter.MapRange.clamp) |  |
| [data_type](#nodebpy.nodes.geometry.converter.MapRange.data_type) |  |
| [i_from_max](#nodebpy.nodes.geometry.converter.MapRange.i_from_max) | Input socket: From Max |
| [i_from_max_float3](#nodebpy.nodes.geometry.converter.MapRange.i_from_max_float3) | Input socket: From Max |
| [i_from_min](#nodebpy.nodes.geometry.converter.MapRange.i_from_min) | Input socket: From Min |
| [i_from_min_float3](#nodebpy.nodes.geometry.converter.MapRange.i_from_min_float3) | Input socket: From Min |
| [i_steps](#nodebpy.nodes.geometry.converter.MapRange.i_steps) | Input socket: Steps |
| [i_steps_float3](#nodebpy.nodes.geometry.converter.MapRange.i_steps_float3) | Input socket: Steps |
| [i_to_max](#nodebpy.nodes.geometry.converter.MapRange.i_to_max) | Input socket: To Max |
| [i_to_max_float3](#nodebpy.nodes.geometry.converter.MapRange.i_to_max_float3) | Input socket: To Max |
| [i_to_min](#nodebpy.nodes.geometry.converter.MapRange.i_to_min) | Input socket: To Min |
| [i_to_min_float3](#nodebpy.nodes.geometry.converter.MapRange.i_to_min_float3) | Input socket: To Min |
| [i_value](#nodebpy.nodes.geometry.converter.MapRange.i_value) | Input socket: Value |
| [i_vector](#nodebpy.nodes.geometry.converter.MapRange.i_vector) | Input socket: Vector |
| [interpolation_type](#nodebpy.nodes.geometry.converter.MapRange.interpolation_type) |  |
| [name](#nodebpy.nodes.geometry.converter.MapRange.name) |  |
| [node](#nodebpy.nodes.geometry.converter.MapRange.node) |  |
| [o_result](#nodebpy.nodes.geometry.converter.MapRange.o_result) | Output socket: Result |
| [o_vector](#nodebpy.nodes.geometry.converter.MapRange.o_vector) | Output socket: Vector |
| [tree](#nodebpy.nodes.geometry.converter.MapRange.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.MapRange.type) |  |

#### Methods

| Name | Description |
| --- | --- |
| [float](#nodebpy.nodes.geometry.converter.MapRange.float) | Create Map Range with operation 'Float'. |
| [vector](#nodebpy.nodes.geometry.converter.MapRange.vector) | Create Map Range with operation 'Vector'. |

##### float { #nodebpy.nodes.geometry.converter.MapRange.float }

```python
nodes.geometry.converter.MapRange.float(
    value=1.0,
    from_min=0.0,
    from_max=1.0,
    to_min=0.0,
    to_max=1.0,
)
```

Create Map Range with operation 'Float'.

##### vector { #nodebpy.nodes.geometry.converter.MapRange.vector }

```python
nodes.geometry.converter.MapRange.vector(
    vector=None,
    from_min3=None,
    from_max3=None,
    to_min3=None,
    to_max3=None,
)
```

Create Map Range with operation 'Vector'.

### MatchString { #nodebpy.nodes.geometry.converter.MatchString }

```python
nodes.geometry.converter.MatchString(string='', operation='Starts With', key='')
```

Check if a given string exists within another string

#### Attributes

| Name | Description |
| --- | --- |
| [i_key](#nodebpy.nodes.geometry.converter.MatchString.i_key) | Input socket: Key |
| [i_operation](#nodebpy.nodes.geometry.converter.MatchString.i_operation) | Input socket: Operation |
| [i_string](#nodebpy.nodes.geometry.converter.MatchString.i_string) | Input socket: String |
| [name](#nodebpy.nodes.geometry.converter.MatchString.name) |  |
| [node](#nodebpy.nodes.geometry.converter.MatchString.node) |  |
| [o_result](#nodebpy.nodes.geometry.converter.MatchString.o_result) | Output socket: Result |
| [tree](#nodebpy.nodes.geometry.converter.MatchString.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.MatchString.type) |  |

### Math { #nodebpy.nodes.geometry.converter.Math }

```python
nodes.geometry.converter.Math(
    value=0.5,
    value_001=0.5,
    value_002=0.5,
    *,
    operation='ADD',
    use_clamp=False,
)
```

Perform math operations

#### Attributes

| Name | Description |
| --- | --- |
| [i_value](#nodebpy.nodes.geometry.converter.Math.i_value) | Input socket: Value |
| [i_value_001](#nodebpy.nodes.geometry.converter.Math.i_value_001) | Input socket: Value |
| [i_value_002](#nodebpy.nodes.geometry.converter.Math.i_value_002) | Input socket: Value |
| [name](#nodebpy.nodes.geometry.converter.Math.name) |  |
| [node](#nodebpy.nodes.geometry.converter.Math.node) |  |
| [o_value](#nodebpy.nodes.geometry.converter.Math.o_value) | Output socket: Value |
| [operation](#nodebpy.nodes.geometry.converter.Math.operation) |  |
| [tree](#nodebpy.nodes.geometry.converter.Math.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.Math.type) |  |
| [use_clamp](#nodebpy.nodes.geometry.converter.Math.use_clamp) |  |

#### Methods

| Name | Description |
| --- | --- |
| [absolute](#nodebpy.nodes.geometry.converter.Math.absolute) | Create Math with operation 'Absolute'. |
| [add](#nodebpy.nodes.geometry.converter.Math.add) | Create Math with operation 'Add'. |
| [arccosine](#nodebpy.nodes.geometry.converter.Math.arccosine) | Create Math with operation 'Arccosine'. |
| [arcsine](#nodebpy.nodes.geometry.converter.Math.arcsine) | Create Math with operation 'Arcsine'. |
| [arctan2](#nodebpy.nodes.geometry.converter.Math.arctan2) | Create Math with operation 'Arctan2'. |
| [arctangent](#nodebpy.nodes.geometry.converter.Math.arctangent) | Create Math with operation 'Arctangent'. |
| [ceil](#nodebpy.nodes.geometry.converter.Math.ceil) | Create Math with operation 'Ceil'. |
| [compare](#nodebpy.nodes.geometry.converter.Math.compare) | Create Math with operation 'Compare'. |
| [cosine](#nodebpy.nodes.geometry.converter.Math.cosine) | Create Math with operation 'Cosine'. |
| [divide](#nodebpy.nodes.geometry.converter.Math.divide) | Create Math with operation 'Divide'. |
| [exponent](#nodebpy.nodes.geometry.converter.Math.exponent) | Create Math with operation 'Exponent'. |
| [floor](#nodebpy.nodes.geometry.converter.Math.floor) | Create Math with operation 'Floor'. |
| [floored_modulo](#nodebpy.nodes.geometry.converter.Math.floored_modulo) | Create Math with operation 'Floored Modulo'. |
| [fraction](#nodebpy.nodes.geometry.converter.Math.fraction) | Create Math with operation 'Fraction'. |
| [greater_than](#nodebpy.nodes.geometry.converter.Math.greater_than) | Create Math with operation 'Greater Than'. |
| [hyperbolic_cosine](#nodebpy.nodes.geometry.converter.Math.hyperbolic_cosine) | Create Math with operation 'Hyperbolic Cosine'. |
| [hyperbolic_sine](#nodebpy.nodes.geometry.converter.Math.hyperbolic_sine) | Create Math with operation 'Hyperbolic Sine'. |
| [hyperbolic_tangent](#nodebpy.nodes.geometry.converter.Math.hyperbolic_tangent) | Create Math with operation 'Hyperbolic Tangent'. |
| [inverse_square_root](#nodebpy.nodes.geometry.converter.Math.inverse_square_root) | Create Math with operation 'Inverse Square Root'. |
| [less_than](#nodebpy.nodes.geometry.converter.Math.less_than) | Create Math with operation 'Less Than'. |
| [logarithm](#nodebpy.nodes.geometry.converter.Math.logarithm) | Create Math with operation 'Logarithm'. |
| [maximum](#nodebpy.nodes.geometry.converter.Math.maximum) | Create Math with operation 'Maximum'. |
| [minimum](#nodebpy.nodes.geometry.converter.Math.minimum) | Create Math with operation 'Minimum'. |
| [multiply](#nodebpy.nodes.geometry.converter.Math.multiply) | Create Math with operation 'Multiply'. |
| [multiply_add](#nodebpy.nodes.geometry.converter.Math.multiply_add) | Create Math with operation 'Multiply Add'. |
| [ping_pong](#nodebpy.nodes.geometry.converter.Math.ping_pong) | Create Math with operation 'Ping-Pong'. |
| [power](#nodebpy.nodes.geometry.converter.Math.power) | Create Math with operation 'Power'. |
| [round](#nodebpy.nodes.geometry.converter.Math.round) | Create Math with operation 'Round'. |
| [sign](#nodebpy.nodes.geometry.converter.Math.sign) | Create Math with operation 'Sign'. |
| [sine](#nodebpy.nodes.geometry.converter.Math.sine) | Create Math with operation 'Sine'. |
| [smooth_maximum](#nodebpy.nodes.geometry.converter.Math.smooth_maximum) | Create Math with operation 'Smooth Maximum'. |
| [smooth_minimum](#nodebpy.nodes.geometry.converter.Math.smooth_minimum) | Create Math with operation 'Smooth Minimum'. |
| [snap](#nodebpy.nodes.geometry.converter.Math.snap) | Create Math with operation 'Snap'. |
| [square_root](#nodebpy.nodes.geometry.converter.Math.square_root) | Create Math with operation 'Square Root'. |
| [subtract](#nodebpy.nodes.geometry.converter.Math.subtract) | Create Math with operation 'Subtract'. |
| [tangent](#nodebpy.nodes.geometry.converter.Math.tangent) | Create Math with operation 'Tangent'. |
| [to_degrees](#nodebpy.nodes.geometry.converter.Math.to_degrees) | Create Math with operation 'To Degrees'. |
| [to_radians](#nodebpy.nodes.geometry.converter.Math.to_radians) | Create Math with operation 'To Radians'. |
| [truncate](#nodebpy.nodes.geometry.converter.Math.truncate) | Create Math with operation 'Truncate'. |
| [truncated_modulo](#nodebpy.nodes.geometry.converter.Math.truncated_modulo) | Create Math with operation 'Truncated Modulo'. |
| [wrap](#nodebpy.nodes.geometry.converter.Math.wrap) | Create Math with operation 'Wrap'. |

##### absolute { #nodebpy.nodes.geometry.converter.Math.absolute }

```python
nodes.geometry.converter.Math.absolute(value=0.5)
```

Create Math with operation 'Absolute'.

##### add { #nodebpy.nodes.geometry.converter.Math.add }

```python
nodes.geometry.converter.Math.add(value=0.5, value_001=0.5)
```

Create Math with operation 'Add'.

##### arccosine { #nodebpy.nodes.geometry.converter.Math.arccosine }

```python
nodes.geometry.converter.Math.arccosine(value=0.5)
```

Create Math with operation 'Arccosine'.

##### arcsine { #nodebpy.nodes.geometry.converter.Math.arcsine }

```python
nodes.geometry.converter.Math.arcsine(value=0.5)
```

Create Math with operation 'Arcsine'.

##### arctan2 { #nodebpy.nodes.geometry.converter.Math.arctan2 }

```python
nodes.geometry.converter.Math.arctan2(value=0.5, value_001=0.5)
```

Create Math with operation 'Arctan2'.

##### arctangent { #nodebpy.nodes.geometry.converter.Math.arctangent }

```python
nodes.geometry.converter.Math.arctangent(value=0.5)
```

Create Math with operation 'Arctangent'.

##### ceil { #nodebpy.nodes.geometry.converter.Math.ceil }

```python
nodes.geometry.converter.Math.ceil(value=0.5)
```

Create Math with operation 'Ceil'.

##### compare { #nodebpy.nodes.geometry.converter.Math.compare }

```python
nodes.geometry.converter.Math.compare(value=0.5, value_001=0.5, value_002=0.5)
```

Create Math with operation 'Compare'.

##### cosine { #nodebpy.nodes.geometry.converter.Math.cosine }

```python
nodes.geometry.converter.Math.cosine(value=0.5)
```

Create Math with operation 'Cosine'.

##### divide { #nodebpy.nodes.geometry.converter.Math.divide }

```python
nodes.geometry.converter.Math.divide(value=0.5, value_001=0.5)
```

Create Math with operation 'Divide'.

##### exponent { #nodebpy.nodes.geometry.converter.Math.exponent }

```python
nodes.geometry.converter.Math.exponent(value=0.5)
```

Create Math with operation 'Exponent'.

##### floor { #nodebpy.nodes.geometry.converter.Math.floor }

```python
nodes.geometry.converter.Math.floor(value=0.5)
```

Create Math with operation 'Floor'.

##### floored_modulo { #nodebpy.nodes.geometry.converter.Math.floored_modulo }

```python
nodes.geometry.converter.Math.floored_modulo(value=0.5, value_001=0.5)
```

Create Math with operation 'Floored Modulo'.

##### fraction { #nodebpy.nodes.geometry.converter.Math.fraction }

```python
nodes.geometry.converter.Math.fraction(value=0.5)
```

Create Math with operation 'Fraction'.

##### greater_than { #nodebpy.nodes.geometry.converter.Math.greater_than }

```python
nodes.geometry.converter.Math.greater_than(value=0.5, value_001=0.5)
```

Create Math with operation 'Greater Than'.

##### hyperbolic_cosine { #nodebpy.nodes.geometry.converter.Math.hyperbolic_cosine }

```python
nodes.geometry.converter.Math.hyperbolic_cosine(value=0.5)
```

Create Math with operation 'Hyperbolic Cosine'.

##### hyperbolic_sine { #nodebpy.nodes.geometry.converter.Math.hyperbolic_sine }

```python
nodes.geometry.converter.Math.hyperbolic_sine(value=0.5)
```

Create Math with operation 'Hyperbolic Sine'.

##### hyperbolic_tangent { #nodebpy.nodes.geometry.converter.Math.hyperbolic_tangent }

```python
nodes.geometry.converter.Math.hyperbolic_tangent(value=0.5)
```

Create Math with operation 'Hyperbolic Tangent'.

##### inverse_square_root { #nodebpy.nodes.geometry.converter.Math.inverse_square_root }

```python
nodes.geometry.converter.Math.inverse_square_root(value=0.5)
```

Create Math with operation 'Inverse Square Root'.

##### less_than { #nodebpy.nodes.geometry.converter.Math.less_than }

```python
nodes.geometry.converter.Math.less_than(value=0.5, value_001=0.5)
```

Create Math with operation 'Less Than'.

##### logarithm { #nodebpy.nodes.geometry.converter.Math.logarithm }

```python
nodes.geometry.converter.Math.logarithm(value=0.5, value_001=0.5)
```

Create Math with operation 'Logarithm'.

##### maximum { #nodebpy.nodes.geometry.converter.Math.maximum }

```python
nodes.geometry.converter.Math.maximum(value=0.5, value_001=0.5)
```

Create Math with operation 'Maximum'.

##### minimum { #nodebpy.nodes.geometry.converter.Math.minimum }

```python
nodes.geometry.converter.Math.minimum(value=0.5, value_001=0.5)
```

Create Math with operation 'Minimum'.

##### multiply { #nodebpy.nodes.geometry.converter.Math.multiply }

```python
nodes.geometry.converter.Math.multiply(value=0.5, value_001=0.5)
```

Create Math with operation 'Multiply'.

##### multiply_add { #nodebpy.nodes.geometry.converter.Math.multiply_add }

```python
nodes.geometry.converter.Math.multiply_add(
    value=0.5,
    value_001=0.5,
    value_002=0.5,
)
```

Create Math with operation 'Multiply Add'.

##### ping_pong { #nodebpy.nodes.geometry.converter.Math.ping_pong }

```python
nodes.geometry.converter.Math.ping_pong(value=0.5, value_001=0.5)
```

Create Math with operation 'Ping-Pong'.

##### power { #nodebpy.nodes.geometry.converter.Math.power }

```python
nodes.geometry.converter.Math.power(value=0.5, value_001=0.5)
```

Create Math with operation 'Power'.

##### round { #nodebpy.nodes.geometry.converter.Math.round }

```python
nodes.geometry.converter.Math.round(value=0.5)
```

Create Math with operation 'Round'.

##### sign { #nodebpy.nodes.geometry.converter.Math.sign }

```python
nodes.geometry.converter.Math.sign(value=0.5)
```

Create Math with operation 'Sign'.

##### sine { #nodebpy.nodes.geometry.converter.Math.sine }

```python
nodes.geometry.converter.Math.sine(value=0.5)
```

Create Math with operation 'Sine'.

##### smooth_maximum { #nodebpy.nodes.geometry.converter.Math.smooth_maximum }

```python
nodes.geometry.converter.Math.smooth_maximum(
    value=0.5,
    value_001=0.5,
    value_002=0.5,
)
```

Create Math with operation 'Smooth Maximum'.

##### smooth_minimum { #nodebpy.nodes.geometry.converter.Math.smooth_minimum }

```python
nodes.geometry.converter.Math.smooth_minimum(
    value=0.5,
    value_001=0.5,
    value_002=0.5,
)
```

Create Math with operation 'Smooth Minimum'.

##### snap { #nodebpy.nodes.geometry.converter.Math.snap }

```python
nodes.geometry.converter.Math.snap(value=0.5, value_001=0.5)
```

Create Math with operation 'Snap'.

##### square_root { #nodebpy.nodes.geometry.converter.Math.square_root }

```python
nodes.geometry.converter.Math.square_root(value=0.5)
```

Create Math with operation 'Square Root'.

##### subtract { #nodebpy.nodes.geometry.converter.Math.subtract }

```python
nodes.geometry.converter.Math.subtract(value=0.5, value_001=0.5)
```

Create Math with operation 'Subtract'.

##### tangent { #nodebpy.nodes.geometry.converter.Math.tangent }

```python
nodes.geometry.converter.Math.tangent(value=0.5)
```

Create Math with operation 'Tangent'.

##### to_degrees { #nodebpy.nodes.geometry.converter.Math.to_degrees }

```python
nodes.geometry.converter.Math.to_degrees(value=0.5)
```

Create Math with operation 'To Degrees'.

##### to_radians { #nodebpy.nodes.geometry.converter.Math.to_radians }

```python
nodes.geometry.converter.Math.to_radians(value=0.5)
```

Create Math with operation 'To Radians'.

##### truncate { #nodebpy.nodes.geometry.converter.Math.truncate }

```python
nodes.geometry.converter.Math.truncate(value=0.5)
```

Create Math with operation 'Truncate'.

##### truncated_modulo { #nodebpy.nodes.geometry.converter.Math.truncated_modulo }

```python
nodes.geometry.converter.Math.truncated_modulo(value=0.5, value_001=0.5)
```

Create Math with operation 'Truncated Modulo'.

##### wrap { #nodebpy.nodes.geometry.converter.Math.wrap }

```python
nodes.geometry.converter.Math.wrap(value=0.5, value_001=0.5, value_002=0.5)
```

Create Math with operation 'Wrap'.

### MatrixDeterminant { #nodebpy.nodes.geometry.converter.MatrixDeterminant }

```python
nodes.geometry.converter.MatrixDeterminant(matrix=None)
```

Compute the determinant of the given matrix

#### Attributes

| Name | Description |
| --- | --- |
| [i_matrix](#nodebpy.nodes.geometry.converter.MatrixDeterminant.i_matrix) | Input socket: Matrix |
| [name](#nodebpy.nodes.geometry.converter.MatrixDeterminant.name) |  |
| [node](#nodebpy.nodes.geometry.converter.MatrixDeterminant.node) |  |
| [o_determinant](#nodebpy.nodes.geometry.converter.MatrixDeterminant.o_determinant) | Output socket: Determinant |
| [tree](#nodebpy.nodes.geometry.converter.MatrixDeterminant.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.MatrixDeterminant.type) |  |

### Mix { #nodebpy.nodes.geometry.converter.Mix }

```python
nodes.geometry.converter.Mix(
    factor_float=0.5,
    factor_vector=None,
    a_float=0.0,
    b_float=0.0,
    a_vector=None,
    b_vector=None,
    a_color=None,
    b_color=None,
    a_rotation=None,
    b_rotation=None,
    *,
    data_type='FLOAT',
    factor_mode='UNIFORM',
    blend_type='MIX',
    clamp_factor=False,
    clamp_result=False,
)
```

Mix values by a factor

#### Attributes

| Name | Description |
| --- | --- |
| [blend_type](#nodebpy.nodes.geometry.converter.Mix.blend_type) |  |
| [clamp_factor](#nodebpy.nodes.geometry.converter.Mix.clamp_factor) |  |
| [clamp_result](#nodebpy.nodes.geometry.converter.Mix.clamp_result) |  |
| [data_type](#nodebpy.nodes.geometry.converter.Mix.data_type) |  |
| [factor_mode](#nodebpy.nodes.geometry.converter.Mix.factor_mode) |  |
| [i_a_color](#nodebpy.nodes.geometry.converter.Mix.i_a_color) | Input socket: A |
| [i_a_float](#nodebpy.nodes.geometry.converter.Mix.i_a_float) | Input socket: A |
| [i_a_rotation](#nodebpy.nodes.geometry.converter.Mix.i_a_rotation) | Input socket: A |
| [i_a_vector](#nodebpy.nodes.geometry.converter.Mix.i_a_vector) | Input socket: A |
| [i_b_color](#nodebpy.nodes.geometry.converter.Mix.i_b_color) | Input socket: B |
| [i_b_float](#nodebpy.nodes.geometry.converter.Mix.i_b_float) | Input socket: B |
| [i_b_rotation](#nodebpy.nodes.geometry.converter.Mix.i_b_rotation) | Input socket: B |
| [i_b_vector](#nodebpy.nodes.geometry.converter.Mix.i_b_vector) | Input socket: B |
| [i_factor_float](#nodebpy.nodes.geometry.converter.Mix.i_factor_float) | Input socket: Factor |
| [i_factor_vector](#nodebpy.nodes.geometry.converter.Mix.i_factor_vector) | Input socket: Factor |
| [name](#nodebpy.nodes.geometry.converter.Mix.name) |  |
| [node](#nodebpy.nodes.geometry.converter.Mix.node) |  |
| [o_result_color](#nodebpy.nodes.geometry.converter.Mix.o_result_color) | Output socket: Result |
| [o_result_float](#nodebpy.nodes.geometry.converter.Mix.o_result_float) | Output socket: Result |
| [o_result_rotation](#nodebpy.nodes.geometry.converter.Mix.o_result_rotation) | Output socket: Result |
| [o_result_vector](#nodebpy.nodes.geometry.converter.Mix.o_result_vector) | Output socket: Result |
| [tree](#nodebpy.nodes.geometry.converter.Mix.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.Mix.type) |  |

#### Methods

| Name | Description |
| --- | --- |
| [color](#nodebpy.nodes.geometry.converter.Mix.color) | Create Mix with operation 'Color'. |
| [float](#nodebpy.nodes.geometry.converter.Mix.float) | Create Mix with operation 'Float'. |
| [rotation](#nodebpy.nodes.geometry.converter.Mix.rotation) | Create Mix with operation 'Rotation'. |
| [vector](#nodebpy.nodes.geometry.converter.Mix.vector) | Create Mix with operation 'Vector'. |

##### color { #nodebpy.nodes.geometry.converter.Mix.color }

```python
nodes.geometry.converter.Mix.color(factor=0.5, a_color=None, b_color=None)
```

Create Mix with operation 'Color'.

##### float { #nodebpy.nodes.geometry.converter.Mix.float }

```python
nodes.geometry.converter.Mix.float(factor=0.5, a=0.0, b=0.0)
```

Create Mix with operation 'Float'.

##### rotation { #nodebpy.nodes.geometry.converter.Mix.rotation }

```python
nodes.geometry.converter.Mix.rotation(
    factor=0.5,
    a_rotation=None,
    b_rotation=None,
)
```

Create Mix with operation 'Rotation'.

##### vector { #nodebpy.nodes.geometry.converter.Mix.vector }

```python
nodes.geometry.converter.Mix.vector(factor=0.5, a=None, b=None)
```

Create Mix with operation 'Vector'.

### MultiplyMatrices { #nodebpy.nodes.geometry.converter.MultiplyMatrices }

```python
nodes.geometry.converter.MultiplyMatrices(matrix=None, matrix_001=None)
```

Perform a matrix multiplication on two input matrices

#### Attributes

| Name | Description |
| --- | --- |
| [i_matrix](#nodebpy.nodes.geometry.converter.MultiplyMatrices.i_matrix) | Input socket: Matrix |
| [i_matrix_001](#nodebpy.nodes.geometry.converter.MultiplyMatrices.i_matrix_001) | Input socket: Matrix |
| [name](#nodebpy.nodes.geometry.converter.MultiplyMatrices.name) |  |
| [node](#nodebpy.nodes.geometry.converter.MultiplyMatrices.node) |  |
| [o_matrix](#nodebpy.nodes.geometry.converter.MultiplyMatrices.o_matrix) | Output socket: Matrix |
| [tree](#nodebpy.nodes.geometry.converter.MultiplyMatrices.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.MultiplyMatrices.type) |  |

### PackUVIslands { #nodebpy.nodes.geometry.converter.PackUVIslands }

```python
nodes.geometry.converter.PackUVIslands(
    uv=None,
    selection=True,
    margin=0.001,
    rotate=True,
    method='Bounding Box',
)
```

Scale islands of a UV map and move them so they fill the UV space as much as possible

#### Attributes

| Name | Description |
| --- | --- |
| [i_margin](#nodebpy.nodes.geometry.converter.PackUVIslands.i_margin) | Input socket: Margin |
| [i_method](#nodebpy.nodes.geometry.converter.PackUVIslands.i_method) | Input socket: Method |
| [i_rotate](#nodebpy.nodes.geometry.converter.PackUVIslands.i_rotate) | Input socket: Rotate |
| [i_selection](#nodebpy.nodes.geometry.converter.PackUVIslands.i_selection) | Input socket: Selection |
| [i_uv](#nodebpy.nodes.geometry.converter.PackUVIslands.i_uv) | Input socket: UV |
| [name](#nodebpy.nodes.geometry.converter.PackUVIslands.name) |  |
| [node](#nodebpy.nodes.geometry.converter.PackUVIslands.node) |  |
| [o_uv](#nodebpy.nodes.geometry.converter.PackUVIslands.o_uv) | Output socket: UV |
| [tree](#nodebpy.nodes.geometry.converter.PackUVIslands.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.PackUVIslands.type) |  |

### ProjectPoint { #nodebpy.nodes.geometry.converter.ProjectPoint }

```python
nodes.geometry.converter.ProjectPoint(vector=None, transform=None)
```

Project a point using a matrix, using location, rotation, scale, and perspective divide

#### Attributes

| Name | Description |
| --- | --- |
| [i_transform](#nodebpy.nodes.geometry.converter.ProjectPoint.i_transform) | Input socket: Transform |
| [i_vector](#nodebpy.nodes.geometry.converter.ProjectPoint.i_vector) | Input socket: Vector |
| [name](#nodebpy.nodes.geometry.converter.ProjectPoint.name) |  |
| [node](#nodebpy.nodes.geometry.converter.ProjectPoint.node) |  |
| [o_vector](#nodebpy.nodes.geometry.converter.ProjectPoint.o_vector) | Output socket: Vector |
| [tree](#nodebpy.nodes.geometry.converter.ProjectPoint.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.ProjectPoint.type) |  |

### QuaternionToRotation { #nodebpy.nodes.geometry.converter.QuaternionToRotation }

```python
nodes.geometry.converter.QuaternionToRotation(w=1.0, x=0.0, y=0.0, z=0.0)
```

Build a rotation from quaternion components

#### Attributes

| Name | Description |
| --- | --- |
| [i_w](#nodebpy.nodes.geometry.converter.QuaternionToRotation.i_w) | Input socket: W |
| [i_x](#nodebpy.nodes.geometry.converter.QuaternionToRotation.i_x) | Input socket: X |
| [i_y](#nodebpy.nodes.geometry.converter.QuaternionToRotation.i_y) | Input socket: Y |
| [i_z](#nodebpy.nodes.geometry.converter.QuaternionToRotation.i_z) | Input socket: Z |
| [name](#nodebpy.nodes.geometry.converter.QuaternionToRotation.name) |  |
| [node](#nodebpy.nodes.geometry.converter.QuaternionToRotation.node) |  |
| [o_rotation](#nodebpy.nodes.geometry.converter.QuaternionToRotation.o_rotation) | Output socket: Rotation |
| [tree](#nodebpy.nodes.geometry.converter.QuaternionToRotation.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.QuaternionToRotation.type) |  |

### RandomValue { #nodebpy.nodes.geometry.converter.RandomValue }

```python
nodes.geometry.converter.RandomValue(
    min=None,
    max=None,
    min_001=0.0,
    max_001=1.0,
    min_002=0,
    max_002=100,
    probability=0.5,
    id=0,
    seed=0,
    *,
    data_type='FLOAT',
)
```

Output a randomized value

#### Attributes

| Name | Description |
| --- | --- |
| [data_type](#nodebpy.nodes.geometry.converter.RandomValue.data_type) |  |
| [i_id](#nodebpy.nodes.geometry.converter.RandomValue.i_id) | Input socket: ID |
| [i_max](#nodebpy.nodes.geometry.converter.RandomValue.i_max) | Input socket: Max |
| [i_max_001](#nodebpy.nodes.geometry.converter.RandomValue.i_max_001) | Input socket: Max |
| [i_max_002](#nodebpy.nodes.geometry.converter.RandomValue.i_max_002) | Input socket: Max |
| [i_min](#nodebpy.nodes.geometry.converter.RandomValue.i_min) | Input socket: Min |
| [i_min_001](#nodebpy.nodes.geometry.converter.RandomValue.i_min_001) | Input socket: Min |
| [i_min_002](#nodebpy.nodes.geometry.converter.RandomValue.i_min_002) | Input socket: Min |
| [i_probability](#nodebpy.nodes.geometry.converter.RandomValue.i_probability) | Input socket: Probability |
| [i_seed](#nodebpy.nodes.geometry.converter.RandomValue.i_seed) | Input socket: Seed |
| [name](#nodebpy.nodes.geometry.converter.RandomValue.name) |  |
| [node](#nodebpy.nodes.geometry.converter.RandomValue.node) |  |
| [o_value](#nodebpy.nodes.geometry.converter.RandomValue.o_value) | Output socket: Value |
| [o_value_001](#nodebpy.nodes.geometry.converter.RandomValue.o_value_001) | Output socket: Value |
| [o_value_002](#nodebpy.nodes.geometry.converter.RandomValue.o_value_002) | Output socket: Value |
| [o_value_003](#nodebpy.nodes.geometry.converter.RandomValue.o_value_003) | Output socket: Value |
| [tree](#nodebpy.nodes.geometry.converter.RandomValue.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.RandomValue.type) |  |

#### Methods

| Name | Description |
| --- | --- |
| [boolean](#nodebpy.nodes.geometry.converter.RandomValue.boolean) | Create Random Value with operation 'Boolean'. |
| [float](#nodebpy.nodes.geometry.converter.RandomValue.float) | Create Random Value with operation 'Float'. |
| [integer](#nodebpy.nodes.geometry.converter.RandomValue.integer) | Create Random Value with operation 'Integer'. |
| [vector](#nodebpy.nodes.geometry.converter.RandomValue.vector) | Create Random Value with operation 'Vector'. |

##### boolean { #nodebpy.nodes.geometry.converter.RandomValue.boolean }

```python
nodes.geometry.converter.RandomValue.boolean(probability=0.5, id=0, seed=0)
```

Create Random Value with operation 'Boolean'.

##### float { #nodebpy.nodes.geometry.converter.RandomValue.float }

```python
nodes.geometry.converter.RandomValue.float(min=0.0, max=1.0, id=0, seed=0)
```

Create Random Value with operation 'Float'.

##### integer { #nodebpy.nodes.geometry.converter.RandomValue.integer }

```python
nodes.geometry.converter.RandomValue.integer(min=0, max=100, id=0, seed=0)
```

Create Random Value with operation 'Integer'.

##### vector { #nodebpy.nodes.geometry.converter.RandomValue.vector }

```python
nodes.geometry.converter.RandomValue.vector(min=None, max=None, id=0, seed=0)
```

Create Random Value with operation 'Vector'.

### ReplaceString { #nodebpy.nodes.geometry.converter.ReplaceString }

```python
nodes.geometry.converter.ReplaceString(string='', find='', replace='')
```

Replace a given string segment with another

#### Attributes

| Name | Description |
| --- | --- |
| [i_find](#nodebpy.nodes.geometry.converter.ReplaceString.i_find) | Input socket: Find |
| [i_replace](#nodebpy.nodes.geometry.converter.ReplaceString.i_replace) | Input socket: Replace |
| [i_string](#nodebpy.nodes.geometry.converter.ReplaceString.i_string) | Input socket: String |
| [name](#nodebpy.nodes.geometry.converter.ReplaceString.name) |  |
| [node](#nodebpy.nodes.geometry.converter.ReplaceString.node) |  |
| [o_string](#nodebpy.nodes.geometry.converter.ReplaceString.o_string) | Output socket: String |
| [tree](#nodebpy.nodes.geometry.converter.ReplaceString.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.ReplaceString.type) |  |

### RotateEuler { #nodebpy.nodes.geometry.converter.RotateEuler }

```python
nodes.geometry.converter.RotateEuler(
    rotation=None,
    rotate_by=None,
    axis=None,
    angle=0.0,
    *,
    rotation_type='EULER',
    space='OBJECT',
)
```

Apply a secondary Euler rotation to a given Euler rotation

#### Attributes

| Name | Description |
| --- | --- |
| [i_angle](#nodebpy.nodes.geometry.converter.RotateEuler.i_angle) | Input socket: Angle |
| [i_axis](#nodebpy.nodes.geometry.converter.RotateEuler.i_axis) | Input socket: Axis |
| [i_rotate_by](#nodebpy.nodes.geometry.converter.RotateEuler.i_rotate_by) | Input socket: Rotate By |
| [i_rotation](#nodebpy.nodes.geometry.converter.RotateEuler.i_rotation) | Input socket: Rotation |
| [name](#nodebpy.nodes.geometry.converter.RotateEuler.name) |  |
| [node](#nodebpy.nodes.geometry.converter.RotateEuler.node) |  |
| [o_rotation](#nodebpy.nodes.geometry.converter.RotateEuler.o_rotation) | Output socket: Rotation |
| [rotation_type](#nodebpy.nodes.geometry.converter.RotateEuler.rotation_type) |  |
| [space](#nodebpy.nodes.geometry.converter.RotateEuler.space) |  |
| [tree](#nodebpy.nodes.geometry.converter.RotateEuler.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.RotateEuler.type) |  |

### RotateRotation { #nodebpy.nodes.geometry.converter.RotateRotation }

```python
nodes.geometry.converter.RotateRotation(
    rotation=None,
    rotate_by=None,
    *,
    rotation_space='GLOBAL',
)
```

Apply a secondary rotation to a given rotation value

#### Attributes

| Name | Description |
| --- | --- |
| [i_rotate_by](#nodebpy.nodes.geometry.converter.RotateRotation.i_rotate_by) | Input socket: Rotate By |
| [i_rotation](#nodebpy.nodes.geometry.converter.RotateRotation.i_rotation) | Input socket: Rotation |
| [name](#nodebpy.nodes.geometry.converter.RotateRotation.name) |  |
| [node](#nodebpy.nodes.geometry.converter.RotateRotation.node) |  |
| [o_rotation](#nodebpy.nodes.geometry.converter.RotateRotation.o_rotation) | Output socket: Rotation |
| [rotation_space](#nodebpy.nodes.geometry.converter.RotateRotation.rotation_space) |  |
| [tree](#nodebpy.nodes.geometry.converter.RotateRotation.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.RotateRotation.type) |  |

### RotateVector { #nodebpy.nodes.geometry.converter.RotateVector }

```python
nodes.geometry.converter.RotateVector(vector=None, rotation=None)
```

Apply a rotation to a given vector

#### Attributes

| Name | Description |
| --- | --- |
| [i_rotation](#nodebpy.nodes.geometry.converter.RotateVector.i_rotation) | Input socket: Rotation |
| [i_vector](#nodebpy.nodes.geometry.converter.RotateVector.i_vector) | Input socket: Vector |
| [name](#nodebpy.nodes.geometry.converter.RotateVector.name) |  |
| [node](#nodebpy.nodes.geometry.converter.RotateVector.node) |  |
| [o_vector](#nodebpy.nodes.geometry.converter.RotateVector.o_vector) | Output socket: Vector |
| [tree](#nodebpy.nodes.geometry.converter.RotateVector.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.RotateVector.type) |  |

### RotationToAxisAngle { #nodebpy.nodes.geometry.converter.RotationToAxisAngle }

```python
nodes.geometry.converter.RotationToAxisAngle(rotation=None)
```

Convert a rotation to axis angle components

#### Attributes

| Name | Description |
| --- | --- |
| [i_rotation](#nodebpy.nodes.geometry.converter.RotationToAxisAngle.i_rotation) | Input socket: Rotation |
| [name](#nodebpy.nodes.geometry.converter.RotationToAxisAngle.name) |  |
| [node](#nodebpy.nodes.geometry.converter.RotationToAxisAngle.node) |  |
| [o_angle](#nodebpy.nodes.geometry.converter.RotationToAxisAngle.o_angle) | Output socket: Angle |
| [o_axis](#nodebpy.nodes.geometry.converter.RotationToAxisAngle.o_axis) | Output socket: Axis |
| [tree](#nodebpy.nodes.geometry.converter.RotationToAxisAngle.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.RotationToAxisAngle.type) |  |

### RotationToEuler { #nodebpy.nodes.geometry.converter.RotationToEuler }

```python
nodes.geometry.converter.RotationToEuler(rotation=None)
```

Convert a standard rotation value to an Euler rotation

#### Attributes

| Name | Description |
| --- | --- |
| [i_rotation](#nodebpy.nodes.geometry.converter.RotationToEuler.i_rotation) | Input socket: Rotation |
| [name](#nodebpy.nodes.geometry.converter.RotationToEuler.name) |  |
| [node](#nodebpy.nodes.geometry.converter.RotationToEuler.node) |  |
| [o_euler](#nodebpy.nodes.geometry.converter.RotationToEuler.o_euler) | Output socket: Euler |
| [tree](#nodebpy.nodes.geometry.converter.RotationToEuler.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.RotationToEuler.type) |  |

### RotationToQuaternion { #nodebpy.nodes.geometry.converter.RotationToQuaternion }

```python
nodes.geometry.converter.RotationToQuaternion(rotation=None)
```

Retrieve the quaternion components representing a rotation

#### Attributes

| Name | Description |
| --- | --- |
| [i_rotation](#nodebpy.nodes.geometry.converter.RotationToQuaternion.i_rotation) | Input socket: Rotation |
| [name](#nodebpy.nodes.geometry.converter.RotationToQuaternion.name) |  |
| [node](#nodebpy.nodes.geometry.converter.RotationToQuaternion.node) |  |
| [o_w](#nodebpy.nodes.geometry.converter.RotationToQuaternion.o_w) | Output socket: W |
| [o_x](#nodebpy.nodes.geometry.converter.RotationToQuaternion.o_x) | Output socket: X |
| [o_y](#nodebpy.nodes.geometry.converter.RotationToQuaternion.o_y) | Output socket: Y |
| [o_z](#nodebpy.nodes.geometry.converter.RotationToQuaternion.o_z) | Output socket: Z |
| [tree](#nodebpy.nodes.geometry.converter.RotationToQuaternion.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.RotationToQuaternion.type) |  |

### SeparateBundle { #nodebpy.nodes.geometry.converter.SeparateBundle }

```python
nodes.geometry.converter.SeparateBundle(bundle=None, *, define_signature=False)
```

Split a bundle into multiple sockets.

#### Attributes

| Name | Description |
| --- | --- |
| [define_signature](#nodebpy.nodes.geometry.converter.SeparateBundle.define_signature) |  |
| [i_bundle](#nodebpy.nodes.geometry.converter.SeparateBundle.i_bundle) | Input socket: Bundle |
| [name](#nodebpy.nodes.geometry.converter.SeparateBundle.name) |  |
| [node](#nodebpy.nodes.geometry.converter.SeparateBundle.node) |  |
| [tree](#nodebpy.nodes.geometry.converter.SeparateBundle.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.SeparateBundle.type) |  |

### SeparateColor { #nodebpy.nodes.geometry.converter.SeparateColor }

```python
nodes.geometry.converter.SeparateColor(color=None, *, mode='RGB')
```

Split a color into separate channels, based on a particular color model

#### Attributes

| Name | Description |
| --- | --- |
| [i_color](#nodebpy.nodes.geometry.converter.SeparateColor.i_color) | Input socket: Color |
| [mode](#nodebpy.nodes.geometry.converter.SeparateColor.mode) |  |
| [name](#nodebpy.nodes.geometry.converter.SeparateColor.name) |  |
| [node](#nodebpy.nodes.geometry.converter.SeparateColor.node) |  |
| [o_alpha](#nodebpy.nodes.geometry.converter.SeparateColor.o_alpha) | Output socket: Alpha |
| [o_blue](#nodebpy.nodes.geometry.converter.SeparateColor.o_blue) | Output socket: Blue |
| [o_green](#nodebpy.nodes.geometry.converter.SeparateColor.o_green) | Output socket: Green |
| [o_red](#nodebpy.nodes.geometry.converter.SeparateColor.o_red) | Output socket: Red |
| [tree](#nodebpy.nodes.geometry.converter.SeparateColor.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.SeparateColor.type) |  |

### SeparateMatrix { #nodebpy.nodes.geometry.converter.SeparateMatrix }

```python
nodes.geometry.converter.SeparateMatrix(matrix=None)
```

Split a 4x4 matrix into its individual values

#### Attributes

| Name | Description |
| --- | --- |
| [i_matrix](#nodebpy.nodes.geometry.converter.SeparateMatrix.i_matrix) | Input socket: Matrix |
| [name](#nodebpy.nodes.geometry.converter.SeparateMatrix.name) |  |
| [node](#nodebpy.nodes.geometry.converter.SeparateMatrix.node) |  |
| [o_column_1_row_1](#nodebpy.nodes.geometry.converter.SeparateMatrix.o_column_1_row_1) | Output socket: Column 1 Row 1 |
| [o_column_1_row_2](#nodebpy.nodes.geometry.converter.SeparateMatrix.o_column_1_row_2) | Output socket: Column 1 Row 2 |
| [o_column_1_row_3](#nodebpy.nodes.geometry.converter.SeparateMatrix.o_column_1_row_3) | Output socket: Column 1 Row 3 |
| [o_column_1_row_4](#nodebpy.nodes.geometry.converter.SeparateMatrix.o_column_1_row_4) | Output socket: Column 1 Row 4 |
| [o_column_2_row_1](#nodebpy.nodes.geometry.converter.SeparateMatrix.o_column_2_row_1) | Output socket: Column 2 Row 1 |
| [o_column_2_row_2](#nodebpy.nodes.geometry.converter.SeparateMatrix.o_column_2_row_2) | Output socket: Column 2 Row 2 |
| [o_column_2_row_3](#nodebpy.nodes.geometry.converter.SeparateMatrix.o_column_2_row_3) | Output socket: Column 2 Row 3 |
| [o_column_2_row_4](#nodebpy.nodes.geometry.converter.SeparateMatrix.o_column_2_row_4) | Output socket: Column 2 Row 4 |
| [o_column_3_row_1](#nodebpy.nodes.geometry.converter.SeparateMatrix.o_column_3_row_1) | Output socket: Column 3 Row 1 |
| [o_column_3_row_2](#nodebpy.nodes.geometry.converter.SeparateMatrix.o_column_3_row_2) | Output socket: Column 3 Row 2 |
| [o_column_3_row_3](#nodebpy.nodes.geometry.converter.SeparateMatrix.o_column_3_row_3) | Output socket: Column 3 Row 3 |
| [o_column_3_row_4](#nodebpy.nodes.geometry.converter.SeparateMatrix.o_column_3_row_4) | Output socket: Column 3 Row 4 |
| [o_column_4_row_1](#nodebpy.nodes.geometry.converter.SeparateMatrix.o_column_4_row_1) | Output socket: Column 4 Row 1 |
| [o_column_4_row_2](#nodebpy.nodes.geometry.converter.SeparateMatrix.o_column_4_row_2) | Output socket: Column 4 Row 2 |
| [o_column_4_row_3](#nodebpy.nodes.geometry.converter.SeparateMatrix.o_column_4_row_3) | Output socket: Column 4 Row 3 |
| [o_column_4_row_4](#nodebpy.nodes.geometry.converter.SeparateMatrix.o_column_4_row_4) | Output socket: Column 4 Row 4 |
| [tree](#nodebpy.nodes.geometry.converter.SeparateMatrix.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.SeparateMatrix.type) |  |

### SeparateTransform { #nodebpy.nodes.geometry.converter.SeparateTransform }

```python
nodes.geometry.converter.SeparateTransform(transform=None)
```

Split a transformation matrix into a translation vector, a rotation, and a scale vector

#### Attributes

| Name | Description |
| --- | --- |
| [i_transform](#nodebpy.nodes.geometry.converter.SeparateTransform.i_transform) | Input socket: Transform |
| [name](#nodebpy.nodes.geometry.converter.SeparateTransform.name) |  |
| [node](#nodebpy.nodes.geometry.converter.SeparateTransform.node) |  |
| [o_rotation](#nodebpy.nodes.geometry.converter.SeparateTransform.o_rotation) | Output socket: Rotation |
| [o_scale](#nodebpy.nodes.geometry.converter.SeparateTransform.o_scale) | Output socket: Scale |
| [o_translation](#nodebpy.nodes.geometry.converter.SeparateTransform.o_translation) | Output socket: Translation |
| [tree](#nodebpy.nodes.geometry.converter.SeparateTransform.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.SeparateTransform.type) |  |

### SeparateXYZ { #nodebpy.nodes.geometry.converter.SeparateXYZ }

```python
nodes.geometry.converter.SeparateXYZ(vector=None)
```

Split a vector into its X, Y, and Z components

#### Attributes

| Name | Description |
| --- | --- |
| [i_vector](#nodebpy.nodes.geometry.converter.SeparateXYZ.i_vector) | Input socket: Vector |
| [name](#nodebpy.nodes.geometry.converter.SeparateXYZ.name) |  |
| [node](#nodebpy.nodes.geometry.converter.SeparateXYZ.node) |  |
| [o_x](#nodebpy.nodes.geometry.converter.SeparateXYZ.o_x) | Output socket: X |
| [o_y](#nodebpy.nodes.geometry.converter.SeparateXYZ.o_y) | Output socket: Y |
| [o_z](#nodebpy.nodes.geometry.converter.SeparateXYZ.o_z) | Output socket: Z |
| [tree](#nodebpy.nodes.geometry.converter.SeparateXYZ.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.SeparateXYZ.type) |  |

### SliceString { #nodebpy.nodes.geometry.converter.SliceString }

```python
nodes.geometry.converter.SliceString(string='', position=0, length=10)
```

Extract a string segment from a larger string

#### Attributes

| Name | Description |
| --- | --- |
| [i_length](#nodebpy.nodes.geometry.converter.SliceString.i_length) | Input socket: Length |
| [i_position](#nodebpy.nodes.geometry.converter.SliceString.i_position) | Input socket: Position |
| [i_string](#nodebpy.nodes.geometry.converter.SliceString.i_string) | Input socket: String |
| [name](#nodebpy.nodes.geometry.converter.SliceString.name) |  |
| [node](#nodebpy.nodes.geometry.converter.SliceString.node) |  |
| [o_string](#nodebpy.nodes.geometry.converter.SliceString.o_string) | Output socket: String |
| [tree](#nodebpy.nodes.geometry.converter.SliceString.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.SliceString.type) |  |

### StringLength { #nodebpy.nodes.geometry.converter.StringLength }

```python
nodes.geometry.converter.StringLength(string='')
```

Output the number of characters in the given string

#### Attributes

| Name | Description |
| --- | --- |
| [i_string](#nodebpy.nodes.geometry.converter.StringLength.i_string) | Input socket: String |
| [name](#nodebpy.nodes.geometry.converter.StringLength.name) |  |
| [node](#nodebpy.nodes.geometry.converter.StringLength.node) |  |
| [o_length](#nodebpy.nodes.geometry.converter.StringLength.o_length) | Output socket: Length |
| [tree](#nodebpy.nodes.geometry.converter.StringLength.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.StringLength.type) |  |

### StringToValue { #nodebpy.nodes.geometry.converter.StringToValue }

```python
nodes.geometry.converter.StringToValue(string='', *, data_type='FLOAT')
```

Derive a numeric value from a given string representation

#### Attributes

| Name | Description |
| --- | --- |
| [data_type](#nodebpy.nodes.geometry.converter.StringToValue.data_type) |  |
| [i_string](#nodebpy.nodes.geometry.converter.StringToValue.i_string) | Input socket: String |
| [name](#nodebpy.nodes.geometry.converter.StringToValue.name) |  |
| [node](#nodebpy.nodes.geometry.converter.StringToValue.node) |  |
| [o_length](#nodebpy.nodes.geometry.converter.StringToValue.o_length) | Output socket: Length |
| [o_value](#nodebpy.nodes.geometry.converter.StringToValue.o_value) | Output socket: Value |
| [tree](#nodebpy.nodes.geometry.converter.StringToValue.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.StringToValue.type) |  |

#### Methods

| Name | Description |
| --- | --- |
| [float](#nodebpy.nodes.geometry.converter.StringToValue.float) | Create String to Value with operation 'Float'. |
| [integer](#nodebpy.nodes.geometry.converter.StringToValue.integer) | Create String to Value with operation 'Integer'. |

##### float { #nodebpy.nodes.geometry.converter.StringToValue.float }

```python
nodes.geometry.converter.StringToValue.float(string='')
```

Create String to Value with operation 'Float'.

##### integer { #nodebpy.nodes.geometry.converter.StringToValue.integer }

```python
nodes.geometry.converter.StringToValue.integer(string='')
```

Create String to Value with operation 'Integer'.

### Switch { #nodebpy.nodes.geometry.converter.Switch }

```python
nodes.geometry.converter.Switch(
    switch=False,
    false=None,
    true=None,
    *,
    input_type='GEOMETRY',
)
```

Switch between two inputs

#### Attributes

| Name | Description |
| --- | --- |
| [i_false](#nodebpy.nodes.geometry.converter.Switch.i_false) | Input socket: False |
| [i_switch](#nodebpy.nodes.geometry.converter.Switch.i_switch) | Input socket: Switch |
| [i_true](#nodebpy.nodes.geometry.converter.Switch.i_true) | Input socket: True |
| [input_type](#nodebpy.nodes.geometry.converter.Switch.input_type) |  |
| [name](#nodebpy.nodes.geometry.converter.Switch.name) |  |
| [node](#nodebpy.nodes.geometry.converter.Switch.node) |  |
| [o_output](#nodebpy.nodes.geometry.converter.Switch.o_output) | Output socket: Output |
| [tree](#nodebpy.nodes.geometry.converter.Switch.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.Switch.type) |  |

#### Methods

| Name | Description |
| --- | --- |
| [boolean](#nodebpy.nodes.geometry.converter.Switch.boolean) | Create Switch with operation 'Boolean'. |
| [bundle](#nodebpy.nodes.geometry.converter.Switch.bundle) | Create Switch with operation 'Bundle'. |
| [closure](#nodebpy.nodes.geometry.converter.Switch.closure) | Create Switch with operation 'Closure'. |
| [collection](#nodebpy.nodes.geometry.converter.Switch.collection) | Create Switch with operation 'Collection'. |
| [color](#nodebpy.nodes.geometry.converter.Switch.color) | Create Switch with operation 'Color'. |
| [float](#nodebpy.nodes.geometry.converter.Switch.float) | Create Switch with operation 'Float'. |
| [geometry](#nodebpy.nodes.geometry.converter.Switch.geometry) | Create Switch with operation 'Geometry'. |
| [image](#nodebpy.nodes.geometry.converter.Switch.image) | Create Switch with operation 'Image'. |
| [integer](#nodebpy.nodes.geometry.converter.Switch.integer) | Create Switch with operation 'Integer'. |
| [material](#nodebpy.nodes.geometry.converter.Switch.material) | Create Switch with operation 'Material'. |
| [matrix](#nodebpy.nodes.geometry.converter.Switch.matrix) | Create Switch with operation 'Matrix'. |
| [menu](#nodebpy.nodes.geometry.converter.Switch.menu) | Create Switch with operation 'Menu'. |
| [object](#nodebpy.nodes.geometry.converter.Switch.object) | Create Switch with operation 'Object'. |
| [rotation](#nodebpy.nodes.geometry.converter.Switch.rotation) | Create Switch with operation 'Rotation'. |
| [string](#nodebpy.nodes.geometry.converter.Switch.string) | Create Switch with operation 'String'. |
| [vector](#nodebpy.nodes.geometry.converter.Switch.vector) | Create Switch with operation 'Vector'. |

##### boolean { #nodebpy.nodes.geometry.converter.Switch.boolean }

```python
nodes.geometry.converter.Switch.boolean(switch=False, false=False, true=False)
```

Create Switch with operation 'Boolean'.

##### bundle { #nodebpy.nodes.geometry.converter.Switch.bundle }

```python
nodes.geometry.converter.Switch.bundle(switch=False, false=None, true=None)
```

Create Switch with operation 'Bundle'.

##### closure { #nodebpy.nodes.geometry.converter.Switch.closure }

```python
nodes.geometry.converter.Switch.closure(switch=False, false=None, true=None)
```

Create Switch with operation 'Closure'.

##### collection { #nodebpy.nodes.geometry.converter.Switch.collection }

```python
nodes.geometry.converter.Switch.collection(switch=False, false=None, true=None)
```

Create Switch with operation 'Collection'.

##### color { #nodebpy.nodes.geometry.converter.Switch.color }

```python
nodes.geometry.converter.Switch.color(switch=False, false=None, true=None)
```

Create Switch with operation 'Color'.

##### float { #nodebpy.nodes.geometry.converter.Switch.float }

```python
nodes.geometry.converter.Switch.float(switch=False, false=0.0, true=0.0)
```

Create Switch with operation 'Float'.

##### geometry { #nodebpy.nodes.geometry.converter.Switch.geometry }

```python
nodes.geometry.converter.Switch.geometry(switch=False, false=None, true=None)
```

Create Switch with operation 'Geometry'.

##### image { #nodebpy.nodes.geometry.converter.Switch.image }

```python
nodes.geometry.converter.Switch.image(switch=False, false=None, true=None)
```

Create Switch with operation 'Image'.

##### integer { #nodebpy.nodes.geometry.converter.Switch.integer }

```python
nodes.geometry.converter.Switch.integer(switch=False, false=0, true=0)
```

Create Switch with operation 'Integer'.

##### material { #nodebpy.nodes.geometry.converter.Switch.material }

```python
nodes.geometry.converter.Switch.material(switch=False, false=None, true=None)
```

Create Switch with operation 'Material'.

##### matrix { #nodebpy.nodes.geometry.converter.Switch.matrix }

```python
nodes.geometry.converter.Switch.matrix(switch=False, false=None, true=None)
```

Create Switch with operation 'Matrix'.

##### menu { #nodebpy.nodes.geometry.converter.Switch.menu }

```python
nodes.geometry.converter.Switch.menu(switch=False, false='', true='')
```

Create Switch with operation 'Menu'.

##### object { #nodebpy.nodes.geometry.converter.Switch.object }

```python
nodes.geometry.converter.Switch.object(switch=False, false=None, true=None)
```

Create Switch with operation 'Object'.

##### rotation { #nodebpy.nodes.geometry.converter.Switch.rotation }

```python
nodes.geometry.converter.Switch.rotation(switch=False, false=None, true=None)
```

Create Switch with operation 'Rotation'.

##### string { #nodebpy.nodes.geometry.converter.Switch.string }

```python
nodes.geometry.converter.Switch.string(switch=False, false='', true='')
```

Create Switch with operation 'String'.

##### vector { #nodebpy.nodes.geometry.converter.Switch.vector }

```python
nodes.geometry.converter.Switch.vector(switch=False, false=None, true=None)
```

Create Switch with operation 'Vector'.

### TransformDirection { #nodebpy.nodes.geometry.converter.TransformDirection }

```python
nodes.geometry.converter.TransformDirection(direction=None, transform=None)
```

Apply a transformation matrix (excluding translation) to the given vector

#### Attributes

| Name | Description |
| --- | --- |
| [i_direction](#nodebpy.nodes.geometry.converter.TransformDirection.i_direction) | Input socket: Direction |
| [i_transform](#nodebpy.nodes.geometry.converter.TransformDirection.i_transform) | Input socket: Transform |
| [name](#nodebpy.nodes.geometry.converter.TransformDirection.name) |  |
| [node](#nodebpy.nodes.geometry.converter.TransformDirection.node) |  |
| [o_direction](#nodebpy.nodes.geometry.converter.TransformDirection.o_direction) | Output socket: Direction |
| [tree](#nodebpy.nodes.geometry.converter.TransformDirection.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.TransformDirection.type) |  |

### TransformPoint { #nodebpy.nodes.geometry.converter.TransformPoint }

```python
nodes.geometry.converter.TransformPoint(vector=None, transform=None)
```

Apply a transformation matrix to the given vector

#### Attributes

| Name | Description |
| --- | --- |
| [i_transform](#nodebpy.nodes.geometry.converter.TransformPoint.i_transform) | Input socket: Transform |
| [i_vector](#nodebpy.nodes.geometry.converter.TransformPoint.i_vector) | Input socket: Vector |
| [name](#nodebpy.nodes.geometry.converter.TransformPoint.name) |  |
| [node](#nodebpy.nodes.geometry.converter.TransformPoint.node) |  |
| [o_vector](#nodebpy.nodes.geometry.converter.TransformPoint.o_vector) | Output socket: Vector |
| [tree](#nodebpy.nodes.geometry.converter.TransformPoint.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.TransformPoint.type) |  |

### TransposeMatrix { #nodebpy.nodes.geometry.converter.TransposeMatrix }

```python
nodes.geometry.converter.TransposeMatrix(matrix=None)
```

Flip a matrix over its diagonal, turning columns into rows and vice-versa

#### Attributes

| Name | Description |
| --- | --- |
| [i_matrix](#nodebpy.nodes.geometry.converter.TransposeMatrix.i_matrix) | Input socket: Matrix |
| [name](#nodebpy.nodes.geometry.converter.TransposeMatrix.name) |  |
| [node](#nodebpy.nodes.geometry.converter.TransposeMatrix.node) |  |
| [o_matrix](#nodebpy.nodes.geometry.converter.TransposeMatrix.o_matrix) | Output socket: Matrix |
| [tree](#nodebpy.nodes.geometry.converter.TransposeMatrix.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.TransposeMatrix.type) |  |

### UVUnwrap { #nodebpy.nodes.geometry.converter.UVUnwrap }

```python
nodes.geometry.converter.UVUnwrap(
    selection=True,
    seam=False,
    margin=0.001,
    fill_holes=True,
    method='Angle Based',
)
```

Generate a UV map based on seam edges

#### Attributes

| Name | Description |
| --- | --- |
| [i_fill_holes](#nodebpy.nodes.geometry.converter.UVUnwrap.i_fill_holes) | Input socket: Fill Holes |
| [i_margin](#nodebpy.nodes.geometry.converter.UVUnwrap.i_margin) | Input socket: Margin |
| [i_method](#nodebpy.nodes.geometry.converter.UVUnwrap.i_method) | Input socket: Method |
| [i_seam](#nodebpy.nodes.geometry.converter.UVUnwrap.i_seam) | Input socket: Seam |
| [i_selection](#nodebpy.nodes.geometry.converter.UVUnwrap.i_selection) | Input socket: Selection |
| [name](#nodebpy.nodes.geometry.converter.UVUnwrap.name) |  |
| [node](#nodebpy.nodes.geometry.converter.UVUnwrap.node) |  |
| [o_uv](#nodebpy.nodes.geometry.converter.UVUnwrap.o_uv) | Output socket: UV |
| [tree](#nodebpy.nodes.geometry.converter.UVUnwrap.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.UVUnwrap.type) |  |

### ValueToString { #nodebpy.nodes.geometry.converter.ValueToString }

```python
nodes.geometry.converter.ValueToString(
    value=0.0,
    decimals=0,
    *,
    data_type='FLOAT',
)
```

Generate a string representation of the given input value

#### Attributes

| Name | Description |
| --- | --- |
| [data_type](#nodebpy.nodes.geometry.converter.ValueToString.data_type) |  |
| [i_decimals](#nodebpy.nodes.geometry.converter.ValueToString.i_decimals) | Input socket: Decimals |
| [i_value](#nodebpy.nodes.geometry.converter.ValueToString.i_value) | Input socket: Value |
| [name](#nodebpy.nodes.geometry.converter.ValueToString.name) |  |
| [node](#nodebpy.nodes.geometry.converter.ValueToString.node) |  |
| [o_string](#nodebpy.nodes.geometry.converter.ValueToString.o_string) | Output socket: String |
| [tree](#nodebpy.nodes.geometry.converter.ValueToString.tree) |  |
| [type](#nodebpy.nodes.geometry.converter.ValueToString.type) |  |

#### Methods

| Name | Description |
| --- | --- |
| [float](#nodebpy.nodes.geometry.converter.ValueToString.float) | Create Value to String with operation 'Float'. |
| [integer](#nodebpy.nodes.geometry.converter.ValueToString.integer) | Create Value to String with operation 'Integer'. |

##### float { #nodebpy.nodes.geometry.converter.ValueToString.float }

```python
nodes.geometry.converter.ValueToString.float(value=0.0, decimals=0)
```

Create Value to String with operation 'Float'.

##### integer { #nodebpy.nodes.geometry.converter.ValueToString.integer }

```python
nodes.geometry.converter.ValueToString.integer(value=0)
```

Create Value to String with operation 'Integer'.